export interface OrganismPart {
  name: string;
  description: string;
  color: string;
}

export interface OrganismData {
  id: string;
  name: string;
  scientificName: string;
  emoji: string;
  color: string;
  accentColor: string;
  type: string;
  size: string;
  habitat: string;
  reproduction: string;
  description: string;
  funFact: string;
  taxonomy: {
    domain: string;
    kingdom: string;
    phylum: string;
    class: string;
    order: string;
    family: string;
    genus: string;
    species: string;
  };
  parts: OrganismPart[];
}

export const ORGANISMS: OrganismData[] = [
  {
    id: "amoeba",
    name: "Amoeba",
    scientificName: "Amoeba proteus",
    emoji: "🫧",
    color: "#39FF14",
    accentColor: "#2ECC71",
    type: "Protozoa",
    size: "0.1 – 0.5 mm",
    habitat: "Freshwater ponds, soil, decaying matter",
    reproduction: "Binary fission (asexual)",
    description: "A shapeless unicellular organism that moves by extending temporary projections called pseudopods. It engulfs food through phagocytosis.",
    funFact: "Amoeba can change shape constantly — it has no fixed form and moves like flowing jelly!",
    taxonomy: { domain: "Eukaryota", kingdom: "Protozoa", phylum: "Amoebozoa", class: "Tubulinea", order: "Tubulinida", family: "Amoebidae", genus: "Amoeba", species: "A. proteus" },
    parts: [
      { name: "Plasma Membrane", description: "Thin flexible boundary controlling substance movement", color: "#39FF14" },
      { name: "Pseudopods", description: "Temporary cytoplasmic projections for movement & feeding", color: "#2ECC71" },
      { name: "Nucleus", description: "Control center containing genetic material (DNA)", color: "#6C3483" },
      { name: "Contractile Vacuole", description: "Pumps out excess water to maintain osmotic balance", color: "#3498DB" },
      { name: "Food Vacuoles", description: "Digest engulfed food particles with enzymes", color: "#E67E22" },
      { name: "Endoplasm", description: "Inner granular cytoplasm suspending organelles", color: "#27AE60" },
      { name: "Ectoplasm", description: "Clear outer gel-like layer aiding movement", color: "#A9DFBF" },
    ],
  },
  {
    id: "ecoli",
    name: "E. coli",
    scientificName: "Escherichia coli",
    emoji: "🦠",
    color: "#EF9F27",
    accentColor: "#F5B041",
    type: "Bacteria",
    size: "~2 μm length",
    habitat: "Intestines of warm-blooded organisms, soil, water",
    reproduction: "Binary fission (every 20 min)",
    description: "A gram-negative, rod-shaped bacterium commonly found in the lower intestine. Most strains are harmless and vital for digestion.",
    funFact: "E. coli can divide every 20 minutes — one cell can become billions in just 24 hours!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Proteobacteria", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae", genus: "Escherichia", species: "E. coli" },
    parts: [
      { name: "Cell Envelope", description: "Multi-layered barrier protecting the cell", color: "#EF9F27" },
      { name: "Flagella", description: "Long whip-like structures for motility", color: "#F0E68C" },
      { name: "Pili (Fimbriae)", description: "Short hair-like structures for attachment", color: "#E8DAEF" },
      { name: "Nucleoid (DNA)", description: "Region containing the circular bacterial chromosome", color: "#8E44AD" },
      { name: "Ribosomes", description: "Sites of protein synthesis (70S)", color: "#D5D8DC" },
      { name: "Plasmid", description: "Small circular DNA molecules replicating independently", color: "#FF6B6B" },
      { name: "Cytoplasm", description: "Gel-like substance containing enzymes and ribosomes", color: "#FAD7A0" },
    ],
  },
  {
    id: "chlorella",
    name: "Chlorella",
    scientificName: "Chlorella vulgaris",
    emoji: "🌿",
    color: "#2ECC71",
    accentColor: "#1ABC9C",
    type: "Green Algae",
    size: "2 – 10 μm",
    habitat: "Freshwater, saltwater, damp soil",
    reproduction: "Autospores (asexual)",
    description: "A single-celled spherical green alga with high photosynthetic efficiency. Widely studied as a superfood due to its exceptional nutritional profile.",
    funFact: "Chlorella contains 50-60% protein by dry weight and produces oxygen through photosynthesis!",
    taxonomy: { domain: "Eukaryota", kingdom: "Plantae", phylum: "Chlorophyta", class: "Trebouxiophyceae", order: "Chlorellales", family: "Chlorellaceae", genus: "Chlorella", species: "C. vulgaris" },
    parts: [
      { name: "Cell Wall", description: "Rigid glycoprotein layer providing shape and protection", color: "#1D8348" },
      { name: "Cell Membrane", description: "Semi-permeable lipid bilayer regulating transport", color: "#27AE60" },
      { name: "Chloroplast", description: "Cup-shaped organelle for photosynthesis (chlorophyll a & b)", color: "#2ECC71" },
      { name: "Pyrenoid", description: "Dense proteinaceous body for CO₂ fixation and starch synthesis", color: "#8E44AD" },
      { name: "Starch Grains", description: "Stored food as insoluble starch within chloroplast", color: "#F7DC6F" },
      { name: "Nucleus", description: "Contains DNA and controls cellular activities", color: "#2980B9" },
      { name: "Cytoplasm", description: "Jelly-like matrix for metabolic reactions", color: "#ABEBC6" },
    ],
  },
  {
    id: "volvox",
    name: "Volvox",
    scientificName: "Volvox globator",
    emoji: "🟢",
    color: "#1D9E75",
    accentColor: "#16A085",
    type: "Colonial Green Algae",
    size: "100 – 500 μm",
    habitat: "Freshwater ponds and ditches",
    reproduction: "Both asexual (daughter colonies) and sexual",
    description: "A colonial organism forming a hollow sphere of up to 50,000 biflagellate cells connected by cytoplasmic bridges.",
    funFact: "Volvox spins through water using coordinated flagella — it looks like a tiny green disco ball!",
    taxonomy: { domain: "Eukaryota", kingdom: "Plantae", phylum: "Chlorophyta", class: "Chlorophyceae", order: "Volvocales", family: "Volvocaceae", genus: "Volvox", species: "V. globator" },
    parts: [
      { name: "Somatic Cells", description: "Surface cells with flagella for movement", color: "#1D9E75" },
      { name: "Daughter Colonies", description: "New colonies forming inside the parent sphere", color: "#27AE60" },
      { name: "Extracellular Matrix", description: "Gelatinous layer holding the colony together", color: "#A9DFBF" },
      { name: "Flagella", description: "Two unequal flagella per cell for coordinated swimming", color: "#F7DC6F" },
      { name: "Chloroplast", description: "Cup-shaped photosynthetic organelle in each cell", color: "#2ECC71" },
      { name: "Eyespot (Stigma)", description: "Red eyespot detecting light intensity for phototaxis", color: "#E74C3C" },
    ],
  },
  {
    id: "paramecium",
    name: "Paramecium",
    scientificName: "Paramecium caudatum",
    emoji: "🥿",
    color: "#3498DB",
    accentColor: "#2980B9",
    type: "Ciliate Protozoa",
    size: "150 – 300 μm",
    habitat: "Freshwater with decaying organic matter",
    reproduction: "Binary fission and conjugation",
    description: "A slipper-shaped unicellular organism covered in cilia. One of the most studied protists, known for its complex behavior despite being a single cell.",
    funFact: "Paramecium has two nuclei — a macronucleus for daily functions and a micronucleus for reproduction!",
    taxonomy: { domain: "Eukaryota", kingdom: "Protista", phylum: "Ciliophora", class: "Oligohymenophorea", order: "Peniculida", family: "Parameciidae", genus: "Paramecium", species: "P. caudatum" },
    parts: [
      { name: "Cilia", description: "Hair-like structures covering the body for locomotion", color: "#85C1E9" },
      { name: "Oral Groove", description: "Funnel-shaped depression leading to the cell mouth", color: "#F39C12" },
      { name: "Macronucleus", description: "Large nucleus controlling cell metabolism", color: "#8E44AD" },
      { name: "Micronucleus", description: "Small nucleus for genetic exchange during conjugation", color: "#6C3483" },
      { name: "Contractile Vacuoles", description: "Two star-shaped vacuoles expelling excess water", color: "#3498DB" },
      { name: "Trichocysts", description: "Defensive dart-like organelles beneath the pellicle", color: "#E74C3C" },
      { name: "Food Vacuoles", description: "Circulate through cytoplasm digesting bacteria", color: "#E67E22" },
    ],
  },
  {
    id: "euglena",
    name: "Euglena",
    scientificName: "Euglena gracilis",
    emoji: "🔬",
    color: "#27AE60",
    accentColor: "#1ABC9C",
    type: "Euglenoid Flagellate",
    size: "35 – 55 μm",
    habitat: "Freshwater, especially nutrient-rich ponds",
    reproduction: "Longitudinal binary fission",
    description: "A unique single-celled organism that can photosynthesize like a plant AND consume food like an animal — a true mixotroph.",
    funFact: "Euglena is both plant and animal! It photosynthesizes in sunlight but eats food particles in the dark.",
    taxonomy: { domain: "Eukaryota", kingdom: "Excavata", phylum: "Euglenozoa", class: "Euglenoidea", order: "Euglenales", family: "Euglenaceae", genus: "Euglena", species: "E. gracilis" },
    parts: [
      { name: "Flagellum", description: "Long whip-like structure emerging from anterior for locomotion", color: "#F7DC6F" },
      { name: "Eyespot (Stigma)", description: "Orange-red photoreceptor detecting light direction", color: "#E74C3C" },
      { name: "Chloroplasts", description: "Multiple disc-shaped organelles for photosynthesis", color: "#2ECC71" },
      { name: "Pellicle", description: "Flexible protein strips allowing shape changes", color: "#1ABC9C" },
      { name: "Paramylon Granules", description: "Unique carbohydrate energy storage bodies", color: "#F0E68C" },
      { name: "Nucleus", description: "Large central nucleus with visible nucleolus", color: "#8E44AD" },
      { name: "Contractile Vacuole", description: "Osmoregulatory organelle near the reservoir", color: "#3498DB" },
    ],
  },
  {
    id: "dna-helix",
    name: "DNA Double Helix",
    scientificName: "Deoxyribonucleic Acid",
    emoji: "🧬",
    color: "#E74C3C",
    accentColor: "#C0392B",
    type: "Nucleic Acid",
    size: "~2 nm diameter",
    habitat: "Nucleus of every living cell",
    reproduction: "Semi-conservative replication",
    description: "The molecule of life — a double helix of two antiparallel strands encoding all genetic information needed to build and maintain living organisms.",
    funFact: "If you stretched out all the DNA in one human cell, it would be about 2 meters long — yet it fits in a nucleus just 6 μm wide!",
    taxonomy: { domain: "Universal", kingdom: "—", phylum: "—", class: "—", order: "—", family: "—", genus: "—", species: "—" },
    parts: [
      { name: "Sugar-Phosphate Backbone", description: "Alternating deoxyribose sugar and phosphate groups forming the helix rails", color: "#5DADE2" },
      { name: "Adenine (A)", description: "Purine base pairing with Thymine via 2 hydrogen bonds", color: "#E74C3C" },
      { name: "Thymine (T)", description: "Pyrimidine base pairing with Adenine via 2 hydrogen bonds", color: "#3498DB" },
      { name: "Guanine (G)", description: "Purine base pairing with Cytosine via 3 hydrogen bonds", color: "#2ECC71" },
      { name: "Cytosine (C)", description: "Pyrimidine base pairing with Guanine via 3 hydrogen bonds", color: "#F1C40F" },
      { name: "Hydrogen Bonds", description: "Weak bonds holding base pairs together (2 for A-T, 3 for G-C)", color: "#FF69B4" },
      { name: "Major & Minor Grooves", description: "Spiral grooves where proteins bind to read DNA", color: "#9B59B6" },
    ],
  },
  {
    id: "animal-cell",
    name: "Animal Cell",
    scientificName: "Eukaryotic Animal Cell",
    emoji: "🔴",
    color: "#E74C3C",
    accentColor: "#C0392B",
    type: "Eukaryotic Cell",
    size: "10 – 30 μm",
    habitat: "All animal tissues",
    reproduction: "Mitosis and meiosis",
    description: "The fundamental unit of animal life. Lacks a cell wall and chloroplasts but contains specialized organelles for complex functions.",
    funFact: "The human body contains approximately 37.2 trillion animal cells working together!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "—", class: "—", order: "—", family: "—", genus: "—", species: "—" },
    parts: [
      { name: "Cell Membrane", description: "Phospholipid bilayer controlling entry and exit", color: "#E74C3C" },
      { name: "Nucleus", description: "Contains DNA — the control center", color: "#2980B9" },
      { name: "Mitochondria", description: "Powerhouse — produces ATP via cellular respiration", color: "#1D9E75" },
      { name: "Endoplasmic Reticulum", description: "Rough (protein) and Smooth (lipid) synthesis network", color: "#9B59B6" },
      { name: "Golgi Apparatus", description: "Packages and ships proteins to destinations", color: "#F39C12" },
      { name: "Lysosomes", description: "Digestive enzymes breaking down waste", color: "#E67E22" },
      { name: "Centrioles", description: "Organize spindle fibers during cell division", color: "#1ABC9C" },
      { name: "Ribosomes", description: "Protein factories reading mRNA", color: "#BDC3C7" },
    ],
  },
  {
    id: "plant-cell",
    name: "Plant Cell",
    scientificName: "Eukaryotic Plant Cell",
    emoji: "🌱",
    color: "#27AE60",
    accentColor: "#229954",
    type: "Eukaryotic Cell",
    size: "10 – 100 μm",
    habitat: "All plant tissues",
    reproduction: "Mitosis and meiosis",
    description: "The building block of all plants. Distinguished by a rigid cell wall, large central vacuole, and chloroplasts for photosynthesis.",
    funFact: "The central vacuole can occupy up to 90% of the plant cell's volume, storing water and maintaining turgor pressure!",
    taxonomy: { domain: "Eukaryota", kingdom: "Plantae", phylum: "—", class: "—", order: "—", family: "—", genus: "—", species: "—" },
    parts: [
      { name: "Cell Wall", description: "Rigid cellulose wall providing structure and protection", color: "#1D8348" },
      { name: "Cell Membrane", description: "Semi-permeable lipid bilayer inside the wall", color: "#27AE60" },
      { name: "Chloroplasts", description: "Green organelles converting sunlight to glucose", color: "#2ECC71" },
      { name: "Central Vacuole", description: "Large fluid-filled sac maintaining turgor pressure", color: "#85C1E9" },
      { name: "Nucleus", description: "DNA-containing control center", color: "#2980B9" },
      { name: "Mitochondria", description: "Energy production via cellular respiration", color: "#1D9E75" },
      { name: "Endoplasmic Reticulum", description: "Protein and lipid synthesis network", color: "#9B59B6" },
      { name: "Plasmodesmata", description: "Channels between cells for communication", color: "#F39C12" },
    ],
  },
  {
    id: "bacteria",
    name: "Bacteria Cell",
    scientificName: "Prokaryotic Bacterium",
    emoji: "🧫",
    color: "#F39C12",
    accentColor: "#E67E22",
    type: "Prokaryotic Cell",
    size: "0.2 – 5 μm",
    habitat: "Everywhere — soil, water, air, inside organisms",
    reproduction: "Binary fission",
    description: "The simplest and most ancient form of life. Prokaryotic cells lacking a true nucleus, yet incredibly diverse and essential for all ecosystems.",
    funFact: "There are more bacteria in your body than human cells — about 38 trillion!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Various", class: "—", order: "—", family: "—", genus: "—", species: "—" },
    parts: [
      { name: "Capsule", description: "Outer protective polysaccharide layer (some species)", color: "#F5CBA7" },
      { name: "Cell Wall", description: "Rigid peptidoglycan layer providing shape", color: "#F39C12" },
      { name: "Cell Membrane", description: "Phospholipid bilayer controlling transport", color: "#E67E22" },
      { name: "Nucleoid", description: "Region of circular DNA (no membrane-bound nucleus)", color: "#8E44AD" },
      { name: "Ribosomes (70S)", description: "Smaller ribosomes for protein synthesis", color: "#BDC3C7" },
      { name: "Flagellum", description: "Tail-like structure for swimming motility", color: "#F7DC6F" },
      { name: "Plasmid", description: "Extra-chromosomal circular DNA with beneficial genes", color: "#E74C3C" },
    ],
  },
  {
    id: "tardigrade",
    name: "Tardigrade",
    scientificName: "Hypsibius dujardini",
    emoji: "🐻‍❄️",
    color: "#D2B48C",
    accentColor: "#8B4513",
    type: "Micro-animal",
    size: "0.5 mm",
    habitat: "Mosses, lichens, deep sea, mud volcanoes",
    reproduction: "Sexual and Parthenogenesis",
    description: "Also known as 'Water Bears', these 8-legged micro-animals are famous for their extreme resilience, surviving the vacuum of space, radiation, and extreme temperatures.",
    funFact: "Tardigrades can enter a state called 'cryptobiosis' where they lose 97% of their water and can survive for decades without food!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Tardigrada", class: "Eutardigrada", order: "Parachela", family: "Hypsibiidae", genus: "Hypsibius", species: "H. dujardini" },
    parts: [
      { name: "8 Legs", description: "Four pairs of stubby legs ending in claws", color: "#A0522D" },
      { name: "Cuticle", description: "Tough but flexible outer layer that can be molted", color: "#DEB887" },
      { name: "Stylets", description: "Needle-like structures for piercing plant cells or prey", color: "#F4A460" },
      { name: "Tun", description: "A dried-up dormant state for surviving extreme environments", color: "#CD853F" },
      { name: "Simple Eyes", description: "Basic light-sensing pigment cups", color: "#000000" },
    ],
  },
  {
    id: "diatom",
    name: "Diatom",
    scientificName: "Fragilaria crotonensis",
    emoji: "💎",
    color: "#5DADE2",
    accentColor: "#3498DB",
    type: "Algae",
    size: "20 – 200 μm",
    habitat: "Oceans, freshwater, soils",
    reproduction: "Binary fission and Sexual",
    description: "Single-celled algae with a transparent cell wall made of silica (glass). They are major producers of oxygen on Earth.",
    funFact: "Diatoms produce about 20% to 50% of the oxygen we breathe — more than all the world's tropical rainforests combined!",
    taxonomy: { domain: "Eukaryota", kingdom: "Chromista", phylum: "Bacillariophyta", class: "Bacillariophyceae", order: "Fragilariales", family: "Fragilariaceae", genus: "Fragilaria", species: "F. crotonensis" },
    parts: [
      { name: "Frustule", description: "Intricate silica shell consisting of two valves", color: "#EBF5FB" },
      { name: "Chloroplasts", description: "Golden-brown organelles for photosynthesis", color: "#D4AC0D" },
      { name: "Oil Droplets", description: "Stored energy that also aids in buoyancy", color: "#F1C40F" },
      { name: "Raphe", description: "Slit in the valve used for gliding movement", color: "#2E86C1" },
    ],
  },
  {
    id: "spirogyra",
    name: "Spirogyra",
    scientificName: "Spirogyra porticalis",
    emoji: "🌀",
    color: "#2ECC71",
    accentColor: "#27AE60",
    type: "Green Algae",
    size: "10 – 100 μm (width)",
    habitat: "Freshwater ponds and ditches",
    reproduction: "Fragmentation and Conjugation",
    description: "A filamentous green alga named for its spiral-shaped chloroplasts. It often forms slimy green mats on the surface of water.",
    funFact: "The spiral chloroplasts rotate to maximize sunlight exposure, looking like a green spiral staircase under a microscope!",
    taxonomy: { domain: "Eukaryota", kingdom: "Plantae", phylum: "Charophyta", class: "Zygnematophyceae", order: "Zygnematales", family: "Zygnemataceae", genus: "Spirogyra", species: "S. porticalis" },
    parts: [
      { name: "Spiral Chloroplast", description: "Ribbon-like chloroplast winding around the cell", color: "#39FF14" },
      { name: "Pyrenoids", description: "Small round bodies on the chloroplast for starch storage", color: "#1D8348" },
      { name: "Cytoplasmic Strands", description: "Thin threads suspending the nucleus in the center", color: "#A9DFBF" },
      { name: "Cell Wall", description: "Two-layered wall with an inner cellulose layer", color: "#229954" },
    ],
  },
  {
    id: "stentor",
    name: "Stentor",
    scientificName: "Stentor coeruleus",
    emoji: "🎺",
    color: "#3498DB",
    accentColor: "#2980B9",
    type: "Ciliate",
    size: "0.5 – 2.0 mm",
    habitat: "Freshwater lakes and streams",
    reproduction: "Binary fission and Conjugation",
    description: "One of the largest single-celled organisms, shaped like a trumpet. It is known for its beautiful blue color and incredible regenerative powers.",
    funFact: "If you cut a Stentor into small pieces, each piece with a part of the nucleus can regrow into a full organism!",
    taxonomy: { domain: "Eukaryota", kingdom: "Chromista", phylum: "Ciliophora", class: "Heterotrichea", order: "Heterotrichida", family: "Stentoridae", genus: "Stentor", species: "S. coeruleus" },
    parts: [
      { name: "Ciliary Wrap", description: "Cilia around the 'mouth' to create water vortexes", color: "#5DADE2" },
      { name: "Macronucleus", description: "Chain-like nucleus resembling a string of beads", color: "#6C3483" },
      { name: "Contractile Stalk", description: "Allows the cell to rapidly contract into a ball", color: "#2E86C1" },
      { name: "Stentorin", description: "Blue pigment used for light sensing and defense", color: "#1F618D" },
    ],
  },
  {
    id: "halobacterium",
    name: "Halobacterium",
    scientificName: "Halobacterium salinarum",
    emoji: "🧂",
    color: "#FF7F50",
    accentColor: "#FF4500",
    type: "Archaea",
    size: "1 – 5 μm",
    habitat: "Hypersaline lakes (e.g., Dead Sea, Great Salt Lake)",
    reproduction: "Binary fission",
    description: "An extreme halophile (salt-lover) that belongs to the Archaea domain. It colors salt lakes pink or red due to its pigments.",
    funFact: "Halobacterium uses a protein called bacteriorhodopsin to capture light energy, similar to the pigment in human eyes!",
    taxonomy: { domain: "Archaea", kingdom: "Archaea", phylum: "Euryarchaeota", class: "Halobacteria", order: "Halobacteriales", family: "Halobacteriaceae", genus: "Halobacterium", species: "H. salinarum" },
    parts: [
      { name: "Gas Vesicles", description: "Small balloons providing buoyancy to stay near the surface", color: "#F5B041" },
      { name: "Bacteriorhodopsin", description: "Purple protein that acts as a light-driven proton pump", color: "#8E44AD" },
      { name: "Halophilic Enzymes", description: "Proteins that only function in high salt concentrations", color: "#D35400" },
    ],
  },
  {
    id: "cyanobacteria",
    name: "Cyanobacteria",
    scientificName: "Anabaena variabilis",
    emoji: "🟢",
    color: "#1ABC9C",
    accentColor: "#16A085",
    type: "Bacteria",
    size: "5 – 10 μm",
    habitat: "Oceans, freshwater, moist soil, rocks",
    reproduction: "Binary fission and Fragmentation",
    description: "The 'Blue-Green Algae' that first produced oxygen on Earth. They often form long chains of cells called filaments.",
    funFact: "Cyanobacteria are responsible for the 'Great Oxidation Event' 2.4 billion years ago, which made Earth's atmosphere breathable!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Cyanobacteria", class: "Cyanophyceae", order: "Nostocales", family: "Nostocaceae", genus: "Anabaena", species: "A. variabilis" },
    parts: [
      { name: "Heterocyst", description: "Specialized cells that fix nitrogen from the air", color: "#F1C40F" },
      { name: "Akinete", description: "Thick-walled dormant cells for surviving harsh conditions", color: "#D4AC0D" },
      { name: "Phycobilisomes", description: "Pigment complexes for capturing light energy", color: "#1D8348" },
      { name: "Thylakoid Membranes", description: "Internal membranes where photosynthesis occurs", color: "#16A085" },
    ],
  },
  {
    id: "yeast",
    name: "Yeast",
    scientificName: "Saccharomyces cerevisiae",
    emoji: "🍞",
    color: "#F5CBA7",
    accentColor: "#DC7633",
    type: "Fungi",
    size: "5 – 10 μm",
    habitat: "Sugar-rich environments (fruits, nectar, dough)",
    reproduction: "Budding (asexual)",
    description: "A single-celled fungus used for thousands of years in baking and brewing. It converts sugar into alcohol and carbon dioxide.",
    funFact: "Yeast was the first eukaryotic organism to have its entire genome sequenced, in 1996!",
    taxonomy: { domain: "Eukaryota", kingdom: "Fungi", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Saccharomycetaceae", genus: "Saccharomyces", species: "S. cerevisiae" },
    parts: [
      { name: "Bud", description: "A small daughter cell growing out of the parent cell", color: "#EB984E" },
      { name: "Bud Scar", description: "A mark left on the parent cell after a daughter cell detaches", color: "#A04000" },
      { name: "Vacuole", description: "Large organelle for nutrient storage and waste breakdown", color: "#D5D8DC" },
    ],
  },
  {
    id: "penicillium",
    name: "Penicillium",
    scientificName: "Penicillium chrysogenum",
    emoji: "🍄",
    color: "#A9DFBF",
    accentColor: "#27AE60",
    type: "Fungi",
    size: "Filamentous",
    habitat: "Soil, decaying vegetation, food (bread, fruit)",
    reproduction: "Conidia (asexual spores)",
    description: "The mold used to create Penicillin, the world's first antibiotic. It looks like a tiny brush under a microscope.",
    funFact: "Alexander Fleming discovered Penicillin in 1928 when he noticed mold on a petri dish had killed the surrounding bacteria!",
    taxonomy: { domain: "Eukaryota", kingdom: "Fungi", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Aspergillaceae", genus: "Penicillium", species: "P. chrysogenum" },
    parts: [
      { name: "Conidiophore", description: "Specialized stalk that produces spores", color: "#1D8348" },
      { name: "Conidia", description: "Spore-like structures arranged in chains", color: "#52BE80" },
      { name: "Mycelium", description: "Network of thread-like hyphae forming the mold body", color: "#D1F2EB" },
    ],
  },
  {
    id: "radiolaria",
    name: "Radiolaria",
    scientificName: "Actinomma asteracanthion",
    emoji: "❄️",
    color: "#D6EAF8",
    accentColor: "#3498DB",
    type: "Protozoa",
    size: "0.1 – 0.2 mm",
    habitat: "Marine plankton (oceans)",
    reproduction: "Binary fission",
    description: "Protozoa that produce intricate mineral skeletons, usually with a central capsule. Their remains form 'radiolarian ooze' on the ocean floor.",
    funFact: "Radiolarian skeletons are so beautiful and geometric that they inspired famous artists like Ernst Haeckel!",
    taxonomy: { domain: "Eukaryota", kingdom: "Chromista", phylum: "Retaria", class: "Polycystina", order: "Spumellaria", family: "Actinommidae", genus: "Actinomma", species: "A. asteracanthion" },
    parts: [
      { name: "Central Capsule", description: "Divides the cell into inner and outer zones", color: "#5DADE2" },
      { name: "Siliceous Skeleton", description: "Complex glass-like framework with spines", color: "#FFFFFF" },
      { name: "Axopodia", description: "Needle-like projections for catching prey", color: "#AED6F1" },
    ],
  },
  {
    id: "dinoflagellate",
    name: "Dinoflagellate",
    scientificName: "Noctiluca scintillans",
    emoji: "✨",
    color: "#3498DB",
    accentColor: "#1ABC9C",
    type: "Protist",
    size: "200 – 2000 μm",
    habitat: "Marine and freshwater environments",
    reproduction: "Binary fission and Sexual",
    description: "Marine plankton famous for bioluminescence—creating 'glowing waves' at night. Some species cause harmful 'Red Tides'.",
    funFact: "The word 'Dinoflagellate' comes from the Greek 'dinos' (whirling), describing how they spin through the water!",
    taxonomy: { domain: "Eukaryota", kingdom: "Chromista", phylum: "Myzozoa", class: "Dinophyceae", order: "Noctilucales", family: "Noctilucaceae", genus: "Noctiluca", species: "N. scintillans" },
    parts: [
      { name: "Theca", description: "Armored plates made of cellulose", color: "#85C1E9" },
      { name: "Transverse Flagellum", description: "Ribbon-like flagellum that makes the cell spin", color: "#F7DC6F" },
      { name: "Longitudinal Flagellum", description: "Acts as a rudder for steering", color: "#F1C40F" },
      { name: "Scintillons", description: "Bioluminescent organelles that flash when disturbed", color: "#39FF14" },
    ],
  },
  {
    id: "spirochete",
    name: "Spirochete",
    scientificName: "Treponema pallidum",
    emoji: "➰",
    color: "#F1948A",
    accentColor: "#C0392B",
    type: "Bacteria",
    size: "5 – 20 μm",
    habitat: "Aquatic environments and animal hosts",
    reproduction: "Binary fission",
    description: "Helically coiled bacteria that move using a corkscrew motion. They are unique for having internal flagella called endoflagella.",
    funFact: "Spirochetes move like a corkscrew, allowing them to swim through thick fluids like mucus that stop other bacteria!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Spirochaetes", class: "Spirochaetia", order: "Spirochaetales", family: "Treponemataceae", genus: "Treponema", species: "T. pallidum" },
    parts: [
      { name: "Axial Filaments", description: "Internal flagella that wrap around the cell body", color: "#E74C3C" },
      { name: "Helical Body", description: "Flexible spiral-shaped cell wall", color: "#FAD7A0" },
      { name: "Outer Membrane", description: "Sheath covering the axial filaments", color: "#F1948A" },
    ],
  },
  {
    id: "slime-mold",
    name: "Slime Mold",
    scientificName: "Physarum polycephalum",
    emoji: "🟡",
    color: "#F4D03F",
    accentColor: "#D4AC0D",
    type: "Amoebozoa",
    size: "Variable (up to meters)",
    habitat: "Damp leaf litter, rotting logs",
    reproduction: "Spores",
    description: "A single giant cell with thousands of nuclei. It is famous for its 'intelligence'—being able to solve mazes and find efficient paths.",
    funFact: "Slime molds can 'remember' where they've been by leaving behind a trail of translucent slime!",
    taxonomy: { domain: "Eukaryota", kingdom: "Amoebozoa", phylum: "Evosea", class: "Myxogastria", order: "Physarales", family: "Physaraceae", genus: "Physarum", species: "P. polycephalum" },
    parts: [
      { name: "Plasmodium", description: "The vegetative stage consisting of a giant multi-nucleated cell", color: "#F1C40F" },
      { name: "Veins", description: "Network of tubes used for transporting nutrients", color: "#D4AC0D" },
      { name: "Cytoplasmic Streaming", description: "Rapid rhythmic movement of fluid inside the veins", color: "#B7950B" },
    ],
  },
  {
    id: "vorticella",
    name: "Vorticella",
    scientificName: "Vorticella campanula",
    emoji: "🔔",
    color: "#85C1E9",
    accentColor: "#3498DB",
    type: "Ciliate",
    size: "50 – 150 μm",
    habitat: "Stagnant freshwater and ponds",
    reproduction: "Binary fission and Conjugation",
    description: "Bell-shaped ciliates attached to surfaces by a long contractile stalk. They create water currents to pull food into their mouths.",
    funFact: "Vorticella's stalk can contract in a split second at a speed equivalent to a human jumping over a skyscraper!",
    taxonomy: { domain: "Eukaryota", kingdom: "Chromista", phylum: "Ciliophora", class: "Oligohymenophorea", order: "Sessilida", family: "Vorticellidae", genus: "Vorticella", species: "V. campanula" },
    parts: [
      { name: "Bell (Zooid)", description: "The main body of the cell shaped like an inverted bell", color: "#AED6F1" },
      { name: "Ciliary Wreath", description: "Ring of cilia around the top to create a vortex", color: "#3498DB" },
      { name: "Contractile Stalk", description: "Contains a spring-like fiber called a spasmoneme", color: "#2E86C1" },
    ],
  },
  {
    id: "rotifer",
    name: "Rotifer",
    scientificName: "Brachionus calyciflorus",
    emoji: "🎡",
    color: "#FAD7A0",
    accentColor: "#DC7633",
    type: "Micro-animal",
    size: "0.1 – 0.5 mm",
    habitat: "Freshwater, damp soil, mosses",
    reproduction: "Parthenogenesis and Sexual",
    description: "Tiny multi-cellular animals named for their 'wheel-organ'—two rotating rings of cilia that look like spinning wheels.",
    funFact: "Rotifers have a brain, stomach, and kidneys, even though they are smaller than many single-celled protists!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Rotifera", class: "Monogononta", order: "Ploima", family: "Brachionidae", genus: "Brachionus", species: "B. calyciflorus" },
    parts: [
      { name: "Corona", description: "The 'wheel' of cilia used for feeding and swimming", color: "#FDEBD0" },
      { name: "Mastax", description: "Complex muscular pharynx with jaw-like teeth", color: "#E59866" },
      { name: "Foot and Toes", description: "Allows the rotifer to anchor itself to surfaces", color: "#D35400" },
      { name: "Eyespot", description: "Simple light-sensing organ", color: "#C0392B" },
    ],
  },
  {
    id: "nematode",
    name: "Nematode",
    scientificName: "Caenorhabditis elegans",
    emoji: "🪱",
    color: "#FDFEFE",
    accentColor: "#BDC3C7",
    type: "Roundworm",
    size: "1 mm",
    habitat: "Soil, water, inside other organisms",
    reproduction: "Sexual (Hermaphrodites and Males)",
    description: "Microscopic roundworms found in almost every environment. C. elegans is a famous 'model organism' used in aging research.",
    funFact: "C. elegans was the first multi-cellular organism to have its entire genome sequenced and its nervous system fully mapped!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Nematoda", class: "Chromadorea", order: "Rhabditida", family: "Rhabditidae", genus: "Caenorhabditis", species: "C. elegans" },
    parts: [
      { name: "Cuticle", description: "Transparent protective outer layer", color: "#ECF0F1" },
      { name: "Pharynx", description: "Muscular pump used to ingest bacteria", color: "#BDC3C7" },
      { name: "Vulva", description: "Opening through which eggs are laid", color: "#D5D8DC" },
      { name: "Intestine", description: "The main organ for digestion and nutrient storage", color: "#CCD1D1" },
    ],
  },
  {
    id: "trypanosoma",
    name: "Trypanosoma",
    scientificName: "Trypanosoma brucei",
    emoji: "🩸",
    color: "#E6B0AA",
    accentColor: "#943126",
    type: "Protozoa",
    size: "20 μm",
    habitat: "Blood and tissues of animals, Tsetse flies",
    reproduction: "Binary fission",
    description: "Parasitic flagellates that cause diseases like African Sleeping Sickness. They have a unique kineoplast (giant DNA mass).",
    funFact: "Trypanosomes can change their entire surface coating to hide from the host's immune system!",
    taxonomy: { domain: "Eukaryota", kingdom: "Excavata", phylum: "Euglenozoa", class: "Kinetoplastea", order: "Trypanosomatida", family: "Trypanosomatidae", genus: "Trypanosoma", species: "T. brucei" },
    parts: [
      { name: "Undulating Membrane", description: "A fold of the membrane attached to the flagellum", color: "#CD6155" },
      { name: "Kinetoplast", description: "Mass of mitochondrial DNA near the flagellar base", color: "#641E16" },
      { name: "Flagellum", description: "Emerges from the flagellar pocket at the posterior", color: "#F7DC6F" },
    ],
  },
  {
    id: "giardia",
    name: "Giardia",
    scientificName: "Giardia lamblia",
    emoji: "👺",
    color: "#F7DC6F",
    accentColor: "#D4AC0D",
    type: "Protozoa",
    size: "10 – 15 μm",
    habitat: "Intestines of mammals, contaminated water",
    reproduction: "Binary fission",
    description: "A heart-shaped parasite with two nuclei that look like eyes. It causes 'Giardiasis' or 'Beaver Fever' in humans.",
    funFact: "Giardia has two identical nuclei and looks like a face with a goatee when viewed under a microscope!",
    taxonomy: { domain: "Eukaryota", kingdom: "Excavata", phylum: "Metamonada", class: "Fornicata", order: "Diplomonadida", family: "Giardiidae", genus: "Giardia", species: "G. lamblia" },
    parts: [
      { name: "Sucking Disc", description: "Allows the parasite to stick firmly to the intestinal wall", color: "#B7950B" },
      { name: "Two Nuclei", description: "Symmetrical nuclei that look like 'eyes'", color: "#6C3483" },
      { name: "8 Flagella", description: "Four pairs of flagella for movement", color: "#D4AC0D" },
    ],
  },
  {
    id: "streptococcus",
    name: "Streptococcus",
    scientificName: "Streptococcus pyogenes",
    emoji: "📿",
    color: "#D7BDE2",
    accentColor: "#8E44AD",
    type: "Bacteria",
    size: "0.5 – 1.0 μm",
    habitat: "Human skin and throat",
    reproduction: "Binary fission",
    description: "Spherical bacteria that grow in chains. S. pyogenes is responsible for Strep throat and scarlet fever.",
    funFact: "The name 'Streptococcus' comes from Greek 'streptos' (twisted chain) and 'kokkos' (berry)!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Firmicutes", class: "Bacilli", order: "Lactobacillales", family: "Streptococcaceae", genus: "Streptococcus", species: "S. pyogenes" },
    parts: [
      { name: "Cocci Chain", description: "Round cells arranged in a bead-like chain", color: "#AF7AC5" },
      { name: "Hyaluronic Acid Capsule", description: "Helps the bacteria hide from the immune system", color: "#EBDEF0" },
      { name: "M Protein", description: "Hair-like projections that aid in infection", color: "#8E44AD" },
    ],
  },
  {
    id: "bacillus",
    name: "Bacillus",
    scientificName: "Bacillus subtilis",
    emoji: "🥖",
    color: "#FADBD8",
    accentColor: "#E74C3C",
    type: "Bacteria",
    size: "2 – 5 μm",
    habitat: "Soil and vegetation",
    reproduction: "Binary fission and Endospores",
    description: "Rod-shaped bacteria that are very common in soil. They can form tough spores to survive extreme conditions.",
    funFact: "Some Bacillus species can survive for thousands, possibly millions of years as dormant spores!",
    taxonomy: { domain: "Bacteria", kingdom: "Eubacteria", phylum: "Firmicutes", class: "Bacilli", order: "Bacillales", family: "Bacillaceae", genus: "Bacillus", species: "B. subtilis" },
    parts: [
      { name: "Rod Body", description: "Cylindrical cell shape", color: "#F5B7B1" },
      { name: "Endospore", description: "A tough, resistant structure formed inside the cell", color: "#C0392B" },
      { name: "Peritrichous Flagella", description: "Flagella distributed all over the cell surface", color: "#F7DC6F" },
    ],
  },
  {
    id: "methanogen",
    name: "Methanogen",
    scientificName: "Methanocaldococcus jannaschii",
    emoji: "🔥",
    color: "#EB984E",
    accentColor: "#A04000",
    type: "Archaea",
    size: "1 μm",
    habitat: "Hydrothermal vents, digestive tracts",
    reproduction: "Binary fission",
    description: "Archaea that produce methane as a byproduct. Many are extremophiles living at the bottom of the ocean.",
    funFact: "Methanogens in cow stomachs are responsible for a significant portion of global methane emissions!",
    taxonomy: { domain: "Archaea", kingdom: "Archaea", phylum: "Euryarchaeota", class: "Methanococci", order: "Methanococcales", family: "Methanocaldococcaceae", genus: "Methanocaldococcus", species: "M. jannaschii" },
    parts: [
      { name: "Methanogenesis Enzymes", description: "Unique proteins used to produce methane gas", color: "#D35400" },
      { name: "Flagellar Bundle", description: "Used for swimming in extreme environments", color: "#FAD7A0" },
      { name: "S-layer", description: "Crystalline surface protein layer for protection", color: "#DC7633" },
    ],
  },
  {
    id: "daphnia",
    name: "Daphnia",
    scientificName: "Daphnia pulex",
    emoji: "🦐",
    color: "#FAD7A0",
    accentColor: "#E67E22",
    type: "Crustacean",
    size: "0.2 – 5 mm",
    habitat: "Freshwater lakes and ponds",
    reproduction: "Parthenogenesis",
    description: "Often called 'Water Fleas', these tiny crustaceans are transparent, allowing you to see their beating heart and moving organs.",
    funFact: "Daphnia's heart can beat up to 300 times per minute, and you can see it through their clear shell!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Arthropoda", class: "Branchiopoda", order: "Anomopoda", family: "Daphniidae", genus: "Daphnia", species: "D. pulex" },
    parts: [
      { name: "Carapace", description: "Transparent folded shell covering the body", color: "#FDEBD0" },
      { name: "Compound Eye", description: "Single large dark eye made of many small lenses", color: "#17202A" },
      { name: "Second Antennae", description: "Large branched structures used for swimming in jerks", color: "#EB984E" },
      { name: "Beating Heart", description: "Simple muscular tube visible through the shell", color: "#E74C3C" },
    ],
  },
  {
    id: "hydra",
    name: "Hydra",
    scientificName: "Hydra vulgaris",
    emoji: "🐙",
    color: "#2ECC71",
    accentColor: "#27AE60",
    type: "Cnidarian",
    size: "1 – 10 mm",
    habitat: "Freshwater ponds, slow-moving rivers",
    reproduction: "Budding and Sexual",
    description: "A small freshwater relative of jellyfish. It is famous for its biological immortality—it doesn't seem to age at all.",
    funFact: "Hydras can completely regrow their entire body from just a few cells if they are cut into pieces!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Cnidaria", class: "Hydrozoa", order: "Anthoathecata", family: "Hydridae", genus: "Hydra", species: "H. vulgaris" },
    parts: [
      { name: "Tentacles", description: "Long arms equipped with stinging cells to catch prey", color: "#52BE80" },
      { name: "Cnidocytes", description: "Specialized stinging cells for defense and hunting", color: "#E74C3C" },
      { name: "Basal Disc", description: "Sticky foot used to attach to underwater surfaces", color: "#1D8348" },
      { name: "Hypostome", description: "Raised area around the mouth", color: "#27AE60" },
    ],
  },
  {
    id: "ostracod",
    name: "Ostracod",
    scientificName: "Cypridopsis vidua",
    emoji: "🐚",
    color: "#D5DBDB",
    accentColor: "#85929E",
    type: "Crustacean",
    size: "1 mm",
    habitat: "Oceans, freshwater, and even damp soil",
    reproduction: "Sexual and Parthenogenesis",
    description: "Known as 'Seed Shrimp', these micro-crustaceans are encased in a two-part shell like a tiny clam.",
    funFact: "Some deep-sea Ostracods are bioluminescent and spit out glowing clouds of blue chemicals to distract predators!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Arthropoda", class: "Ostracoda", order: "Podocopida", family: "Cypridopsidae", genus: "Cypridopsis", species: "C. vidua" },
    parts: [
      { name: "Bivalve Carapace", description: "Two-part shell that can close completely for protection", color: "#EBEDEF" },
      { name: "Jointed Limbs", description: "Used for swimming, crawling, and feeding", color: "#85929E" },
      { name: "Nauplius Eye", description: "Simple light-sensing central eye", color: "#000000" },
    ],
  },
  {
    id: "planaria",
    name: "Planaria",
    scientificName: "Dugesia tigrina",
    emoji: "👅",
    color: "#F1948A",
    accentColor: "#C0392B",
    type: "Flatworm",
    size: "3 – 15 mm",
    habitat: "Freshwater streams and ponds",
    reproduction: "Fragmentation and Sexual",
    description: "Non-parasitic flatworms with arrow-shaped heads and cross-eyed spots. They have incredible regeneration abilities.",
    funFact: "If you cut a Planaria into four pieces, you will soon have four new, complete flatworms!",
    taxonomy: { domain: "Eukaryota", kingdom: "Animalia", phylum: "Platyhelminthes", class: "Rhabditophora", order: "Tricladida", family: "Dugesiidae", genus: "Dugesia", species: "D. tigrina" },
    parts: [
      { name: "Eyespots (Ocelli)", description: "Simple light-sensing organs that make it look cross-eyed", color: "#17202A" },
      { name: "Auricles", description: "Side flaps on the head used to detect chemicals and food", color: "#E6B0AA" },
      { name: "Pharynx", description: "A tube that comes out of the belly to suck up food", color: "#CD6155" },
    ],
  },
  {
    id: "thermophile",
    name: "Thermophile",
    scientificName: "Pyrococcus furiosus",
    emoji: "🌋",
    color: "#E67E22",
    accentColor: "#BA4A00",
    type: "Archaea",
    size: "1 μm",
    habitat: "Deep-sea hydrothermal vents (100°C+)",
    reproduction: "Binary fission",
    description: "Heat-loving organisms that thrive in boiling water where almost nothing else can survive.",
    funFact: "Thermophiles produce 'heat-stable' enzymes that are used in PCR tests to detect DNA for medicine and forensics!",
    taxonomy: { domain: "Archaea", kingdom: "Archaea", phylum: "Euryarchaeota", class: "Thermococci", order: "Thermococcales", family: "Thermococcaceae", genus: "Pyrococcus", species: "P. furiosus" },
    parts: [
      { name: "Heat-Resistant Membrane", description: "Specialized lipids that don't melt in boiling water", color: "#D35400" },
      { name: "S-layer", description: "Outer protein armor for high-pressure protection", color: "#BA4A00" },
      { name: "DNA Polymerase", description: "Enzymes that can copy DNA even at near-boiling temperatures", color: "#F4D03F" },
    ],
  },
];


export function getOrganismById(id: string): OrganismData | undefined {
  return ORGANISMS.find(o => o.id === id);
}
