export interface VirusPart {
  name: string;
  description: string;
  color: string;
}

export interface VirusData {
  id: string;
  name: string;
  scientificName: string;
  emoji: string;
  color: string;
  accentColor: string;
  type: string;
  shape: string;
  size: string;
  genome: string;
  discoveredYear: string;
  discoveredBy: string;
  transmission: string;
  symptoms: string[];
  treatment: string;
  prevention: string;
  mortality: string;
  description: string;
  funFact: string;
  parts: VirusPart[];
}

export const VIRUSES: VirusData[] = [
  {
    id: "sars-cov-2",
    name: "SARS-CoV-2",
    scientificName: "Severe Acute Respiratory Syndrome Coronavirus 2",
    emoji: "🦠",
    color: "#E24B4A",
    accentColor: "#C0392B",
    type: "Coronavirus",
    shape: "Spherical with crown-like spikes",
    size: "50–200 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "2019",
    discoveredBy: "Zhang Yongzhen's team (China)",
    transmission: "Respiratory droplets, aerosols, contact with contaminated surfaces",
    symptoms: ["Fever", "Dry cough", "Fatigue", "Loss of taste/smell", "Shortness of breath", "Body aches"],
    treatment: "Paxlovid (nirmatrelvir/ritonavir), Remdesivir, Dexamethasone, monoclonal antibodies, supportive care",
    prevention: "mRNA/viral vector vaccines (Pfizer, Moderna, AstraZeneca), masking, social distancing, hand hygiene",
    mortality: "~1-2% (varies by variant and population)",
    description: "The virus responsible for the COVID-19 pandemic. It belongs to the betacoronavirus genus and is characterized by its distinctive spike proteins that form a crown-like (corona) appearance. These spike proteins bind to ACE2 receptors on human cells.",
    funFact: "The name 'corona' comes from Latin for 'crown' — the spike proteins on the virus surface look like a solar corona when viewed under electron microscopy!",
    parts: [
      { name: "Spike Protein (S)", description: "Crown-like projections that bind to ACE2 receptors on host cells — the key to cell entry", color: "#E74C3C" },
      { name: "Lipid Envelope", description: "Fatty outer membrane stolen from host cell — vulnerable to soap and hand sanitizer", color: "#F5B041" },
      { name: "Membrane Protein (M)", description: "Most abundant structural protein shaping the viral envelope", color: "#E24B4A" },
      { name: "Envelope Protein (E)", description: "Small protein involved in virus assembly, release, and pathogenesis", color: "#D4AC0D" },
      { name: "Nucleocapsid (N)", description: "Protein shell packaging the RNA genome in a helical structure", color: "#9B59B6" },
      { name: "RNA Genome", description: "~30,000 nucleotides — one of the largest RNA virus genomes known", color: "#3498DB" },
    ],
  },
  {
    id: "hiv",
    name: "HIV",
    scientificName: "Human Immunodeficiency Virus",
    emoji: "🔴",
    color: "#9B59B6",
    accentColor: "#8E44AD",
    type: "Lentivirus (Retrovirus)",
    shape: "Spherical with glycoprotein envelope",
    size: "120 nm",
    genome: "Two copies of positive-sense single-stranded RNA",
    discoveredYear: "1983",
    discoveredBy: "Luc Montagnier & Françoise Barré-Sinoussi (France)",
    transmission: "Blood, sexual contact, mother-to-child (pregnancy/birth/breastfeeding), contaminated needles",
    symptoms: ["Flu-like illness (acute)", "Swollen lymph nodes", "Weight loss", "Chronic diarrhea", "Opportunistic infections", "Night sweats"],
    treatment: "Antiretroviral therapy (ART) — combination of NRTIs, NNRTIs, protease inhibitors, integrase inhibitors. Not curable but manageable",
    prevention: "PrEP (pre-exposure prophylaxis), condoms, needle exchange programs, antiretroviral treatment as prevention",
    mortality: "Nearly 100% without treatment; near-normal lifespan with ART",
    description: "HIV attacks the immune system, specifically CD4+ T cells. Over time, it destroys so many of these cells that the body can't fight infections, leading to AIDS (Acquired Immunodeficiency Syndrome). HIV uses reverse transcriptase to convert its RNA into DNA.",
    funFact: "HIV mutates so rapidly that within a single infected person, the virus evolves faster than the entire influenza virus does globally in a year!",
    parts: [
      { name: "Glycoprotein gp120", description: "Surface protein that binds to CD4 receptors on T cells — the first step of infection", color: "#E74C3C" },
      { name: "Glycoprotein gp41", description: "Transmembrane protein that fuses the viral and cell membranes", color: "#C0392B" },
      { name: "Lipid Envelope", description: "Outer lipid bilayer derived from the host cell membrane", color: "#F5B041" },
      { name: "Matrix (p17)", description: "Protein layer lining the inside of the envelope", color: "#9B59B6" },
      { name: "Capsid (p24)", description: "Cone-shaped core protecting the viral RNA genome", color: "#8E44AD" },
      { name: "Reverse Transcriptase", description: "Enzyme that converts viral RNA to DNA — target of many antiretroviral drugs", color: "#3498DB" },
      { name: "RNA Genome (2 copies)", description: "Two identical copies of single-stranded RNA totaling ~9,700 nucleotides", color: "#2ECC71" },
    ],
  },
  {
    id: "influenza",
    name: "Influenza",
    scientificName: "Influenza A virus (H1N1/H3N2)",
    emoji: "🤧",
    color: "#378ADD",
    accentColor: "#2980B9",
    type: "Orthomyxovirus",
    shape: "Spherical/filamentous with surface spikes",
    size: "80–120 nm",
    genome: "Eight segments of negative-sense single-stranded RNA",
    discoveredYear: "1933",
    discoveredBy: "Wilson Smith, Christopher Andrewes & Patrick Laidlaw (UK)",
    transmission: "Respiratory droplets, airborne transmission, contact with contaminated surfaces",
    symptoms: ["High fever", "Body aches", "Headache", "Severe fatigue", "Dry cough", "Sore throat", "Runny nose"],
    treatment: "Oseltamivir (Tamiflu), Zanamivir (Relenza), Baloxavir marboxil (Xofluza), supportive care",
    prevention: "Annual flu vaccine (inactivated or live attenuated), hand washing, avoiding sick contacts",
    mortality: "~0.1% seasonal; up to 2.5% pandemic strains",
    description: "The influenza virus causes seasonal flu epidemics. Its segmented genome allows 'antigenic shift' — when two different flu strains co-infect a cell and swap segments, creating entirely new strains (like H1N1 in 2009). This is why we need new flu vaccines every year.",
    funFact: "The 1918 Spanish Flu pandemic killed more people (50-100 million) than World War I — making it the deadliest pandemic in recorded history!",
    parts: [
      { name: "Hemagglutinin (HA)", description: "Surface spike protein binding to sialic acid on host cells — the 'H' in H1N1", color: "#3498DB" },
      { name: "Neuraminidase (NA)", description: "Surface enzyme that releases new viruses from host cells — the 'N' in H1N1", color: "#E74C3C" },
      { name: "Lipid Envelope", description: "Host-derived lipid bilayer studded with HA and NA proteins", color: "#F5B041" },
      { name: "M1 Matrix Protein", description: "Inner protein layer providing structural support", color: "#378ADD" },
      { name: "M2 Ion Channel", description: "Proton channel essential for viral uncoating inside the cell", color: "#1ABC9C" },
      { name: "RNA Segments (8)", description: "Eight separate RNA segments encoding 11+ proteins — enables genetic reassortment", color: "#9B59B6" },
    ],
  },
  {
    id: "ebola",
    name: "Ebola",
    scientificName: "Zaire ebolavirus",
    emoji: "☣️",
    color: "#EF9F27",
    accentColor: "#E67E22",
    type: "Filovirus",
    shape: "Filamentous (long thread-like)",
    size: "80 nm diameter × 800–14,000 nm length",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1976",
    discoveredBy: "Peter Piot & team (Belgium/Zaire)",
    transmission: "Direct contact with blood/body fluids of infected person, contaminated objects, infected animals (fruit bats)",
    symptoms: ["Sudden high fever", "Severe headache", "Muscle pain", "Vomiting", "Diarrhea", "Internal/external bleeding", "Organ failure"],
    treatment: "Inmazeb (atoltivimab/maftivimab/odesivimab), Ebanga (ansuvimab), supportive care with IV fluids and electrolytes",
    prevention: "rVSV-ZEBOV vaccine (Ervebo), contact tracing, isolation, protective equipment, safe burial practices",
    mortality: "25–90% (average ~50%, up to 90% for Zaire strain)",
    description: "One of the most deadly viruses known. Ebola causes severe hemorrhagic fever with massive internal bleeding. Its filamentous shape is unique — it can be extremely long, sometimes forming shepherd's crook or circular shapes. The virus is believed to be maintained in fruit bat populations.",
    funFact: "Ebola is named after the Ebola River in the Democratic Republic of Congo, near the village where the first recognized outbreak occurred in 1976!",
    parts: [
      { name: "Glycoprotein (GP)", description: "Surface protein forming trimeric spikes — the sole target for antibody-based treatments", color: "#E67E22" },
      { name: "Lipid Envelope", description: "Host-derived membrane covering the filamentous nucleocapsid", color: "#F5B041" },
      { name: "VP40 Matrix Protein", description: "Most abundant protein — drives the filamentous budding shape", color: "#EF9F27" },
      { name: "Nucleoprotein (NP)", description: "Coats and protects the RNA genome in a helical nucleocapsid", color: "#D4AC0D" },
      { name: "VP35", description: "Polymerase cofactor that also suppresses the host immune response", color: "#9B59B6" },
      { name: "RNA Genome", description: "~19,000 nucleotides encoding just 7 structural proteins", color: "#E74C3C" },
    ],
  },
  {
    id: "rabies",
    name: "Rabies",
    scientificName: "Rabies lyssavirus",
    emoji: "🐕",
    color: "#E74C3C",
    accentColor: "#C0392B",
    type: "Rhabdovirus (Lyssavirus)",
    shape: "Bullet-shaped",
    size: "75 nm × 180 nm",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1903 (virus isolated)",
    discoveredBy: "Adelchi Negri (Italy); vaccine by Louis Pasteur (1885)",
    transmission: "Bite or scratch from infected animal (dogs, bats, raccoons), saliva contact with open wounds",
    symptoms: ["Fever", "Headache", "Anxiety", "Hydrophobia (fear of water)", "Aerophobia", "Hallucinations", "Paralysis", "Cerebral dysfunction"],
    treatment: "Post-exposure prophylaxis (PEP) — rabies immunoglobulin + vaccine series. NO cure once symptoms appear",
    prevention: "Pre-exposure vaccination (for high-risk), pet vaccination, avoiding wild animals, immediate wound washing",
    mortality: "~99.9% once symptoms appear (nearly always fatal without PEP)",
    description: "Rabies is almost universally fatal once clinical symptoms develop, making it one of the most lethal viruses. It travels along nerves from the bite site to the brain, causing encephalitis. Its distinctive bullet shape makes it easily recognizable under electron microscopy.",
    funFact: "Louis Pasteur developed the first rabies vaccine in 1885 — he tested it on a 9-year-old boy bitten by a rabid dog, saving his life and pioneering modern vaccination!",
    parts: [
      { name: "Glycoprotein (G)", description: "Surface spikes that bind to nerve cell receptors — the target of neutralizing antibodies", color: "#E74C3C" },
      { name: "Lipid Envelope", description: "Outer membrane with embedded G protein spikes", color: "#F5B041" },
      { name: "Matrix Protein (M)", description: "Connects the envelope to the inner nucleocapsid and gives bullet shape", color: "#C0392B" },
      { name: "Nucleoprotein (N)", description: "Encapsidates the RNA genome in a helical ribonucleoprotein complex", color: "#9B59B6" },
      { name: "Phosphoprotein (P)", description: "Essential cofactor for the viral RNA polymerase", color: "#3498DB" },
      { name: "RNA Genome", description: "~12,000 nucleotides encoding only 5 proteins — extremely compact", color: "#2ECC71" },
    ],
  },
  {
    id: "bacteriophage",
    name: "T4 Bacteriophage",
    scientificName: "Enterobacteria phage T4",
    emoji: "🔬",
    color: "#39FF14",
    accentColor: "#2ECC71",
    type: "Myovirus (Bacteriophage)",
    shape: "Icosahedral head + contractile tail + baseplate + tail fibers",
    size: "Head: 86 nm, Tail: 120 nm",
    genome: "Linear double-stranded DNA",
    discoveredYear: "1915 (phages in general)",
    discoveredBy: "Frederick Twort (UK) & Félix d'Hérelle (France)",
    transmission: "Infects E. coli bacteria only — harmless to humans",
    symptoms: ["Does not infect humans", "Kills bacteria by lytic cycle", "Bursts host cell releasing ~100-200 new phages"],
    treatment: "Used AS treatment — Phage therapy is an alternative to antibiotics for drug-resistant bacterial infections",
    prevention: "N/A — beneficial virus used in medicine and research",
    mortality: "N/A for humans. 100% lethal to target bacteria",
    description: "Bacteriophages are viruses that exclusively infect bacteria. T4 is the most studied phage, with its iconic lunar-lander shape. It injects its DNA into E. coli, hijacks the cell machinery, and produces ~100-200 copies before bursting the cell. Phages are being explored as alternatives to antibiotics.",
    funFact: "There are an estimated 10³¹ bacteriophages on Earth — that's more than every other organism combined, including bacteria! They're the most abundant biological entity on the planet.",
    parts: [
      { name: "Icosahedral Head", description: "Elongated icosahedral capsid containing 169 kbp of DNA — one of the largest phage genomes", color: "#39FF14" },
      { name: "Tail Tube", description: "Contractile sheath that acts like a molecular syringe to inject DNA into bacteria", color: "#2ECC71" },
      { name: "Baseplate", description: "Complex hexagonal structure at the tail tip that recognizes and attaches to E. coli", color: "#1ABC9C" },
      { name: "Tail Fibers (6)", description: "Long leg-like structures that recognize specific receptors on the bacterial surface", color: "#F7DC6F" },
      { name: "Tail Pins", description: "Short fibers on the baseplate that provide secondary attachment", color: "#27AE60" },
      { name: "DNA Genome", description: "169,903 base pairs encoding ~289 proteins — packed tightly in the head", color: "#9B59B6" },
    ],
  },
  {
    id: "dengue",
    name: "Dengue",
    scientificName: "Dengue virus (DENV 1-4)",
    emoji: "🦟",
    color: "#F39C12",
    accentColor: "#E67E22",
    type: "Flavivirus",
    shape: "Smooth spherical with no projecting spikes",
    size: "40–60 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1943",
    discoveredBy: "Ren Kimura & Susumu Hotta (Japan)",
    transmission: "Aedes aegypti and Aedes albopictus mosquito bites",
    symptoms: ["High fever (40°C/104°F)", "Severe headache", "Pain behind eyes", "Muscle/joint pain", "Nausea", "Skin rash", "Mild bleeding (nose/gums)"],
    treatment: "No specific antiviral — supportive care with fluids, pain relievers (acetaminophen), avoid aspirin/NSAIDs. Severe cases need ICU",
    prevention: "Dengvaxia vaccine (limited use), mosquito control (eliminating standing water, insecticides), protective clothing, repellents",
    mortality: "~1% treated; up to 20% untreated severe dengue",
    description: "Dengue is the most common mosquito-borne viral disease, infecting ~390 million people annually. It has 4 serotypes (DENV 1-4). Recovery from one serotype gives lifelong immunity to that type but subsequent infection by a different serotype increases risk of severe dengue (hemorrhagic fever).",
    funFact: "Dengue is called 'breakbone fever' because the muscle and joint pain can be so severe that patients feel like their bones are breaking!",
    parts: [
      { name: "E Protein (Envelope)", description: "Surface protein mediating host cell attachment and membrane fusion — lies flat creating smooth surface", color: "#F39C12" },
      { name: "M Protein (Membrane)", description: "Small protein beneath E protein, created by cleavage of prM during maturation", color: "#E67E22" },
      { name: "Lipid Envelope", description: "Smooth outer lipid bilayer — unusually smooth compared to other viruses", color: "#F5B041" },
      { name: "Capsid Protein (C)", description: "Dimeric protein forming the inner nucleocapsid", color: "#D4AC0D" },
      { name: "RNA Genome", description: "~10,700 nucleotides encoding a single polyprotein cleaved into 10 proteins", color: "#9B59B6" },
      { name: "NS Proteins", description: "Non-structural proteins (NS1-NS5) essential for replication — NS1 is a diagnostic marker", color: "#E74C3C" },
    ],
  },
  {
    id: "hepatitis-b",
    name: "Hepatitis B",
    scientificName: "Hepatitis B virus (HBV)",
    emoji: "🟡",
    color: "#1D9E75",
    accentColor: "#16A085",
    type: "Hepadnavirus",
    shape: "Icosahedral with surface antigens",
    size: "42 nm (Dane particle)",
    genome: "Partially double-stranded circular DNA (relaxed circular DNA)",
    discoveredYear: "1965 (antigen), 1970 (virus)",
    discoveredBy: "Baruch Blumberg (USA) — Nobel Prize 1976",
    transmission: "Blood, sexual contact, mother-to-child (perinatal), contaminated needles, tattooing",
    symptoms: ["Jaundice (yellow skin/eyes)", "Dark urine", "Fatigue", "Abdominal pain", "Nausea", "Loss of appetite"],
    treatment: "Tenofovir, Entecavir (nucleos(t)ide analogues), Pegylated interferon-alpha. Chronic infection not fully curable but manageable",
    prevention: "HBV vaccine (3-dose series, >95% effective — first anti-cancer vaccine), screening blood supply, safe injection practices",
    mortality: "~1% acute; 15-25% chronic (liver cirrhosis/cancer)",
    description: "HBV infects liver cells and can cause both acute and chronic hepatitis. Chronic infection can lead to cirrhosis and liver cancer. It has a unique replication strategy using reverse transcriptase despite being a DNA virus. The HBV vaccine was the world's first vaccine to prevent cancer.",
    funFact: "The Hepatitis B vaccine was the first vaccine to prevent a type of cancer — chronic HBV causes ~80% of all liver cancer cases worldwide!",
    parts: [
      { name: "HBsAg (Surface Antigen)", description: "Surface protein used for diagnosis — the first hepatitis B marker discovered", color: "#1D9E75" },
      { name: "Lipid Envelope", description: "Outer lipid membrane containing three forms of surface antigen (S, M, L)", color: "#F5B041" },
      { name: "HBcAg (Core Antigen)", description: "Icosahedral capsid made of 240 copies of core protein", color: "#16A085" },
      { name: "HBeAg", description: "Secreted form of core protein — marker of active viral replication", color: "#E74C3C" },
      { name: "Polymerase/RT", description: "Reverse transcriptase that converts RNA intermediate back to DNA — unique for a DNA virus", color: "#3498DB" },
      { name: "rcDNA Genome", description: "~3,200 base pairs of relaxed circular DNA — smallest genome of any known human DNA virus", color: "#9B59B6" },
    ],
  },
  {
    id: "measles",
    name: "Measles",
    scientificName: "Measles morbillivirus",
    emoji: "🔴",
    color: "#E74C3C",
    accentColor: "#C0392B",
    type: "Paramyxovirus (Morbillivirus)",
    shape: "Pleomorphic spherical with fusion proteins",
    size: "100–300 nm",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1757 (identified as distinct disease), 1954 (virus isolated)",
    discoveredBy: "John Enders & Thomas Peebles (USA)",
    transmission: "Airborne (one of the most contagious diseases — R₀ of 12-18), respiratory droplets",
    symptoms: ["High fever", "Cough", "Runny nose", "Red watery eyes", "Koplik spots (white spots in mouth)", "Characteristic red rash (face → body)"],
    treatment: "No specific antiviral — supportive care, Vitamin A supplementation (reduces complications by 50%), treat secondary infections",
    prevention: "MMR vaccine (measles, mumps, rubella — 97% effective with 2 doses), isolation of cases, ring vaccination",
    mortality: "~0.1-0.2% in developed countries; 3-6% in developing countries; up to 10% in malnourished",
    description: "Measles is one of the most contagious diseases known — a single infected person can infect 12-18 others. The virus attacks immune memory cells, causing 'immune amnesia' that erases immunity to previously encountered pathogens. This effect can last 2-3 years after infection.",
    funFact: "Measles causes 'immune amnesia' — it erases your immune system's memory of past infections, leaving you vulnerable to diseases you were previously immune to for up to 3 years!",
    parts: [
      { name: "Hemagglutinin (H)", description: "Surface receptor binding protein that attaches to CD46/SLAM receptors on host cells", color: "#E74C3C" },
      { name: "Fusion Protein (F)", description: "Trimeric protein that fuses viral and cell membranes for entry", color: "#C0392B" },
      { name: "Lipid Envelope", description: "Host-derived membrane studded with H and F glycoproteins", color: "#F5B041" },
      { name: "Matrix Protein (M)", description: "Lines the inner envelope surface — organizes virus assembly", color: "#E74C3C" },
      { name: "Nucleocapsid (N+P+L)", description: "Helical ribonucleoprotein complex with nucleoprotein, phosphoprotein, and polymerase", color: "#9B59B6" },
    ],
  },
  {
    id: "tmv",
    name: "Tobacco Mosaic Virus",
    scientificName: "Tobamovirus TMV",
    emoji: "🌿",
    color: "#27AE60",
    accentColor: "#229954",
    type: "Tobamovirus",
    shape: "Rigid rod / helical",
    size: "18 nm diameter × 300 nm length",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1892 (first virus ever discovered)",
    discoveredBy: "Dmitri Ivanovsky (Russia) & Martinus Beijerinck (Netherlands)",
    transmission: "Mechanical contact (plant sap), contaminated tools, seeds, soil",
    symptoms: ["Mosaic pattern on leaves (light/dark green patches)", "Leaf curling", "Stunted growth", "Reduced crop yield", "Does not infect humans"],
    treatment: "No cure for infected plants — remove and destroy infected plants, sterilize tools",
    prevention: "Disease-resistant crop varieties, crop rotation, sanitation, seed treatment, avoiding tobacco products near crops",
    mortality: "N/A for humans. Causes 20-80% crop yield loss in tobacco, tomato, pepper plants",
    description: "TMV holds a legendary place in science — it was the FIRST virus ever discovered (1892). Ivanovsky showed that the agent causing tobacco mosaic disease was smaller than any known bacterium. Beijerinck called it 'contagium vivum fluidum' (living contagious fluid), coining the concept of viruses.",
    funFact: "TMV was the first virus ever discovered (1892), the first virus crystallized (1935 by Wendell Stanley, who won the Nobel Prize), and the first virus seen under an electron microscope (1939)!",
    parts: [
      { name: "Coat Protein (CP)", description: "2,130 identical protein subunits arranged in a helix — self-assembles like a spiral staircase", color: "#27AE60" },
      { name: "Helical Capsid", description: "Rigid rod structure with 16.33 proteins per turn in a right-handed helix", color: "#229954" },
      { name: "RNA Genome", description: "6,395 nucleotides embedded in a groove between protein subunits — encodes 4 proteins", color: "#9B59B6" },
      { name: "Central Channel", description: "4 nm hollow channel running through the center of the rod", color: "#1ABC9C" },
      { name: "5' Cap", description: "Modified nucleotide cap at the RNA 5' end for translation initiation", color: "#E74C3C" },
      { name: "Assembly Origin", description: "Specific RNA sequence where coat proteins begin self-assembly", color: "#F39C12" },
    ],
  },
  {
    id: "adenovirus",
    name: "Adenovirus",
    scientificName: "Human Adenovirus C",
    emoji: "🤧",
    color: "#5DADE2",
    accentColor: "#2E86C1",
    type: "Adenoviridae",
    shape: "Icosahedral with fiber spikes",
    size: "90–100 nm",
    genome: "Double-stranded DNA",
    discoveredYear: "1953",
    discoveredBy: "Wallace P. Rowe and colleagues",
    transmission: "Respiratory droplets, fecal-oral route, contaminated surfaces",
    symptoms: ["Sore throat", "Pink eye (conjunctivitis)", "Pneumonia", "Diarrhea", "Bronchitis"],
    treatment: "No specific antiviral — supportive care, hydration, rest",
    prevention: "Hand washing, disinfection of surfaces, vaccine (for military only)",
    mortality: "Low in healthy individuals; can be high in immunocompromised",
    description: "Adenoviruses are common viruses that cause flu-like symptoms. They are famous in biotechnology as 'viral vectors' for delivering genes in vaccines (like the AstraZeneca COVID vaccine).",
    funFact: "Adenoviruses have long fibers sticking out from their corners that look like antennas, which they use to 'dock' onto host cells!",
    parts: [
      { name: "Icosahedral Capsid", description: "Geometric 20-sided shell protecting the DNA", color: "#3498DB" },
      { name: "Fiber Spikes", description: "Long antenna-like structures for cell attachment", color: "#1ABC9C" },
      { name: "Hexon Proteins", description: "Major structural protein making up the capsid facets", color: "#2E86C1" },
    ],
  },
  {
    id: "zika",
    name: "Zika Virus",
    scientificName: "Zika virus",
    emoji: "🦟",
    color: "#F4D03F",
    accentColor: "#D4AC0D",
    type: "Flaviviridae",
    shape: "Spherical icosahedral",
    size: "50 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1947",
    discoveredBy: "Scientists in the Zika Forest of Uganda",
    transmission: "Aedes mosquito bites, sexual contact, mother-to-child",
    symptoms: ["Mild fever", "Rash", "Joint pain", "Conjunctivitis", "Microcephaly (in newborns)"],
    treatment: "Supportive care (fluids, rest, pain relievers)",
    prevention: "Mosquito control, insect repellent, avoiding travel to outbreak areas",
    mortality: "Very low for adults; high risk of birth defects during pregnancy",
    description: "Zika gained global attention in 2015-2016. While mild for most, it can cause microcephaly and other severe brain defects in babies born to infected mothers.",
    funFact: "Zika was discovered in a monkey in the Zika Forest — 'Zika' actually means 'overgrown' in the Luganda language!",
    parts: [
      { name: "Envelope (E) Protein", description: "Outer layer for cell binding and entry", color: "#F1C40F" },
      { name: "Membrane (M) Protein", description: "Protects the virus during maturation", color: "#D4AC0D" },
      { name: "RNA Core", description: "Single strand of genetic instructions", color: "#E74C3C" },
    ],
  },
  {
    id: "smallpox",
    name: "Smallpox",
    scientificName: "Variola virus",
    emoji: "💀",
    color: "#BA4A00",
    accentColor: "#873600",
    type: "Poxviridae",
    shape: "Large brick-shaped",
    size: "250 – 300 nm",
    genome: "Double-stranded DNA",
    discoveredYear: "Ancient (known for millennia)",
    discoveredBy: "N/A (Edward Jenner created vaccine in 1796)",
    transmission: "Face-to-face contact, respiratory droplets, contaminated bedding",
    symptoms: ["High fever", "Severe back pain", "Fluid-filled blisters (pustules)", "Permanent scarring"],
    treatment: "Tecovirimat (antiviral); historically no treatment once infected",
    prevention: "Vaccination (eradicated in 1980)",
    mortality: "~30% (Variola major)",
    description: "The first and only human disease to be completely eradicated by vaccination. It killed hundreds of millions of people throughout history.",
    funFact: "Smallpox is the only human disease to ever be completely wiped out by human effort!",
    parts: [
      { name: "Lateral Bodies", description: "Unique oval structures inside the virus core", color: "#D35400" },
      { name: "Dumbbell Core", description: "Shape of the inner nucleocapsid containing DNA", color: "#A04000" },
      { name: "Outer Membrane", description: "Complex multi-layered protein and lipid shell", color: "#6E2C00" },
    ],
  },
  {
    id: "herpes",
    name: "Herpes Simplex",
    scientificName: "Herpes simplex virus (HSV-1/2)",
    emoji: "👄",
    color: "#E74C3C",
    accentColor: "#922B21",
    type: "Herpesviridae",
    shape: "Spherical with tegument layer",
    size: "150 – 200 nm",
    genome: "Double-stranded DNA",
    discoveredYear: "Ancient (vaccine in development)",
    discoveredBy: "N/A",
    transmission: "Skin-to-skin contact, saliva, sexual contact",
    symptoms: ["Blisters/cold sores", "Itching", "Flu-like symptoms during first outbreak", "Latency (stays in nerves)"],
    treatment: "Acyclovir, Valacyclovir (antivirals to manage outbreaks)",
    prevention: "Avoiding contact during outbreaks, protective barriers",
    mortality: "Very low; can be serious in newborns or immunocompromised",
    description: "A lifelong infection that hides in nerve cells and 'reactivates' occasionally. HSV-1 usually causes cold sores, while HSV-2 is typically genital.",
    funFact: "Once you have Herpes, the virus stays in your nerve cells forever, 'sleeping' until it decides to wake up!",
    parts: [
      { name: "Tegument", description: "A unique space between the capsid and envelope filled with viral proteins", color: "#C0392B" },
      { name: "Icosahedral Capsid", description: "Sturdy shell protecting the large DNA genome", color: "#E74C3C" },
      { name: "Lipid Envelope", description: "Studded with at least 11 different glycoproteins", color: "#F5B041" },
    ],
  },
  {
    id: "rotavirus",
    name: "Rotavirus",
    scientificName: "Rotavirus A",
    emoji: "🎡",
    color: "#5D6D7E",
    accentColor: "#2E4053",
    type: "Reoviridae",
    shape: "Wheel-like (Icosahedral)",
    size: "70 – 100 nm",
    genome: "Segmented double-stranded RNA",
    discoveredYear: "1973",
    discoveredBy: "Ruth Bishop and colleagues (Australia)",
    transmission: "Fecal-oral route, contaminated hands/water",
    symptoms: ["Severe watery diarrhea", "Vomiting", "Fever", "Dehydration"],
    treatment: "Rehydration therapy (ORS), supportive care",
    prevention: "Oral Rotavirus vaccine (Rotarix/RotaTeq), hand hygiene",
    mortality: "High in children in developing countries due to dehydration",
    description: "The leading cause of severe diarrhea in infants and young children worldwide. It looks like a wheel under a microscope.",
    funFact: "The name 'Rotavirus' comes from the Latin word 'rota', which means 'wheel'!",
    parts: [
      { name: "Triple-Layered Capsid", description: "Three separate protein shells protecting the RNA", color: "#85929E" },
      { name: "VP4 Spikes", description: "Proteins that stick out to attach to the intestine", color: "#34495E" },
      { name: "RNA Segments", description: "11 segments of double-stranded RNA", color: "#9B59B6" },
    ],
  },
  {
    id: "marburg",
    name: "Marburg Virus",
    scientificName: "Marburg marburgvirus",
    emoji: "☣️",
    color: "#17202A",
    accentColor: "#E74C3C",
    type: "Filoviridae",
    shape: "Filamentous",
    size: "80 nm diameter",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1967",
    discoveredBy: "Scientists in Marburg and Frankfurt, Germany",
    transmission: "Contact with fruit bats, direct contact with infected blood/fluids",
    symptoms: ["High fever", "Severe headache", "Vomiting blood", "Internal bleeding", "Shock"],
    treatment: "Supportive care (no approved antivirals, though some in trial)",
    prevention: "Avoiding fruit bats, strict isolation of cases, PPE",
    mortality: "24 – 88%",
    description: "A close relative of Ebola. It causes severe hemorrhagic fever and was first identified after lab workers were exposed to African green monkeys.",
    funFact: "Marburg was the first filovirus ever discovered, appearing nearly 10 years before Ebola!",
    parts: [
      { name: "Nucleoprotein (NP)", description: "Protects the viral RNA strand", color: "#C0392B" },
      { name: "Glycoprotein Spikes", description: "Used to infect human cells", color: "#E74C3C" },
      { name: "Filamentous Envelope", description: "Long, flexible thread-like membrane", color: "#2C3E50" },
    ],
  },
  {
    id: "norovirus",
    name: "Norovirus",
    scientificName: "Norwalk virus",
    emoji: "🤢",
    color: "#2ECC71",
    accentColor: "#1D8348",
    type: "Caliciviridae",
    shape: "Small round structured",
    size: "27 – 35 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1968",
    discoveredBy: "Scientists during an outbreak in Norwalk, Ohio",
    transmission: "Fecal-oral route, contaminated food (shellfish), surfaces",
    symptoms: ["Projectile vomiting", "Diarrhea", "Stomach cramps", "Low-grade fever"],
    treatment: "Hydration, electrolytes (no specific antiviral)",
    prevention: "Thorough hand washing, disinfecting with bleach, cooking shellfish well",
    mortality: "Very low, but can be dangerous for elderly/babies",
    description: "Often called the 'stomach flu' or 'winter vomiting bug'. It is incredibly contagious—just 18 particles can make you sick!",
    funFact: "Norovirus is so contagious that it's famous for causing massive outbreaks on cruise ships!",
    parts: [
      { name: "VP1 Capsid", description: "Protein shell made of 180 identical subunits", color: "#27AE60" },
      { name: "Cup-shaped Depressions", description: "Surface features that give the family its name (Calici = Cup)", color: "#1D8348" },
      { name: "RNA Genome", description: "Single small strand of genetic code", color: "#3498DB" },
    ],
  },
  {
    id: "hpv",
    name: "HPV",
    scientificName: "Human papillomavirus",
    emoji: "🐚",
    color: "#D2B4DE",
    accentColor: "#7D3C98",
    type: "Papillomaviridae",
    shape: "Icosahedral (non-enveloped)",
    size: "55 nm",
    genome: "Double-stranded circular DNA",
    discoveredYear: "1907 (warts), 1980s (cancer link)",
    discoveredBy: "Harald zur Hausen (Nobel Prize for cancer link)",
    transmission: "Skin-to-skin contact, sexual contact",
    symptoms: ["Warts (skin/genital)", "Often asymptomatic", "Can lead to cervical/throat cancer"],
    treatment: "Removal of warts, treatment of precancerous cells",
    prevention: "HPV Vaccine (Gardasil), Pap smears, screening",
    mortality: "Low directly; high mortality via associated cancers",
    description: "The most common sexually transmitted infection. Most types are harmless, but 'high-risk' types are the leading cause of cervical cancer.",
    funFact: "The HPV vaccine is so effective it is expected to virtually eliminate cervical cancer in countries with high vaccination rates!",
    parts: [
      { name: "L1 Major Capsid", description: "Main structural protein forming the geometric shell", color: "#8E44AD" },
      { name: "L2 Minor Capsid", description: "Helps the virus DNA get into the cell nucleus", color: "#7D3C98" },
      { name: "Circular DNA", description: "Ring-shaped genetic material", color: "#5DADE2" },
    ],
  },
  {
    id: "poliovirus",
    name: "Poliovirus",
    scientificName: "Enterovirus C",
    emoji: "🦵",
    color: "#AED6F1",
    accentColor: "#2E86C1",
    type: "Picornaviridae",
    shape: "Small icosahedral",
    size: "30 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1908",
    discoveredBy: "Karl Landsteiner and Erwin Popper",
    transmission: "Fecal-oral route, contaminated water",
    symptoms: ["Flu-like symptoms", "Muscle weakness", "Irreversible paralysis (1 in 200 cases)"],
    treatment: "Supportive care (Iron lungs historically), physical therapy",
    prevention: "IPV (Salk) and OPV (Sabin) vaccines",
    mortality: "5 – 10% in cases with paralysis",
    description: "A virus that can attack the nervous system and cause total paralysis in hours. It is very close to being eradicated globally.",
    funFact: "Before the vaccine, thousands of children had to live inside 'Iron Lungs'—giant machines that breathed for them!",
    parts: [
      { name: "Protein Shell", description: "Very small, tough shell that resists stomach acid", color: "#3498DB" },
      { name: "VP1, VP2, VP3", description: "Three main surface proteins making up the shell", color: "#2E86C1" },
      { name: "RNA strand", description: "Small but highly efficient genetic code", color: "#9B59B6" },
    ],
  },
  {
    id: "mimivirus",
    name: "Mimivirus",
    scientificName: "Acanthamoeba polyphaga mimivirus",
    emoji: "👹",
    color: "#5D4037",
    accentColor: "#3E2723",
    type: "Mimiviridae",
    shape: "Large icosahedral with fiber hairs",
    size: "400 – 750 nm",
    genome: "Large double-stranded DNA",
    discoveredYear: "1992 (identified as virus in 2003)",
    discoveredBy: "Scientists in Bradford, UK (mistaken for bacteria initially)",
    transmission: "Infects amoebae",
    symptoms: ["No known human disease", "Infects amoebas by pretending to be food"],
    treatment: "N/A",
    prevention: "N/A",
    mortality: "N/A",
    description: "A 'Giant Virus' that is larger than many bacteria. It was named because it 'mimics' a microbe.",
    funFact: "Mimivirus is so big it even has its own 'parasite'—a smaller virus called Sputnik that infects it!",
    parts: [
      { name: "Protein Fibrils", description: "Hair-like coating that helps it look like bacteria to amoebas", color: "#8D6E63" },
      { name: "Giant Capsid", description: "Massive 20-sided shell", color: "#4E342E" },
      { name: "Stargate", description: "A unique star-shaped seal that opens to release DNA", color: "#39FF14" },
    ],
  },
  {
    id: "lambda-phage",
    name: "Lambda Phage",
    scientificName: "Enterobacteria phage λ",
    emoji: "🧬",
    color: "#A9DFBF",
    accentColor: "#27AE60",
    type: "Siphoviridae",
    shape: "Icosahedral head + long non-contractile tail",
    size: "Head: 50 nm, Tail: 150 nm",
    genome: "Double-stranded DNA",
    discoveredYear: "1950",
    discoveredBy: "Esther Lederberg",
    transmission: "Infects E. coli bacteria",
    symptoms: ["Lysogenic cycle (can hide inside bacterial DNA)"],
    treatment: "Used in genetic engineering and research",
    prevention: "N/A",
    mortality: "N/A",
    description: "A temperate bacteriophage that can either kill its host or hide inside its genome for generations.",
    funFact: "Lambda phage is a 'genetic switch'—it can choose between killing the cell or becoming part of it!",
    parts: [
      { name: "Head", description: "Icosahedral container for DNA", color: "#52BE80" },
      { name: "Long Tail", description: "Flexible tube used to find E. coli", color: "#27AE60" },
      { name: "J Protein", description: "Tip of the tail that recognizes host receptors", color: "#1D8348" },
    ],
  },
  {
    id: "rubella",
    name: "Rubella",
    scientificName: "Rubella virus",
    emoji: "🌸",
    color: "#F1948A",
    accentColor: "#C0392B",
    type: "Matonaviridae",
    shape: "Spherical enveloped",
    size: "60 – 70 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1962",
    discoveredBy: "Paul Parkman and Thomas Weller",
    transmission: "Respiratory droplets",
    symptoms: ["Mild fever", "Pink rash", "Swollen lymph nodes", "Congenital Rubella Syndrome (in newborns)"],
    treatment: "Supportive care",
    prevention: "MMR Vaccine",
    mortality: "Low for children; high for fetuses (birth defects)",
    description: "Also known as 'German Measles'. It is mild for children but devastating for unborn babies.",
    funFact: "Rubella means 'little red' in Latin, referring to the characteristic pink rash!",
    parts: [
      { name: "E1 & E2 Spikes", description: "Proteins used to enter cells", color: "#E74C3C" },
      { name: "Lipid Envelope", description: "Host-derived fatty layer", color: "#FAD7A0" },
      { name: "Nucleocapsid", description: "RNA-protein core", color: "#C0392B" },
    ],
  },
  {
    id: "mumps",
    name: "Mumps",
    scientificName: "Mumps orthorubulavirus",
    emoji: "🐹",
    color: "#F5B041",
    accentColor: "#D68910",
    type: "Paramyxoviridae",
    shape: "Pleomorphic (variable)",
    size: "150 – 200 nm",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1934",
    discoveredBy: "Claude Johnson and Ernest Goodpasture",
    transmission: "Saliva, respiratory droplets, sharing utensils",
    symptoms: ["Swollen salivary (parotid) glands", "Fever", "Headache", "Pain while chewing"],
    treatment: "Supportive care",
    prevention: "MMR Vaccine",
    mortality: "Very low",
    description: "Best known for causing 'chipmunk cheeks' due to swollen glands. Can occasionally cause deafness or meningitis.",
    funFact: "Before the vaccine, Mumps was a leading cause of childhood deafness!",
    parts: [
      { name: "HN Protein", description: "Hemagglutinin-neuraminidase for attachment", color: "#D35400" },
      { name: "F Protein", description: "Helps the virus fuse with the cell", color: "#E67E22" },
      { name: "RNA Core", description: "Helical genetic material", color: "#9B59B6" },
    ],
  },
  {
    id: "hcv",
    name: "Hepatitis C",
    scientificName: "Hepatitis C virus (HCV)",
    emoji: "🩸",
    color: "#85C1E9",
    accentColor: "#2874A6",
    type: "Flaviviridae",
    shape: "Spherical enveloped",
    size: "55 – 65 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1989",
    discoveredBy: "Harvey J. Alter, Michael Houghton, and Charles M. Rice (Nobel Prize 2020)",
    transmission: "Blood-to-blood contact (needles, transfusions before 1992)",
    symptoms: ["Often asymptomatic for years", "Fatigue", "Jaundice", "Cirrhosis", "Liver cancer"],
    treatment: "DAAs (Direct-acting antivirals) — can now be cured in >95% of cases!",
    prevention: "Safe injection practices, screening blood supply (no vaccine)",
    mortality: "High if untreated (liver failure)",
    description: "A 'silent killer' that can damage the liver for decades without symptoms. Now one of the few chronic viruses that can be completely cured.",
    funFact: "The discovery of HCV was so important for global health that the scientists won the Nobel Prize in 2020!",
    parts: [
      { name: "E1 & E2 Spikes", description: "Heavily glycosylated proteins that hide from the immune system", color: "#2E86C1" },
      { name: "Lipid Envelope", description: "Often associated with host lipoproteins (fat)", color: "#FAD7A0" },
      { name: "Core Protein", description: "Builds the internal shell", color: "#1B4F72" },
    ],
  },
  {
    id: "lassa",
    name: "Lassa Virus",
    scientificName: "Lassa mammarenavirus",
    emoji: "🐁",
    color: "#566573",
    accentColor: "#2C3E50",
    type: "Arenaviridae",
    shape: "Pleomorphic with 'sandy' appearance",
    size: "70 – 150 nm",
    genome: "Segmented single-stranded RNA (Ambisense)",
    discoveredYear: "1969",
    discoveredBy: "Scientists in Lassa, Nigeria",
    transmission: "Contact with rat urine/feces (Mastomys rats), person-to-person",
    symptoms: ["Fever", "Facial swelling", "Deafness (in 25%)", "Internal bleeding"],
    treatment: "Ribavirin (antiviral), supportive care",
    prevention: "Rodent control, safe food storage",
    mortality: "1% overall; 15% for hospitalized cases",
    description: "A viral hemorrhagic fever endemic to West Africa. Its name 'Arena' means 'sand', referring to ribosomes inside the virus that look like grains of sand.",
    funFact: "Lassa virus looks like it has sand inside it under a microscope—those grains are actually ribosomes the virus stole from its host cell!",
    parts: [
      { name: "Surface Glycoproteins", description: "Spikes that look like club-shaped projections", color: "#D5DBDB" },
      { name: "Ribosomes (Sand)", description: "Stolen host ribosomes inside the virus particle", color: "#BDC3C7" },
      { name: "RNA Segments", description: "Two circular RNA segments (L and S)", color: "#9B59B6" },
    ],
  },
  {
    id: "varicella",
    name: "Chickenpox",
    scientificName: "Varicella-zoster virus (VZV)",
    emoji: "🌋",
    color: "#F1948A",
    accentColor: "#C0392B",
    type: "Herpesviridae",
    shape: "Spherical with tegument",
    size: "150 – 200 nm",
    genome: "Double-stranded DNA",
    discoveredYear: "1952 (virus isolated)",
    discoveredBy: "Thomas Weller",
    transmission: "Respiratory droplets, contact with blister fluid",
    symptoms: ["Itchy red rash", "Fever", "Tiredness", "Shingles (later in life)"],
    treatment: "Calamine lotion, Acyclovir for severe cases",
    prevention: "Varicella Vaccine",
    mortality: "Very low for children; higher for adults",
    description: "Causes Chickenpox in children. After recovery, it hides in the spine and can re-emerge decades later as Shingles.",
    funFact: "Chickenpox never truly leaves you—it just hides in your nerves for 50 years until it decides to become Shingles!",
    parts: [
      { name: "Tegument Layer", description: "Space filled with proteins that help the virus start infection", color: "#C0392B" },
      { name: "Lipid Envelope", description: "Stolen from the host cell's Golgi membrane", color: "#FAD7A0" },
      { name: "DNA Core", description: "Large linear genetic code", color: "#8E44AD" },
    ],
  },
  {
    id: "rhinovirus",
    name: "Rhinovirus",
    scientificName: "Human rhinovirus (A/B/C)",
    emoji: "💧",
    color: "#D6EAF8",
    accentColor: "#3498DB",
    type: "Picornaviridae",
    shape: "Small icosahedral",
    size: "30 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1956",
    discoveredBy: "Karl Price and colleagues",
    transmission: "Hand-to-eye/nose contact, droplets",
    symptoms: ["Runny nose", "Sneezing", "Sore throat", "Congestion"],
    treatment: "Supportive care (rest, fluids, zinc, vitamin C)",
    prevention: "Hand washing, avoiding face touching",
    mortality: "Near zero",
    description: "The primary cause of the 'Common Cold'. There are over 160 different types, which is why you never become fully immune to colds.",
    funFact: "There are so many types of Rhinovirus that you could have a different cold every year of your life and never catch the same one twice!",
    parts: [
      { name: "Capsid", description: "Smooth geometric shell made of 60 subunits", color: "#85C1E9" },
      { name: "Canyons", description: "Deep grooves on the surface where host receptors bind", color: "#2E86C1" },
      { name: "RNA Genome", description: "Small, fast-acting genetic strand", color: "#9B59B6" },
    ],
  },
  {
    id: "west-nile",
    name: "West Nile Virus",
    scientificName: "West Nile virus",
    emoji: "🦅",
    color: "#82E0AA",
    accentColor: "#229954",
    type: "Flaviviridae",
    shape: "Spherical enveloped",
    size: "50 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1937",
    discoveredBy: "Scientists in the West Nile district of Uganda",
    transmission: "Mosquitoes (birds are the natural host)",
    symptoms: ["80% asymptomatic", "Fever", "Headache", "Encephalitis (1%)"],
    treatment: "Supportive care",
    prevention: "Mosquito repellent, long sleeves, removing standing water",
    mortality: "10% for those with neuroinvasive disease",
    description: "A virus that cycles between birds and mosquitoes. Humans and horses are 'dead-end' hosts.",
    funFact: "West Nile virus was only found in Africa and Asia until 1999, when it suddenly appeared in New York City!",
    parts: [
      { name: "E Protein", description: "Head-to-tail dimers that form a smooth surface", color: "#27AE60" },
      { name: "Lipid Envelope", description: "Derived from the host's endoplasmic reticulum", color: "#FAD7A0" },
      { name: "C Protein", description: "Packages the RNA core", color: "#1D8348" },
    ],
  },
  {
    id: "mers",
    name: "MERS-CoV",
    scientificName: "Middle East Respiratory Syndrome Coronavirus",
    emoji: "🐪",
    color: "#F5CBA7",
    accentColor: "#BA4A00",
    type: "Coronaviridae",
    shape: "Spherical with club-shaped spikes",
    size: "125 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "2012",
    discoveredBy: "Ali Mohamed Zaki (Saudi Arabia)",
    transmission: "Contact with camels, respiratory droplets",
    symptoms: ["Severe cough", "Fever", "Shortness of breath", "Kidney failure"],
    treatment: "Supportive care",
    prevention: "Avoiding contact with sick camels, hand hygiene",
    mortality: "~35%",
    description: "A much more lethal cousin of SARS and COVID-19. It primarily spreads from dromedary camels to humans.",
    funFact: "MERS is often called 'Camel Flu' because camels are the main source of the virus for humans!",
    parts: [
      { name: "Spike Protein", description: "Binds to DPP4 receptors in the lungs", color: "#E67E22" },
      { name: "Nucleocapsid", description: "Helical structure containing the RNA", color: "#9B59B6" },
      { name: "Envelope", description: "Lipid bilayer stolen from the host cell", color: "#D35400" },
    ],
  },
  {
    id: "hanta",
    name: "Hanta Virus",
    scientificName: "Sin Nombre virus",
    emoji: "🖱️",
    color: "#ABB2B9",
    accentColor: "#2C3E50",
    type: "Hantaviridae",
    shape: "Spherical enveloped",
    size: "80 – 120 nm",
    genome: "Segmented single-stranded RNA",
    discoveredYear: "1978 (Hantaan), 1993 (Sin Nombre)",
    discoveredBy: "Ho-Wang Lee (South Korea)",
    transmission: "Inhaling dust contaminated with rodent urine/feces",
    symptoms: ["Fever", "Muscle aches", "Severe fluid buildup in lungs (HPS)"],
    treatment: "Supportive care, mechanical ventilation",
    prevention: "Rodent control, avoiding dusty rodent-infested areas",
    mortality: "38% (for Sin Nombre strain)",
    description: "Unlike most other viruses in its family, Hantaviruses are not spread by insects, but by rodents like the deer mouse.",
    funFact: "The most famous Hantavirus in the US is named 'Sin Nombre', which means 'Without a Name' in Spanish!",
    parts: [
      { name: "Gn & Gc Spikes", description: "Glycoprotein spikes arranged in a square pattern", color: "#566573" },
      { name: "3 RNA Segments", description: "Large, Medium, and Small segments", color: "#9B59B6" },
      { name: "Nucleocapsid Protein", description: "Coats each RNA segment individually", color: "#2C3E50" },
    ],
  },
  {
    id: "nipah",
    name: "Nipah Virus",
    scientificName: "Nipah henipavirus",
    emoji: "🦇",
    color: "#1D8348",
    accentColor: "#145A32",
    type: "Paramyxoviridae",
    shape: "Pleomorphic enveloped",
    size: "40 – 600 nm",
    genome: "Negative-sense single-stranded RNA",
    discoveredYear: "1998",
    discoveredBy: "Chua Kaw Bing (Malaysia)",
    transmission: "Fruit bats, infected pigs, contaminated food, human-to-human",
    symptoms: ["Encephalitis (brain swelling)", "Fever", "Seizures", "Coma"],
    treatment: "Supportive care, Ribavirin (experimental)",
    prevention: "Avoiding contact with bats/pigs, not drinking raw date palm sap",
    mortality: "40% – 75%",
    description: "A highly dangerous zoonotic virus that can cause severe respiratory illness and fatal encephalitis.",
    funFact: "The movie 'Contagion' (2011) was based on a fictional virus inspired by the Nipah virus!",
    parts: [
      { name: "G Protein", description: "Attachment protein that binds to ephrin-B2/B3", color: "#27AE60" },
      { name: "F Protein", description: "Fusion protein for entering host cells", color: "#16A085" },
      { name: "Ribonucleoprotein", description: "Helical core containing the RNA", color: "#F4D03F" },
    ],
  },
  {
    id: "rift-valley",
    name: "Rift Valley Fever",
    scientificName: "Rift Valley fever phlebovirus",
    emoji: "🦟",
    color: "#E67E22",
    accentColor: "#922B21",
    type: "Phenuiviridae",
    shape: "Spherical enveloped",
    size: "80 – 120 nm",
    genome: "Segmented single-stranded RNA",
    discoveredYear: "1931",
    discoveredBy: "Daubney and Hudson (Kenya)",
    transmission: "Mosquitoes, contact with infected livestock blood/milk",
    symptoms: ["Fever", "Liver abnormalities", "Eye disease (blindness)", "Hemorrhagic fever"],
    treatment: "Supportive care",
    prevention: "Mosquito control, livestock vaccination",
    mortality: "<1% for mild, up to 50% for hemorrhagic",
    description: "An arbovirus that primarily affects animals but can cause severe disease in humans, often linked to heavy rainfall.",
    funFact: "RVF can remain dormant in mosquito eggs for years, only to hatch when heavy rains flood the area!",
    parts: [
      { name: "Gn & Gc Spikes", description: "Forms a dense fringe on the envelope", color: "#D35400" },
      { name: "L, M, S Segments", description: "Three RNA segments for replication", color: "#F4D03F" },
      { name: "Lipid Envelope", description: "Acquired from the host cell", color: "#922B21" },
    ],
  },
  {
    id: "chikungunya",
    name: "Chikungunya",
    scientificName: "Chikungunya virus",
    emoji: "🦟",
    color: "#AED6F1",
    accentColor: "#2E86C1",
    type: "Togaviridae",
    shape: "Spherical enveloped",
    size: "60 – 70 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1952",
    discoveredBy: "Marion Robinson and W.H.R. Lumsden (Tanzania)",
    transmission: "Aedes aegypti and Aedes albopictus mosquitoes",
    symptoms: ["Severe joint pain", "Fever", "Rash", "Fatigue"],
    treatment: "Supportive care (rest, fluids, non-aspirin painkillers)",
    prevention: "Mosquito avoidance, using nets, repellent",
    mortality: "Rare (<0.1%)",
    description: "The name comes from the Kimakonde language, meaning 'to become contorted,' referring to the stooped posture of sufferers.",
    funFact: "While rarely fatal, the joint pain can last for months or even years!",
    parts: [
      { name: "E1 Glycoprotein", description: "Responsible for membrane fusion", color: "#3498DB" },
      { name: "E2 Glycoprotein", description: "Responsible for receptor binding", color: "#2E86C1" },
      { name: "Nucleocapsid", description: "Icosahedral shell containing the RNA", color: "#1B4F72" },
    ],
  },
  {
    id: "japanese-encephalitis",
    name: "Japanese Encephalitis",
    scientificName: "Japanese encephalitis virus",
    emoji: "🦟",
    color: "#D2B4DE",
    accentColor: "#8E44AD",
    type: "Flaviviridae",
    shape: "Spherical enveloped",
    size: "50 nm",
    genome: "Positive-sense single-stranded RNA",
    discoveredYear: "1871 (first described), 1935 (isolated)",
    discoveredBy: "Japanese researchers (First isolate: Nakayama strain)",
    transmission: "Culex mosquitoes (natural cycle in pigs and wading birds)",
    symptoms: ["High fever", "Headache", "Stiff neck", "Mental status changes", "Seizures"],
    treatment: "Supportive care",
    prevention: "Vaccination, mosquito avoidance",
    mortality: "20% – 30% of clinical cases",
    description: "The leading cause of vaccine-preventable encephalitis in Asia and the Western Pacific.",
    funFact: "Pigs act as 'amplifying hosts', meaning the virus multiplies to very high levels inside them!",
    parts: [
      { name: "Envelope Protein", description: "Dimerized protein forming a smooth surface", color: "#AF7AC5" },
      { name: "M Protein", description: "Small membrane protein for assembly", color: "#8E44AD" },
      { name: "RNA-C Complex", description: "Genetic core packaged by the capsid protein", color: "#4A235A" },
    ],
  },
];

export function getVirusById(id: string): VirusData | undefined {
  return VIRUSES.find(v => v.id === id);
}
