"use client";

import React from "react";
import {
  Compass,
  Home,
  LayoutDashboard,
  GraduationCap,
  Bot,
  Trophy,
  Microscope,
  HeartPulse,
  GitFork,
  Sun,
  Workflow,
  FlaskConical,
  Globe,
  RotateCw,
  Dna,
  Biohazard,
  Stethoscope,
  Footprints,
  Trees,
  BookOpen,
  ClipboardList,
  Library,
  Search,
  Star,
  Pin,
  Bell,
  Keyboard,
  Palette,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  User,
  Shield,
  FolderKanban,
  Zap,
  Cpu,
  Package,
  Network,
  Activity,
  Thermometer,
  AlertTriangle,
  Flame,
  Syringe,
  Droplets,
  Binary,
  CircleDot,
  ShieldCheck,
  Globe2,
  Waves,
  FileText,
  Copy,
  Link,
  Sparkles,
  Award,
  Layers,
  Sprout,
  FileQuestion,
  ChevronDown,
  ChevronUp,
  Minus,
  Plus,
  Minimize2,
  Maximize2,
  LucideProps
} from "lucide-react";

export type IconName = string;

interface BioIconProps extends Omit<LucideProps, "ref"> {
  name: IconName;
  className?: string;
  size?: number | string;
}

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Navigation / Core
  home: Home,
  "🏠": Home,
  dashboard: LayoutDashboard,
  "📊": LayoutDashboard,
  "learning-paths": GraduationCap,
  "🎓": GraduationCap,
  tutor: Bot,
  "🤖": Bot,
  gamification: Trophy,
  "🏆": Trophy,
  profile: Trophy,

  // 3D Modules
  "cell-explorer": Microscope,
  "🔬": Microscope,
  "human-body": HeartPulse,
  "🫀": HeartPulse,
  "tree-of-life": GitFork,
  "🌳": GitFork,
  photosynthesis: Sun,
  "☀️": Sun,
  "food-chain": Workflow,
  "🦅": Workflow,

  // Labs & Sims
  "virtual-microscope": Microscope,
  microscope: Microscope,
  "virtual-lab": FlaskConical,
  "🧪": FlaskConical,
  "ecosystem-simulator": Globe,
  "🌐": Globe,
  "process-simulations": RotateCw,
  "🌀": RotateCw,

  // Research
  microorganisms: Dna,
  "🦠": Dna,
  viruses: Biohazard,
  "☣️": Biohazard,
  "disease-explorer": Stethoscope,
  "🏥": Stethoscope,
  "rare-species": Footprints,
  "🦁": Footprints,
  "dna-genetics": Dna,
  "🧬": Dna,
  ecosystems: Trees,
  "🌿": Trees,
  dictionary: BookOpen,
  "📖": BookOpen,
  quiz: ClipboardList,
  "📝": ClipboardList,
  "research-hub": Library,
  "📚": Library,

  // Organelles / Sub-topics
  membrane: Shield,
  "🛡️": Shield,
  nucleus: FolderKanban,
  "📂": FolderKanban,
  mitochondria: Zap,
  "⚡": Zap,
  ribosome: Cpu,
  "⚙️": Cpu,
  golgi: Package,
  "📦": Package,
  er: Network,
  "🕸️": Network,

  // Pathogens / Microbes sub-topics
  "sars-cov-2": Dna,
  hiv: Activity,
  "🩸": Activity,
  influenza: Thermometer,
  "🤒": Thermometer,
  ebola: AlertTriangle,
  "💀": AlertTriangle,
  rabies: Flame,
  "🐕": Flame,
  bacteriophage: Syringe,
  "👾": Syringe,
  amoeba: Droplets,
  "💧": Droplets,
  ecoli: Binary,
  "🌭": Binary,
  chlorella: CircleDot,
  "🟢": CircleDot,
  tardigrade: ShieldCheck,
  "🐻": ShieldCheck,
  volvox: Globe2,
  "⚽": Globe2,
  paramecium: Waves,
  "👟": Waves,

  // Header & Utilities
  search: Search,
  "🔍": Search,
  star: Star,
  "★": Star,
  "☆": Star,
  pin: Pin,
  "📌": Pin,
  bell: Bell,
  "🔔": Bell,
  keyboard: Keyboard,
  "⌨️": Keyboard,
  palette: Palette,
  "🎨": Palette,
  menu: Menu,
  "☰": Menu,
  close: X,
  "✕": X,
  "chevron-left": ChevronLeft,
  "❮": ChevronLeft,
  "chevron-right": ChevronRight,
  "❯": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  minimize: Minimize2,
  maximize: Maximize2,
  minus: Minus,
  plus: Plus,
  user: User,
  link: Link,
  "🔗": Link,
  copy: Copy,
  "📎": Copy,
  notes: FileText,
  "🗒️": FileText,
  "🌱": Sprout,
  sprout: Sprout,
  sparkles: Sparkles,
  "✨": Sparkles,

  // Modes
  explore: Globe,
  learn: BookOpen,
  simulation: FlaskConical,
  teacher: GraduationCap
};

export const BioIcon: React.FC<BioIconProps> = ({ name, size = 18, className = "", ...props }) => {
  const IconComponent = ICON_MAP[name] || ICON_MAP[name.toLowerCase()] || Compass;

  return <IconComponent size={size} className={`bio-svg-icon ${className}`} {...props} />;
};
