export interface RareSpeciesData {
  id: string;
  name: string;
  scientificName: string;
  emoji: string;
  color: string;
  accentColor: string;
  category: string;
  conservationStatus: "CR" | "EN" | "VU" | "NT";
  population: string;
  size: string;
  habitat: string;
  range: string;
  threats: string[];
  description: string;
  funFact: string;
  bodyType: string;
  bodyParams: {
    primaryColor: string;
    secondaryColor: string;
    bodyScale: [number, number, number];
    limbCount: number;
    hasHorns: boolean;
    hasWings: boolean;
    hasTail: boolean;
    hasFins: boolean;
    hasShell: boolean;
    specialFeature: string;
  };
}

export const RARE_SPECIES: RareSpeciesData[] = [
  // ═══════════════════════════════════════════════════════════
  // MAMMALS (1-20)
  // ═══════════════════════════════════════════════════════════
  {
    id: "vaquita",
    name: "Vaquita",
    scientificName: "Phocoena sinus",
    emoji: "🐬",
    color: "#4FC3F7",
    accentColor: "#0288D1",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~10",
    size: "1.2–1.5 m",
    habitat: "Shallow coastal waters",
    range: "Gulf of California, Mexico",
    threats: ["Bycatch in gillnets", "Illegal totoaba fishing"],
    description: "The world's rarest marine mammal. This tiny porpoise has dark rings around its eyes and lips, giving it a distinctive appearance.",
    funFact: "The vaquita was only discovered by science in 1958 and is the smallest of all porpoises!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#4FC3F7", secondaryColor: "#B3E5FC", bodyScale: [1.2, 0.6, 0.5], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "dorsal-fin" },
  },
  {
    id: "amur-leopard",
    name: "Amur Leopard",
    scientificName: "Panthera pardus orientalis",
    emoji: "🐆",
    color: "#FFB74D",
    accentColor: "#E65100",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~100",
    size: "1.0–1.4 m body",
    habitat: "Temperate broadleaf forests",
    range: "Russian Far East, NE China",
    threats: ["Habitat loss", "Poaching", "Prey depletion", "Inbreeding"],
    description: "One of the rarest big cats on Earth. Adapted to cold climates with a thick, pale coat and widely-spaced rosettes.",
    funFact: "Amur leopards can leap more than 5.8 meters horizontally and 3 meters vertically!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#FFB74D", secondaryColor: "#E65100", bodyScale: [1.4, 0.7, 0.6], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "spots" },
  },
  {
    id: "sumatran-rhino",
    name: "Sumatran Rhinoceros",
    scientificName: "Dicerorhinus sumatrensis",
    emoji: "🦏",
    color: "#A1887F",
    accentColor: "#5D4037",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~80",
    size: "2.4–3.2 m",
    habitat: "Dense tropical rainforest",
    range: "Sumatra, Borneo",
    threats: ["Poaching for horn", "Habitat fragmentation", "Small population"],
    description: "The smallest and most ancient rhino species, covered in reddish-brown hair. The only Asian rhino with two horns.",
    funFact: "Sumatran rhinos are more closely related to the extinct woolly rhinoceros than to any living rhino species!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#A1887F", secondaryColor: "#5D4037", bodyScale: [1.8, 1.2, 1.0], limbCount: 4, hasHorns: true, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "horn" },
  },
  {
    id: "pangolin",
    name: "Sunda Pangolin",
    scientificName: "Manis javanica",
    emoji: "🦔",
    color: "#BCAAA4",
    accentColor: "#795548",
    category: "Mammal",
    conservationStatus: "CR",
    population: "Unknown (declining)",
    size: "40–65 cm body",
    habitat: "Tropical forests, gardens",
    range: "Southeast Asia",
    threats: ["Illegal wildlife trade", "Traditional medicine demand", "Habitat loss"],
    description: "The world's most trafficked mammal. Covered in protective keratin scales and can curl into a tight ball when threatened.",
    funFact: "Pangolins have no teeth — they use a tongue that can be longer than their body to catch ants and termites!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#BCAAA4", secondaryColor: "#795548", bodyScale: [1.0, 0.5, 0.4], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: true, specialFeature: "scales" },
  },
  {
    id: "saola",
    name: "Saola",
    scientificName: "Pseudoryx nghetinhensis",
    emoji: "🦌",
    color: "#8D6E63",
    accentColor: "#4E342E",
    category: "Mammal",
    conservationStatus: "CR",
    population: "Unknown (possibly <100)",
    size: "1.5 m body",
    habitat: "Wet evergreen forests",
    range: "Vietnam, Laos",
    threats: ["Snare hunting", "Habitat loss", "Fragmentation"],
    description: "Called the 'Asian unicorn,' this forest-dwelling bovine was only discovered in 1992. One of the rarest large mammals on Earth.",
    funFact: "The saola was the first large mammal discovered in over 50 years — and has rarely been seen alive in the wild since!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#4E342E", bodyScale: [1.5, 1.0, 0.6], limbCount: 4, hasHorns: true, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "long-horns" },
  },
  {
    id: "javan-rhino",
    name: "Javan Rhinoceros",
    scientificName: "Rhinoceros sondaicus",
    emoji: "🦏",
    color: "#90A4AE",
    accentColor: "#546E7A",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~76",
    size: "2.0–4.0 m",
    habitat: "Tropical lowland rainforest",
    range: "Ujung Kulon NP, Java, Indonesia",
    threats: ["Very small population", "Volcanic eruption risk", "Disease", "Poaching"],
    description: "One of the rarest large mammals on Earth, existing in a single population. Has a single horn and armor-like skin folds.",
    funFact: "Javan rhinos are so shy and elusive that they were only photographed in the wild for the first time by camera traps in the late 1990s!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#90A4AE", secondaryColor: "#546E7A", bodyScale: [2.0, 1.3, 1.1], limbCount: 4, hasHorns: true, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "armor-folds" },
  },
  {
    id: "snow-leopard",
    name: "Snow Leopard",
    scientificName: "Panthera uncia",
    emoji: "🐆",
    color: "#B0BEC5",
    accentColor: "#607D8B",
    category: "Mammal",
    conservationStatus: "VU",
    population: "4,000–6,500",
    size: "0.9–1.3 m body",
    habitat: "Alpine and subalpine zones",
    range: "Central Asia mountains",
    threats: ["Human-wildlife conflict", "Poaching", "Mining", "Climate change"],
    description: "The 'ghost of the mountains' — a powerful yet elusive big cat perfectly adapted to the cold, harsh mountain environments of Central Asia.",
    funFact: "Snow leopards can't roar! Instead, they make a unique 'chuffing' sound. Their long tail helps them balance on rocky terrain and acts as a blanket!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#B0BEC5", secondaryColor: "#607D8B", bodyScale: [1.3, 0.6, 0.5], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "long-tail" },
  },
  {
    id: "red-panda",
    name: "Red Panda",
    scientificName: "Ailurus fulgens",
    emoji: "🐾",
    color: "#E57373",
    accentColor: "#C62828",
    category: "Mammal",
    conservationStatus: "EN",
    population: "~10,000",
    size: "50–64 cm body",
    habitat: "Temperate forests with bamboo",
    range: "Eastern Himalayas, SW China",
    threats: ["Habitat loss", "Fragmentation", "Poaching", "Inbreeding"],
    description: "A small arboreal mammal with reddish-brown fur and a striped bushy tail. Despite its name, it is not closely related to the giant panda.",
    funFact: "The red panda was actually discovered 48 years before the giant panda, and the word 'panda' originally referred to this species!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#E57373", secondaryColor: "#C62828", bodyScale: [0.8, 0.4, 0.35], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "bushy-tail" },
  },
  {
    id: "okapi",
    name: "Okapi",
    scientificName: "Okapia johnstoni",
    emoji: "🦒",
    color: "#6D4C41",
    accentColor: "#3E2723",
    category: "Mammal",
    conservationStatus: "EN",
    population: "~35,000",
    size: "1.5 m at shoulder",
    habitat: "Dense tropical rainforest",
    range: "Democratic Republic of Congo",
    threats: ["Habitat loss", "Hunting", "Armed conflict"],
    description: "The only living relative of the giraffe, with zebra-striped legs and a long prehensile tongue. Endemic to the Congo rainforest.",
    funFact: "An okapi's tongue is so long (35 cm) that it can lick its own ears — it uses it to strip leaves from branches!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#6D4C41", secondaryColor: "#3E2723", bodyScale: [1.5, 1.2, 0.6], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "striped-legs" },
  },
  {
    id: "saiga-antelope",
    name: "Saiga Antelope",
    scientificName: "Saiga tatarica",
    emoji: "🐐",
    color: "#D7CCC8",
    accentColor: "#8D6E63",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~1,300,000 (recovered)",
    size: "0.6–0.8 m at shoulder",
    habitat: "Semi-arid grasslands, steppes",
    range: "Central Asia (Kazakhstan, Mongolia)",
    threats: ["Disease outbreaks", "Poaching", "Habitat loss", "Climate change"],
    description: "Recognizable by its extraordinary bulbous nose that filters dust and regulates blood temperature. A living Ice Age relic.",
    funFact: "The saiga's bizarre flexible nose can filter out dust kicked up by the herd and warm freezing air in winter before it reaches the lungs!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#D7CCC8", secondaryColor: "#8D6E63", bodyScale: [1.1, 0.8, 0.5], limbCount: 4, hasHorns: true, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "bulbous-nose" },
  },
  {
    id: "axolotl",
    name: "Axolotl",
    scientificName: "Ambystoma mexicanum",
    emoji: "🦎",
    color: "#F48FB1",
    accentColor: "#C2185B",
    category: "Amphibian",
    conservationStatus: "CR",
    population: "50–1,000 in wild",
    size: "15–45 cm",
    habitat: "Freshwater lakes and canals",
    range: "Lake Xochimilco, Mexico City",
    threats: ["Urbanization", "Water pollution", "Invasive species", "Drainage"],
    description: "A neotenic salamander that retains its larval features throughout life, including external gills. Famous for its regenerative abilities.",
    funFact: "Axolotls can regenerate entire limbs, their heart, spinal cord, and even parts of their brain — making them invaluable to medical research!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#F48FB1", secondaryColor: "#C2185B", bodyScale: [1.0, 0.3, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "external-gills" },
  },
  {
    id: "narwhal",
    name: "Narwhal",
    scientificName: "Monodon monoceros",
    emoji: "🦄",
    color: "#80CBC4",
    accentColor: "#00695C",
    category: "Mammal",
    conservationStatus: "NT",
    population: "~80,000",
    size: "3.9–5.5 m",
    habitat: "Arctic waters, pack ice",
    range: "Arctic Ocean (Canada, Greenland, Russia)",
    threats: ["Climate change", "Shipping", "Oil exploration", "Hunting"],
    description: "The 'unicorn of the sea' — a medium-sized toothed whale with a long spiral tusk that is actually an elongated canine tooth.",
    funFact: "The narwhal's tusk is actually a tooth with up to 10 million nerve endings — it can sense changes in water temperature, pressure, and salinity!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#80CBC4", secondaryColor: "#00695C", bodyScale: [2.0, 0.6, 0.5], limbCount: 2, hasHorns: true, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "tusk" },
  },
  {
    id: "black-footed-ferret",
    name: "Black-footed Ferret",
    scientificName: "Mustela nigripes",
    emoji: "🦡",
    color: "#FFE082",
    accentColor: "#F9A825",
    category: "Mammal",
    conservationStatus: "EN",
    population: "~370 in wild",
    size: "38–50 cm body",
    habitat: "Grassland prairies",
    range: "Western North America",
    threats: ["Plague", "Habitat loss", "Prey decline (prairie dogs)"],
    description: "North America's most endangered mammal. Once thought extinct, a small population was rediscovered in 1981 and has been bred in captivity.",
    funFact: "Every black-footed ferret alive today descends from just 7 individuals found in a single colony in Wyoming in 1981!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#FFE082", secondaryColor: "#F9A825", bodyScale: [0.7, 0.25, 0.2], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "mask" },
  },
  {
    id: "iberian-lynx",
    name: "Iberian Lynx",
    scientificName: "Lynx pardinus",
    emoji: "🐱",
    color: "#FFCC80",
    accentColor: "#EF6C00",
    category: "Mammal",
    conservationStatus: "EN",
    population: "~1,100",
    size: "85–110 cm body",
    habitat: "Mediterranean scrubland",
    range: "Spain, Portugal",
    threats: ["Habitat loss", "Road kills", "Prey decline (rabbits)", "Disease"],
    description: "The world's most endangered cat species. Distinguished by its tufted ears, spotted coat, and facial 'beard' of fur.",
    funFact: "The Iberian lynx nearly went extinct with just 94 individuals in 2002, but is now a major conservation success story with over 1,100 today!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#FFCC80", secondaryColor: "#EF6C00", bodyScale: [1.0, 0.6, 0.5], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "ear-tufts" },
  },
  {
    id: "pygmy-sloth",
    name: "Pygmy Three-toed Sloth",
    scientificName: "Bradypus pygmaeus",
    emoji: "🦥",
    color: "#A5D6A7",
    accentColor: "#388E3C",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~100",
    size: "48–53 cm",
    habitat: "Red mangrove forests",
    range: "Isla Escudo de Veraguas, Panama",
    threats: ["Tiny island range", "Habitat degradation", "Potential hunting"],
    description: "The smallest and most endangered sloth species, found only on a single tiny island off Panama's coast. About 40% smaller than mainland sloths.",
    funFact: "This sloth is found on only one island in the entire world — an island so small you could walk across it in under 30 minutes!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#A5D6A7", secondaryColor: "#388E3C", bodyScale: [0.6, 0.4, 0.35], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "claws" },
  },
  {
    id: "ethiopian-wolf",
    name: "Ethiopian Wolf",
    scientificName: "Canis simensis",
    emoji: "🐺",
    color: "#EF5350",
    accentColor: "#B71C1C",
    category: "Mammal",
    conservationStatus: "EN",
    population: "~500",
    size: "84–100 cm body",
    habitat: "Afroalpine grasslands and heathlands",
    range: "Ethiopian highlands (above 3,000 m)",
    threats: ["Rabies from domestic dogs", "Habitat loss", "Overgrazing", "Climate change"],
    description: "Africa's most endangered carnivore and the world's rarest canid. A slender, long-legged wolf adapted to high-altitude rodent hunting.",
    funFact: "Despite being called a wolf, genetic studies show Ethiopian wolves are more closely related to grey wolves than to any African canid!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#EF5350", secondaryColor: "#B71C1C", bodyScale: [1.2, 0.7, 0.4], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "long-legs" },
  },
  {
    id: "northern-hairy-nosed-wombat",
    name: "Northern Hairy-nosed Wombat",
    scientificName: "Lasiorhinus krefftii",
    emoji: "🐻",
    color: "#B39DDB",
    accentColor: "#4527A0",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~315",
    size: "~1 m body",
    habitat: "Semi-arid woodland",
    range: "Queensland, Australia",
    threats: ["Small population", "Drought", "Predation", "Competition with cattle"],
    description: "One of Australia's rarest mammals, larger than the common wombat with soft, silky fur and a broader, more 'squashed' nose.",
    funFact: "Northern hairy-nosed wombats produce cube-shaped poop! They stack the cubes to mark their territory and the shape stops them rolling away!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#B39DDB", secondaryColor: "#4527A0", bodyScale: [1.0, 0.6, 0.6], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "broad-nose" },
  },
  {
    id: "cross-river-gorilla",
    name: "Cross River Gorilla",
    scientificName: "Gorilla gorilla diehli",
    emoji: "🦍",
    color: "#78909C",
    accentColor: "#37474F",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~250–300",
    size: "1.4–1.8 m standing",
    habitat: "Tropical and subtropical forests",
    range: "Nigeria-Cameroon border",
    threats: ["Habitat loss", "Hunting", "Small fragmented population"],
    description: "The rarest great ape subspecies, separated from the nearest western lowland gorilla population by about 300 km.",
    funFact: "Cross River gorillas are so wary of humans that they throw sticks and clumps of grass at researchers to keep them away!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#78909C", secondaryColor: "#37474F", bodyScale: [1.6, 1.4, 1.0], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "muscular" },
  },
  {
    id: "yangtze-finless-porpoise",
    name: "Yangtze Finless Porpoise",
    scientificName: "Neophocaena asiaeorientalis",
    emoji: "🐬",
    color: "#90CAF9",
    accentColor: "#1565C0",
    category: "Mammal",
    conservationStatus: "CR",
    population: "~1,000",
    size: "1.2–1.9 m",
    habitat: "Freshwater rivers and lakes",
    range: "Yangtze River, China",
    threats: ["Ship traffic", "Pollution", "Overfishing", "Dam construction"],
    description: "The only freshwater porpoise in the world. Known for its 'smiling' expression and intelligence. Replaced the extinct Yangtze river dolphin.",
    funFact: "This porpoise has no dorsal fin — instead it has a small ridge on its back, and it appears to 'smile' due to the shape of its mouth!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#90CAF9", secondaryColor: "#1565C0", bodyScale: [1.4, 0.5, 0.4], limbCount: 2, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "no-dorsal" },
  },
  {
    id: "aye-aye",
    name: "Aye-Aye",
    scientificName: "Daubentonia madagascariensis",
    emoji: "🐒",
    color: "#A1887F",
    accentColor: "#4E342E",
    category: "Mammal",
    conservationStatus: "EN",
    population: "1,000–10,000",
    size: "36–44 cm body",
    habitat: "Rainforest, dry deciduous forest",
    range: "Madagascar",
    threats: ["Habitat destruction", "Hunting (superstition)", "Persecution"],
    description: "The world's largest nocturnal primate. Uses echolocation-like tapping and a skeletal middle finger to find and extract insect larvae from trees.",
    funFact: "The aye-aye taps on trees up to 8 times per second and listens for hollow spaces — like a woodpecker, but it's a primate!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#A1887F", secondaryColor: "#4E342E", bodyScale: [0.7, 0.35, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "big-ears" },
  },

  // ═══════════════════════════════════════════════════════════
  // BIRDS (21-35)
  // ═══════════════════════════════════════════════════════════
  {
    id: "kakapo",
    name: "Kākāpō",
    scientificName: "Strigops habroptilus",
    emoji: "🦜",
    color: "#AED581",
    accentColor: "#558B2F",
    category: "Bird",
    conservationStatus: "CR",
    population: "~250",
    size: "58–64 cm",
    habitat: "Podocarp and beech forests",
    range: "New Zealand (predator-free islands)",
    threats: ["Predation by introduced mammals", "Low reproductive rate", "Disease"],
    description: "The world's only flightless, nocturnal parrot. The heaviest parrot species, it smells like honey and can live over 90 years.",
    funFact: "Male kākāpō inflate like a balloon and 'boom' at night — their call can be heard 5 km away and they use special bowl-shaped arenas to amplify it!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#AED581", secondaryColor: "#558B2F", bodyScale: [0.8, 0.6, 0.5], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "round-body" },
  },
  {
    id: "philippine-eagle",
    name: "Philippine Eagle",
    scientificName: "Pithecophaga jefferyi",
    emoji: "🦅",
    color: "#8D6E63",
    accentColor: "#3E2723",
    category: "Bird",
    conservationStatus: "CR",
    population: "~800",
    size: "86–102 cm, 2 m wingspan",
    habitat: "Tropical lowland and montane forest",
    range: "Philippines",
    threats: ["Deforestation", "Hunting", "Mining"],
    description: "One of the world's largest and most powerful eagles, with a distinctive shaggy crest. The national bird of the Philippines.",
    funFact: "Philippine Eagles mate for life and only raise a single chick every two years — killing one carries a 12-year prison sentence in the Philippines!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#3E2723", bodyScale: [1.2, 0.8, 0.6], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "crest" },
  },
  {
    id: "spoon-billed-sandpiper",
    name: "Spoon-billed Sandpiper",
    scientificName: "Calidris pygmaea",
    emoji: "🐦",
    color: "#FFAB91",
    accentColor: "#BF360C",
    category: "Bird",
    conservationStatus: "CR",
    population: "240–456 pairs",
    size: "14–16 cm",
    habitat: "Coastal mudflats, tundra",
    range: "NE Russia (breeds), SE Asia (winters)",
    threats: ["Habitat loss on coast", "Hunting", "Climate change"],
    description: "A tiny wading bird with a unique spatula-shaped bill. One of the most threatened birds on Earth with a rapidly declining population.",
    funFact: "The spoon-shaped bill sweeps from side to side in water like a tiny metal detector, filtering out tiny crustaceans and insect larvae!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#FFAB91", secondaryColor: "#BF360C", bodyScale: [0.3, 0.2, 0.15], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "spoon-bill" },
  },
  {
    id: "california-condor",
    name: "California Condor",
    scientificName: "Gymnogyps californianus",
    emoji: "🦅",
    color: "#37474F",
    accentColor: "#E53935",
    category: "Bird",
    conservationStatus: "CR",
    population: "~500",
    size: "1.1–1.4 m, 2.9 m wingspan",
    habitat: "Rocky shrubland, coniferous forests",
    range: "California, Arizona, Utah, Baja California",
    threats: ["Lead poisoning", "Microtrash ingestion", "Power line collisions"],
    description: "North America's largest flying bird with a 3-meter wingspan. Nearly went extinct (22 birds in 1987) but has been brought back through captive breeding.",
    funFact: "Condors are so efficient at soaring they can glide for miles without flapping their wings — they have been tracked flying at speeds of 88 km/h!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#37474F", secondaryColor: "#E53935", bodyScale: [1.4, 0.9, 0.7], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "bald-head" },
  },
  {
    id: "shoebill",
    name: "Shoebill",
    scientificName: "Balaeniceps rex",
    emoji: "🐦",
    color: "#78909C",
    accentColor: "#455A64",
    category: "Bird",
    conservationStatus: "VU",
    population: "5,000–8,000",
    size: "1.0–1.4 m tall",
    habitat: "Freshwater swamps, marshes",
    range: "East-Central Africa",
    threats: ["Wetland drainage", "Disturbance", "Hunting", "Nest trade"],
    description: "A prehistoric-looking bird with a massive shoe-shaped bill. Stands motionless for hours while hunting, then strikes with lightning speed.",
    funFact: "The shoebill can decapitate a 6-foot lungfish with a single strike of its razor-edged bill — and it bows to humans who bow to it first!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#78909C", secondaryColor: "#455A64", bodyScale: [1.2, 0.9, 0.6], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "massive-bill" },
  },
  {
    id: "kiwi",
    name: "North Island Brown Kiwi",
    scientificName: "Apteryx mantelli",
    emoji: "🥝",
    color: "#795548",
    accentColor: "#4E342E",
    category: "Bird",
    conservationStatus: "VU",
    population: "~25,000",
    size: "40–54 cm",
    habitat: "Native forest, scrubland",
    range: "North Island, New Zealand",
    threats: ["Predation by dogs and stoats", "Habitat loss"],
    description: "A flightless, nocturnal bird with whisker-like feathers and nostrils at the tip of its long bill. New Zealand's national symbol.",
    funFact: "Kiwi eggs are enormous — up to 20% of the female's body weight. That's like a human giving birth to a 4-year-old child!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#795548", secondaryColor: "#4E342E", bodyScale: [0.5, 0.4, 0.35], limbCount: 2, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "long-beak" },
  },
  {
    id: "helmeted-hornbill",
    name: "Helmeted Hornbill",
    scientificName: "Rhinoplax vigil",
    emoji: "🐦",
    color: "#FF8A65",
    accentColor: "#D84315",
    category: "Bird",
    conservationStatus: "CR",
    population: "Unknown (declining)",
    size: "1.1–1.2 m",
    habitat: "Lowland and montane forest",
    range: "Borneo, Sumatra, Malay Peninsula",
    threats: ["Hunting for casque (hornbill ivory)", "Deforestation"],
    description: "The only hornbill with a solid casque (helmet). Its skull-like headgear is carved into luxury items, driving it toward extinction.",
    funFact: "Males head-butt each other in mid-air during territorial disputes — the sound of their solid casques colliding can be heard a mile away!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#FF8A65", secondaryColor: "#D84315", bodyScale: [1.1, 0.7, 0.5], limbCount: 2, hasHorns: true, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "casque" },
  },
  {
    id: "hooded-grebe",
    name: "Hooded Grebe",
    scientificName: "Podiceps gallardoi",
    emoji: "🐦",
    color: "#EF9A9A",
    accentColor: "#C62828",
    category: "Bird",
    conservationStatus: "CR",
    population: "~800",
    size: "32–34 cm",
    habitat: "Basaltic steppe lakes",
    range: "Patagonia, Argentina",
    threats: ["Invasive mink", "Climate change", "Kelp gull predation"],
    description: "A striking grebe with a vivid orange crest and elaborate courtship dance. Discovered only in 1974 in remote Patagonian lakes.",
    funFact: "Hooded grebes perform one of the most spectacular mating dances in the bird world — pairs rush across the water surface in perfect synchrony!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#EF9A9A", secondaryColor: "#C62828", bodyScale: [0.4, 0.3, 0.25], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "crest" },
  },
  {
    id: "harpy-eagle",
    name: "Harpy Eagle",
    scientificName: "Harpia harpyja",
    emoji: "🦅",
    color: "#546E7A",
    accentColor: "#263238",
    category: "Bird",
    conservationStatus: "VU",
    population: "Unknown (declining)",
    size: "0.9–1.1 m, 2 m wingspan",
    habitat: "Tropical lowland rainforest",
    range: "Central and South America",
    threats: ["Deforestation", "Hunting", "Habitat fragmentation"],
    description: "One of the most powerful eagles in the world. Its talons are as large as a grizzly bear's claws, used to snatch monkeys and sloths from trees.",
    funFact: "A harpy eagle's talons exert over 200 pounds of pressure per square inch — enough to crush the bones of a howler monkey!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#546E7A", secondaryColor: "#263238", bodyScale: [1.1, 0.8, 0.6], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "crest" },
  },
  {
    id: "great-indian-bustard",
    name: "Great Indian Bustard",
    scientificName: "Ardeotis nigriceps",
    emoji: "🐦",
    color: "#D7CCC8",
    accentColor: "#5D4037",
    category: "Bird",
    conservationStatus: "CR",
    population: "~150",
    size: "0.9–1.2 m tall",
    habitat: "Arid grassland, scrubland",
    range: "Rajasthan, Gujarat (India)",
    threats: ["Power line collisions", "Habitat loss", "Hunting"],
    description: "One of the heaviest flying birds, standing over a meter tall. A flagship grassland species critically close to extinction.",
    funFact: "These bustards have very poor forward vision and can't see power lines in time — collision with power lines is their #1 killer!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#D7CCC8", secondaryColor: "#5D4037", bodyScale: [1.2, 0.9, 0.6], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "gular-pouch" },
  },
  {
    id: "blue-throated-macaw",
    name: "Blue-throated Macaw",
    scientificName: "Ara glaucogularis",
    emoji: "🦜",
    color: "#42A5F5",
    accentColor: "#1565C0",
    category: "Bird",
    conservationStatus: "CR",
    population: "~450",
    size: "85 cm",
    habitat: "Savanna with palm islands",
    range: "Beni savanna, Bolivia",
    threats: ["Pet trade capture", "Habitat loss", "Nest competition"],
    description: "A stunning turquoise and gold macaw with a distinctive blue throat patch. One of the rarest macaws, found in only a small area of Bolivia.",
    funFact: "Unlike most parrots, blue-throated macaws nest exclusively in dead palm trees — they depend on a single palm species for survival!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#42A5F5", secondaryColor: "#1565C0", bodyScale: [0.9, 0.5, 0.4], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "long-tail-feathers" },
  },
  {
    id: "forest-owlet",
    name: "Forest Owlet",
    scientificName: "Athene blewitti",
    emoji: "🦉",
    color: "#8D6E63",
    accentColor: "#4E342E",
    category: "Bird",
    conservationStatus: "EN",
    population: "~250",
    size: "23 cm",
    habitat: "Dry deciduous teak forest",
    range: "Central India",
    threats: ["Deforestation", "Logging", "Habitat degradation"],
    description: "A small, stocky owl rediscovered in 1997 after being thought extinct for 113 years. One of India's rarest birds.",
    funFact: "The forest owlet was rediscovered purely by accident — ornithologist Pamela Rasmussen found it while verifying fraudulent specimens in a museum!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#4E342E", bodyScale: [0.3, 0.25, 0.2], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "round-face" },
  },
  {
    id: "christmas-island-frigatebird",
    name: "Christmas Island Frigatebird",
    scientificName: "Fregata andrewsi",
    emoji: "🐦",
    color: "#37474F",
    accentColor: "#D32F2F",
    category: "Bird",
    conservationStatus: "CR",
    population: "2,400–4,800",
    size: "89–100 cm, 2.15 m wingspan",
    habitat: "Tropical oceanic island forest",
    range: "Christmas Island (Indian Ocean)",
    threats: ["Habitat loss", "Invasive species", "Single-island range"],
    description: "A seabird with an enormous wingspan that breeds only on Christmas Island. Males inflate a bright red throat pouch to attract mates.",
    funFact: "Males inflate their red throat sac to the size of a basketball and vibrate it for hours to attract females flying overhead!",
    bodyType: "avian",
    bodyParams: { primaryColor: "#37474F", secondaryColor: "#D32F2F", bodyScale: [1.0, 0.7, 0.5], limbCount: 2, hasHorns: false, hasWings: true, hasTail: true, hasFins: false, hasShell: false, specialFeature: "throat-pouch" },
  },

  // ═══════════════════════════════════════════════════════════
  // REPTILES (36-48)
  // ═══════════════════════════════════════════════════════════
  {
    id: "gharial",
    name: "Gharial",
    scientificName: "Gavialis gangeticus",
    emoji: "🐊",
    color: "#66BB6A",
    accentColor: "#2E7D32",
    category: "Reptile",
    conservationStatus: "CR",
    population: "~650",
    size: "3.5–6.0 m",
    habitat: "Deep, fast-flowing rivers",
    range: "Northern India, Nepal",
    threats: ["River damming", "Sand mining", "Fishing net entanglement", "Habitat loss"],
    description: "A unique crocodilian with an extremely narrow, elongated snout. Males develop a bulbous growth (ghara) on the tip of their snout.",
    funFact: "The male's bulbous nose tip (ghara) acts as a vocal resonator — it amplifies buzzing and hissing sounds to attract females from far away!",
    bodyType: "serpentine",
    bodyParams: { primaryColor: "#66BB6A", secondaryColor: "#2E7D32", bodyScale: [2.5, 0.4, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "long-snout" },
  },
  {
    id: "komodo-dragon",
    name: "Komodo Dragon",
    scientificName: "Varanus komodoensis",
    emoji: "🦎",
    color: "#8D6E63",
    accentColor: "#4E342E",
    category: "Reptile",
    conservationStatus: "EN",
    population: "~3,000",
    size: "2.0–3.0 m",
    habitat: "Tropical savanna forest",
    range: "Komodo Island and surroundings, Indonesia",
    threats: ["Climate change", "Habitat loss", "Tourism disturbance"],
    description: "The world's largest living lizard. A fearsome apex predator with venomous saliva, powerful claws, and serrated teeth.",
    funFact: "Komodo dragons can detect carrion from 9.5 km away using their forked tongue, and females can reproduce without males (parthenogenesis)!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#4E342E", bodyScale: [2.0, 0.5, 0.4], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "forked-tongue" },
  },
  {
    id: "hawksbill-turtle",
    name: "Hawksbill Sea Turtle",
    scientificName: "Eretmochelys imbricata",
    emoji: "🐢",
    color: "#FFAB91",
    accentColor: "#BF360C",
    category: "Reptile",
    conservationStatus: "CR",
    population: "~8,000 nesting females",
    size: "0.6–0.9 m shell",
    habitat: "Coral reefs, rocky areas",
    range: "Tropical oceans worldwide",
    threats: ["Shell trade (tortoiseshell)", "Egg harvesting", "Reef degradation", "Bycatch"],
    description: "A critically endangered sea turtle with a beautiful patterned shell. Its narrow, pointed beak reaches into crevices to eat sponges on coral reefs.",
    funFact: "Hawksbill turtles eat toxic sponges that would kill most animals — they are one of the few creatures that can digest silica glass spicules!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#FFAB91", secondaryColor: "#BF360C", bodyScale: [0.9, 0.3, 0.7], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: true, specialFeature: "patterned-shell" },
  },
  {
    id: "tuatara",
    name: "Tuatara",
    scientificName: "Sphenodon punctatus",
    emoji: "🦎",
    color: "#66BB6A",
    accentColor: "#2E7D32",
    category: "Reptile",
    conservationStatus: "NT",
    population: "~100,000",
    size: "50–80 cm",
    habitat: "Coastal forest and scrub",
    range: "New Zealand (offshore islands)",
    threats: ["Introduced rats", "Climate change (sex determination)", "Disease"],
    description: "A living fossil — the sole survivor of an order that thrived 200 million years ago alongside the dinosaurs. Not a lizard, despite appearance.",
    funFact: "Tuataras have a third 'parietal eye' on top of their head that can detect light and shadows — it's visible in hatchlings before being covered by scales!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#66BB6A", secondaryColor: "#2E7D32", bodyScale: [0.8, 0.3, 0.25], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "spines" },
  },
  {
    id: "galapagos-iguana",
    name: "Galápagos Marine Iguana",
    scientificName: "Amblyrhynchus cristatus",
    emoji: "🦎",
    color: "#EF5350",
    accentColor: "#212121",
    category: "Reptile",
    conservationStatus: "VU",
    population: "~250,000",
    size: "0.6–1.3 m",
    habitat: "Rocky shorelines, mangroves",
    range: "Galápagos Islands, Ecuador",
    threats: ["El Niño events", "Introduced predators", "Oil spills", "Plastic pollution"],
    description: "The world's only seagoing lizard. Feeds on underwater algae and can dive to 9 meters. Sneezes out excess salt through special nasal glands.",
    funFact: "Marine iguanas sneeze out pure salt crystals through special glands in their nose — they often end up with a white 'wig' of salt on their heads!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#EF5350", secondaryColor: "#212121", bodyScale: [1.0, 0.4, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "dorsal-crest" },
  },
  {
    id: "chinese-alligator",
    name: "Chinese Alligator",
    scientificName: "Alligator sinensis",
    emoji: "🐊",
    color: "#827717",
    accentColor: "#33691E",
    category: "Reptile",
    conservationStatus: "CR",
    population: "~150 in wild",
    size: "1.5–2.1 m",
    habitat: "Slow-moving freshwater rivers, ponds",
    range: "Yangtze River valley, China",
    threats: ["Habitat loss from farming", "Pollution", "Conflict with humans"],
    description: "One of only two alligator species in the world and the most endangered crocodilian. Much smaller than its American cousin.",
    funFact: "Chinese alligators are thought to be the inspiration for the Chinese dragon — ancient texts describe 'muddy dragons' in the Yangtze valley!",
    bodyType: "serpentine",
    bodyParams: { primaryColor: "#827717", secondaryColor: "#33691E", bodyScale: [1.5, 0.3, 0.25], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "armored-back" },
  },
  {
    id: "radiated-tortoise",
    name: "Radiated Tortoise",
    scientificName: "Astrochelys radiata",
    emoji: "🐢",
    color: "#FFF176",
    accentColor: "#F57F17",
    category: "Reptile",
    conservationStatus: "CR",
    population: "~6 million (rapidly declining)",
    size: "30–40 cm shell",
    habitat: "Dry spiny forest",
    range: "Southern Madagascar",
    threats: ["Illegal pet trade", "Habitat loss", "Bushmeat hunting"],
    description: "One of the most beautiful tortoises with a high-domed shell featuring stunning yellow and black star patterns.",
    funFact: "Radiated tortoises can live over 188 years — one named Tu'i Malila, gifted by Captain Cook, lived from 1777 to 1965!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#FFF176", secondaryColor: "#F57F17", bodyScale: [0.5, 0.35, 0.4], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: true, specialFeature: "star-pattern" },
  },
  {
    id: "leatherback-turtle",
    name: "Leatherback Sea Turtle",
    scientificName: "Dermochelys coriacea",
    emoji: "🐢",
    color: "#37474F",
    accentColor: "#CFD8DC",
    category: "Reptile",
    conservationStatus: "VU",
    population: "~26,000–43,000 nesting females",
    size: "1.3–1.8 m",
    habitat: "Open ocean, pelagic zone",
    range: "All oceans (tropical to subarctic)",
    threats: ["Bycatch", "Plastic pollution", "Egg harvesting", "Climate change"],
    description: "The largest of all sea turtles and the fourth-heaviest living reptile. Unique among turtles for its leather-like shell without bony plates.",
    funFact: "Leatherbacks can dive to 1,280 meters — deeper than most whales — and their body temperature stays 18°C warmer than surrounding water!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#37474F", secondaryColor: "#CFD8DC", bodyScale: [1.8, 0.5, 1.0], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: true, specialFeature: "ridged-shell" },
  },
  {
    id: "earless-monitor-lizard",
    name: "Earless Monitor Lizard",
    scientificName: "Lanthanotus borneensis",
    emoji: "🦎",
    color: "#5D4037",
    accentColor: "#3E2723",
    category: "Reptile",
    conservationStatus: "EN",
    population: "Unknown (very rare)",
    size: "20–22 cm",
    habitat: "Lowland rainforest streams",
    range: "Borneo (Sarawak, Kalimantan)",
    threats: ["Illegal pet trade", "Habitat loss", "Mining"],
    description: "A bizarre, semi-aquatic lizard with no visible ear openings. The only species in its family and extremely poorly known.",
    funFact: "The earless monitor lizard was so poorly studied that it was thought to be nocturnal until 2012 — it's actually most active at dusk!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#5D4037", secondaryColor: "#3E2723", bodyScale: [0.4, 0.12, 0.1], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "beaded-scales" },
  },
  {
    id: "blue-iguana",
    name: "Grand Cayman Blue Iguana",
    scientificName: "Cyclura lewisi",
    emoji: "🦎",
    color: "#42A5F5",
    accentColor: "#1565C0",
    category: "Reptile",
    conservationStatus: "EN",
    population: "~1,000",
    size: "1.3–1.5 m total",
    habitat: "Dry shrubland, rocky coast",
    range: "Grand Cayman Island",
    threats: ["Habitat loss", "Invasive cats/dogs/rats", "Road kills"],
    description: "A striking blue-colored rock iguana endemic to Grand Cayman. Was down to just 10–15 individuals in 2002 before a breeding program.",
    funFact: "Blue iguanas turn an even more vivid electric blue during breeding season to attract mates — they can live to over 69 years!",
    bodyType: "quadruped",
    bodyParams: { primaryColor: "#42A5F5", secondaryColor: "#1565C0", bodyScale: [1.2, 0.4, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "dewlap" },
  },
  {
    id: "round-island-boa",
    name: "Round Island Boa",
    scientificName: "Casarea dussumieri",
    emoji: "🐍",
    color: "#A1887F",
    accentColor: "#6D4C41",
    category: "Reptile",
    conservationStatus: "EN",
    population: "~1,000",
    size: "1.0–1.5 m",
    habitat: "Palm savanna, hardwood forest",
    range: "Round Island, Mauritius",
    threats: ["Very small range", "Habitat degradation", "Inbreeding"],
    description: "One of the rarest snakes on Earth, found only on a tiny island. It can split its jaw bones apart more than any other snake to swallow prey.",
    funFact: "The Round Island boa can split its upper jaw in two directions simultaneously — a unique mechanism found in no other living snake!",
    bodyType: "serpentine",
    bodyParams: { primaryColor: "#A1887F", secondaryColor: "#6D4C41", bodyScale: [1.2, 0.15, 0.15], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "split-jaw" },
  },
  {
    id: "siamese-crocodile",
    name: "Siamese Crocodile",
    scientificName: "Crocodylus siamensis",
    emoji: "🐊",
    color: "#689F38",
    accentColor: "#33691E",
    category: "Reptile",
    conservationStatus: "CR",
    population: "~1,000 in wild",
    size: "2.1–3.0 m",
    habitat: "Freshwater marshes, rivers, lakes",
    range: "Southeast Asia (Cambodia, Laos, Vietnam)",
    threats: ["Hunting for skins", "Habitat loss", "Hybridization with saltwater crocs"],
    description: "One of the most endangered crocodilians. A relatively docile freshwater species with a distinctive bony ridge behind its eyes.",
    funFact: "Siamese crocs are one of the least aggressive crocodile species — there are virtually no records of unprovoked attacks on humans!",
    bodyType: "serpentine",
    bodyParams: { primaryColor: "#689F38", secondaryColor: "#33691E", bodyScale: [2.0, 0.35, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "bony-ridge" },
  },

  // ═══════════════════════════════════════════════════════════
  // AMPHIBIANS (49-58)
  // ═══════════════════════════════════════════════════════════
  {
    id: "golden-poison-frog",
    name: "Golden Poison Frog",
    scientificName: "Phyllobates terribilis",
    emoji: "🐸",
    color: "#FFD54F",
    accentColor: "#F9A825",
    category: "Amphibian",
    conservationStatus: "EN",
    population: "Unknown (declining)",
    size: "4.7–5.5 cm",
    habitat: "Tropical rainforest floor",
    range: "Pacific coast of Colombia",
    threats: ["Deforestation", "Gold mining", "Illegal collection"],
    description: "The most toxic animal on Earth. A single frog contains enough poison to kill 10 adult humans. Indigenous Chocó people use its toxin on blowdarts.",
    funFact: "One golden poison frog has enough toxin (batrachotoxin) to kill 20,000 mice or 10 adult humans — but in captivity, they lose their toxicity!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#FFD54F", secondaryColor: "#F9A825", bodyScale: [0.25, 0.15, 0.2], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "bright-warning" },
  },
  {
    id: "chinese-giant-salamander",
    name: "Chinese Giant Salamander",
    scientificName: "Andrias davidianus",
    emoji: "🦎",
    color: "#795548",
    accentColor: "#4E342E",
    category: "Amphibian",
    conservationStatus: "CR",
    population: "Unknown (severely declined)",
    size: "Up to 1.8 m",
    habitat: "Cool rocky mountain streams",
    range: "Central and southern China",
    threats: ["Overcollection for food", "Habitat degradation", "Pollution", "Disease"],
    description: "The world's largest amphibian. A flat-headed, wrinkly 'living fossil' that breathes partly through its skin and can live 60+ years.",
    funFact: "Chinese giant salamanders have been around for 170 million years — they coexisted with dinosaurs and have barely changed since!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#795548", secondaryColor: "#4E342E", bodyScale: [1.8, 0.4, 0.3], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "wrinkly-skin" },
  },
  {
    id: "glass-frog",
    name: "Fleischmann's Glass Frog",
    scientificName: "Hyalinobatrachium fleischmanni",
    emoji: "🐸",
    color: "#A5D6A7",
    accentColor: "#2E7D32",
    category: "Amphibian",
    conservationStatus: "NT",
    population: "Declining",
    size: "1.9–3.2 cm",
    habitat: "Humid mountain forest canopy",
    range: "Central and South America",
    threats: ["Habitat loss", "Climate change", "Chytrid fungus"],
    description: "A tiny translucent frog whose internal organs, including the heart, are visible through its transparent belly skin.",
    funFact: "Glass frogs can turn nearly invisible while sleeping by hiding 89% of their red blood cells in their liver, making their body almost transparent!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#A5D6A7", secondaryColor: "#2E7D32", bodyScale: [0.15, 0.1, 0.12], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "transparent" },
  },
  {
    id: "purple-frog",
    name: "Purple Frog",
    scientificName: "Nasikabatrachus sahyadrensis",
    emoji: "🐸",
    color: "#9C27B0",
    accentColor: "#6A1B9A",
    category: "Amphibian",
    conservationStatus: "EN",
    population: "Unknown",
    size: "6–9 cm",
    habitat: "Underground in Western Ghats",
    range: "Western Ghats, India",
    threats: ["Habitat loss", "Plantation agriculture", "Dam construction"],
    description: "A bizarre, bloated, purple-colored frog that lives underground for most of the year, surfacing only for 2 weeks to breed during monsoon.",
    funFact: "The purple frog diverged from its nearest relative 100 million years ago — it's a living fossil found entirely by accident in 2003!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#9C27B0", secondaryColor: "#6A1B9A", bodyScale: [0.35, 0.25, 0.25], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "bloated" },
  },
  {
    id: "olm",
    name: "Olm (Proteus)",
    scientificName: "Proteus anguinus",
    emoji: "🦎",
    color: "#FFCCBC",
    accentColor: "#FF8A65",
    category: "Amphibian",
    conservationStatus: "VU",
    population: "Unknown",
    size: "20–30 cm",
    habitat: "Underwater caves (complete darkness)",
    range: "Dinaric Alps caves (Slovenia, Croatia, Bosnia)",
    threats: ["Water pollution", "Habitat disturbance", "Climate change"],
    description: "A blind, pink cave salamander that lives its entire life in darkness. Has external gills, can survive 10 years without food, and may live 100+ years.",
    funFact: "Olms can live over 100 years, go a decade without food, and a single individual was observed sitting motionless in the same spot for 7 years straight!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#FFCCBC", secondaryColor: "#FF8A65", bodyScale: [0.6, 0.1, 0.08], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "external-gills" },
  },
  {
    id: "hellbender",
    name: "Hellbender",
    scientificName: "Cryptobranchus alleganiensis",
    emoji: "🦎",
    color: "#8D6E63",
    accentColor: "#5D4037",
    category: "Amphibian",
    conservationStatus: "NT",
    population: "Declining",
    size: "30–74 cm",
    habitat: "Clear, fast-flowing mountain streams",
    range: "Eastern United States",
    threats: ["Siltation", "Pollution", "Disease", "Collection"],
    description: "North America's largest salamander, nicknamed the 'snot otter' for its mucus-covered body. Breathes through folds of skin on its sides.",
    funFact: "Hellbenders are called 'snot otters' because their wrinkly, mucus-covered skin looks slimy — but they're harmless indicators of clean water!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#5D4037", bodyScale: [0.9, 0.2, 0.15], limbCount: 4, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: false, specialFeature: "wrinkly-skin" },
  },
  {
    id: "harlequin-toad",
    name: "Variable Harlequin Toad",
    scientificName: "Atelopus varius",
    emoji: "🐸",
    color: "#FF7043",
    accentColor: "#212121",
    category: "Amphibian",
    conservationStatus: "CR",
    population: "Unknown (possibly <100)",
    size: "2.5–4 cm",
    habitat: "Mountain stream margins",
    range: "Costa Rica, Panama",
    threats: ["Chytrid fungus", "Climate change", "Habitat loss"],
    description: "A spectacularly colorful toad once common in Central American streams. Devastated by chytrid fungus, it was feared extinct until rediscovery.",
    funFact: "Each harlequin toad has a unique color pattern — like human fingerprints, no two are alike. Some have even been 'identified' years apart by their patterns!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#FF7043", secondaryColor: "#212121", bodyScale: [0.2, 0.12, 0.15], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "bright-warning" },
  },
  {
    id: "darwin-frog",
    name: "Darwin's Frog",
    scientificName: "Rhinoderma darwinii",
    emoji: "🐸",
    color: "#66BB6A",
    accentColor: "#2E7D32",
    category: "Amphibian",
    conservationStatus: "EN",
    population: "Unknown (declining)",
    size: "2.2–3.1 cm",
    habitat: "Temperate beech forests",
    range: "Chile, Argentina",
    threats: ["Chytrid fungus", "Habitat loss", "Climate change", "Logging"],
    description: "A tiny leaf-shaped frog discovered by Charles Darwin. The male broods tadpoles inside his vocal sac until they emerge as fully formed froglets.",
    funFact: "Male Darwin's frogs swallow their own tadpoles and store them in their vocal sac — the babies develop inside his throat and hop out of his mouth as tiny frogs!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#66BB6A", secondaryColor: "#2E7D32", bodyScale: [0.15, 0.1, 0.1], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "leaf-shape" },
  },
  {
    id: "lemur-leaf-frog",
    name: "Lemur Leaf Frog",
    scientificName: "Agalychnis lemur",
    emoji: "🐸",
    color: "#69F0AE",
    accentColor: "#00C853",
    category: "Amphibian",
    conservationStatus: "CR",
    population: "Unknown (severely declined)",
    size: "3.0–4.5 cm",
    habitat: "Premontane rainforest canopy",
    range: "Costa Rica, Panama, Colombia",
    threats: ["Chytrid fungus", "Climate change", "Habitat loss"],
    description: "A gorgeous lime-green tree frog with huge silvery eyes that turn dark at night. Named for its lemur-like large eyes.",
    funFact: "Lemur leaf frogs change color — they're bright green during the day and turn brown at night, and their huge silvery eyes glow in flashlight beams!",
    bodyType: "amphibian",
    bodyParams: { primaryColor: "#69F0AE", secondaryColor: "#00C853", bodyScale: [0.2, 0.12, 0.14], limbCount: 4, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "big-eyes" },
  },

  // ═══════════════════════════════════════════════════════════
  // FISH (59-68)
  // ═══════════════════════════════════════════════════════════
  {
    id: "coelacanth",
    name: "Coelacanth",
    scientificName: "Latimeria chalumnae",
    emoji: "🐟",
    color: "#5C6BC0",
    accentColor: "#283593",
    category: "Fish",
    conservationStatus: "CR",
    population: "~500",
    size: "1.5–2.0 m",
    habitat: "Deep ocean caves (150–700 m)",
    range: "East Africa, Comoros Islands, Indonesia",
    threats: ["Bycatch", "Deep-sea fishing", "Very small population"],
    description: "A 'living fossil' thought to have gone extinct 66 million years ago — until a live specimen was caught in 1938. Has lobed fins that move like limbs.",
    funFact: "Coelacanths were thought extinct for 66 million years until one was pulled from the Indian Ocean in 1938 — they can live to 100 years!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#5C6BC0", secondaryColor: "#283593", bodyScale: [1.5, 0.5, 0.4], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "lobed-fins" },
  },
  {
    id: "whale-shark",
    name: "Whale Shark",
    scientificName: "Rhincodon typus",
    emoji: "🦈",
    color: "#42A5F5",
    accentColor: "#0D47A1",
    category: "Fish",
    conservationStatus: "EN",
    population: "Unknown (declining)",
    size: "5.5–20 m",
    habitat: "Open ocean, coastal",
    range: "Tropical and temperate oceans",
    threats: ["Bycatch", "Ship strikes", "Hunting", "Plastic pollution"],
    description: "The largest fish in the sea, yet a gentle filter-feeder that eats plankton. Covered in a unique pattern of pale spots and stripes.",
    funFact: "Each whale shark's spot pattern is unique like a fingerprint — researchers use photo ID software to identify individuals from their markings!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#42A5F5", secondaryColor: "#0D47A1", bodyScale: [3.0, 1.0, 0.8], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "spotted" },
  },
  {
    id: "sawfish",
    name: "Largetooth Sawfish",
    scientificName: "Pristis pristis",
    emoji: "🐟",
    color: "#90A4AE",
    accentColor: "#546E7A",
    category: "Fish",
    conservationStatus: "CR",
    population: "Unknown (severely declined)",
    size: "Up to 6.5 m",
    habitat: "Coastal, estuarine, freshwater",
    range: "Tropical Atlantic and Indo-Pacific (fragmented)",
    threats: ["Bycatch (saw entanglement)", "Habitat loss", "Overfishing"],
    description: "A ray with a chainsaw-like snout studded with teeth. Uses its saw to slash through schools of fish and to dig in sand for prey.",
    funFact: "The sawfish's rostrum has electroreceptors that detect prey's electric fields, plus it can swing it at 3 meters per second to stun fish!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#90A4AE", secondaryColor: "#546E7A", bodyScale: [2.5, 0.4, 0.6], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "saw-snout" },
  },
  {
    id: "napoleon-wrasse",
    name: "Humphead Wrasse",
    scientificName: "Cheilinus undulatus",
    emoji: "🐠",
    color: "#26A69A",
    accentColor: "#00695C",
    category: "Fish",
    conservationStatus: "EN",
    population: "Unknown (declining)",
    size: "Up to 2.3 m",
    habitat: "Coral reefs",
    range: "Indo-Pacific coral reefs",
    threats: ["Overfishing", "Live reef fish trade", "Cyanide fishing", "Reef degradation"],
    description: "The largest living member of the wrasse family, with a distinctive prominent forehead bump. Can live over 30 years.",
    funFact: "All humphead wrasses are born female — some later become males, and they are one of the few fish that can eat toxic crown-of-thorns starfish!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#26A69A", secondaryColor: "#00695C", bodyScale: [1.5, 0.7, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "forehead-bump" },
  },
  {
    id: "devils-hole-pupfish",
    name: "Devils Hole Pupfish",
    scientificName: "Cyprinodon diabolis",
    emoji: "🐟",
    color: "#64B5F6",
    accentColor: "#1976D2",
    category: "Fish",
    conservationStatus: "CR",
    population: "~175–263",
    size: "1.9–3.5 cm",
    habitat: "Single desert pool",
    range: "Devils Hole, Nevada, USA",
    threats: ["Groundwater extraction", "Flash floods", "Climate change"],
    description: "Possibly the rarest fish on Earth, living in a single limestone pool in the Nevada desert that's only 3.5 m × 22 m. Isolated for 10,000–20,000 years.",
    funFact: "The entire wild population lives on a single rock shelf measuring 3.5 by 6 meters — making it the smallest habitat of any known vertebrate!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#64B5F6", secondaryColor: "#1976D2", bodyScale: [0.15, 0.06, 0.04], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "tiny" },
  },
  {
    id: "totoaba",
    name: "Totoaba",
    scientificName: "Totoaba macdonaldi",
    emoji: "🐟",
    color: "#78909C",
    accentColor: "#37474F",
    category: "Fish",
    conservationStatus: "CR",
    population: "Unknown (severely declined)",
    size: "Up to 2 m",
    habitat: "Shallow coastal waters",
    range: "Gulf of California, Mexico",
    threats: ["Poaching for swim bladder", "Bycatch"],
    description: "A large fish whose swim bladder is worth more than gold on the black market. Its illegal fishing is also driving the vaquita to extinction.",
    funFact: "Totoaba swim bladders sell for up to $46,000 per kg on the black market — they're called 'aquatic cocaine' and are smuggled like drugs!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#78909C", secondaryColor: "#37474F", bodyScale: [1.5, 0.5, 0.3], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "large-body" },
  },
  {
    id: "mekong-giant-catfish",
    name: "Mekong Giant Catfish",
    scientificName: "Pangasianodon gigas",
    emoji: "🐟",
    color: "#B0BEC5",
    accentColor: "#607D8B",
    category: "Fish",
    conservationStatus: "CR",
    population: "Unknown (severely declined)",
    size: "Up to 3 m",
    habitat: "Deep river pools",
    range: "Mekong River basin",
    threats: ["Overfishing", "Dam construction", "Habitat degradation"],
    description: "One of the world's largest freshwater fish, reaching 300 kg. A gentle vegetarian giant that migrates huge distances up the Mekong River.",
    funFact: "This catfish holds the record for the world's largest freshwater fish ever caught — a 293 kg specimen pulled from Thailand's Mekong in 2005!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#B0BEC5", secondaryColor: "#607D8B", bodyScale: [2.0, 0.7, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "whiskers" },
  },
  {
    id: "red-handfish",
    name: "Red Handfish",
    scientificName: "Thymichthys politus",
    emoji: "🐟",
    color: "#E53935",
    accentColor: "#B71C1C",
    category: "Fish",
    conservationStatus: "CR",
    population: "~100",
    size: "6–13 cm",
    habitat: "Sandy and rocky reef",
    range: "SE Tasmania, Australia",
    threats: ["Very small range", "Sea urchin overgrazing", "Invasive starfish", "Siltation"],
    description: "A bizarre fish that 'walks' on the seafloor using hand-like pectoral fins. One of the rarest fish on the planet.",
    funFact: "Red handfish walk on the ocean floor using their fins like hands — they're so rare that the entire population lives in an area the size of two tennis courts!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#E53935", secondaryColor: "#B71C1C", bodyScale: [0.2, 0.1, 0.08], limbCount: 2, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "hand-fins" },
  },
  {
    id: "paddlefish",
    name: "Chinese Paddlefish",
    scientificName: "Psephurus gladius",
    emoji: "🐟",
    color: "#90A4AE",
    accentColor: "#455A64",
    category: "Fish",
    conservationStatus: "CR",
    population: "0 (declared extinct 2020)",
    size: "Up to 7 m",
    habitat: "Large rivers",
    range: "Yangtze River (historical)",
    threats: ["Overfishing", "Dam construction", "Habitat loss"],
    description: "Known as the 'panda of the Yangtze,' this enormous paddle-snouted fish was declared extinct in 2020. One of the largest freshwater fish ever known.",
    funFact: "The Chinese paddlefish, once reaching 7 meters long, was declared extinct in 2020 — it was last definitively seen alive in 2003!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#90A4AE", secondaryColor: "#455A64", bodyScale: [2.5, 0.5, 0.3], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "paddle-snout" },
  },
  {
    id: "smalltooth-sawfish",
    name: "Smalltooth Sawfish",
    scientificName: "Pristis pectinata",
    emoji: "🐟",
    color: "#8D6E63",
    accentColor: "#5D4037",
    category: "Fish",
    conservationStatus: "CR",
    population: "~5,000",
    size: "Up to 5.5 m",
    habitat: "Coastal, estuarine",
    range: "Florida, Bahamas (historical range much larger)",
    threats: ["Habitat loss", "Bycatch", "Slow reproduction"],
    description: "Once found throughout the Atlantic, this sawfish has lost 95% of its range. Its saw has both mechanical and electrical sensing functions.",
    funFact: "Smalltooth sawfish can reproduce without mating — females have been documented producing offspring via parthenogenesis (virgin birth)!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#5D4037", bodyScale: [2.0, 0.4, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "saw-snout" },
  },

  // ═══════════════════════════════════════════════════════════
  // INSECTS (69-78)
  // ═══════════════════════════════════════════════════════════
  {
    id: "monarch-butterfly",
    name: "Monarch Butterfly",
    scientificName: "Danaus plexippus",
    emoji: "🦋",
    color: "#FF7043",
    accentColor: "#212121",
    category: "Insect",
    conservationStatus: "EN",
    population: "Millions (declining 80%+)",
    size: "9.3–10.2 cm wingspan",
    habitat: "Meadows, fields, milkweed patches",
    range: "North America → Mexico (migratory)",
    threats: ["Milkweed loss (herbicides)", "Climate change", "Deforestation at wintering sites"],
    description: "Famous for its epic 4,800-km migration from Canada to Mexico. Larvae feed exclusively on milkweed, which makes them toxic to predators.",
    funFact: "Monarchs navigate thousands of miles using an internal sun compass and magnetic field sensor in their antennae — and they've never made the trip before!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#FF7043", secondaryColor: "#212121", bodyScale: [0.2, 0.08, 0.03], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "butterfly-wings" },
  },
  {
    id: "lords-howe-island-stick-insect",
    name: "Lord Howe Island Stick Insect",
    scientificName: "Dryococelus australis",
    emoji: "🪲",
    color: "#4E342E",
    accentColor: "#3E2723",
    category: "Insect",
    conservationStatus: "CR",
    population: "~30 in wild, 700+ captive",
    size: "12–15 cm",
    habitat: "Melaleuca shrubs on volcanic rock",
    range: "Ball's Pyramid, Australia",
    threats: ["Invasive rats (historically)", "Very small population", "Single location"],
    description: "Called the 'tree lobster,' this huge stick insect was thought extinct for 80 years until a tiny population was found on a barren sea stack.",
    funFact: "The entire wild population of 24 individuals was found under a single bush on Ball's Pyramid — the tallest volcanic sea stack in the world!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#4E342E", secondaryColor: "#3E2723", bodyScale: [0.4, 0.05, 0.04], limbCount: 6, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "stick-body" },
  },
  {
    id: "atlas-moth",
    name: "Atlas Moth",
    scientificName: "Attacus atlas",
    emoji: "🦋",
    color: "#A1887F",
    accentColor: "#6D4C41",
    category: "Insect",
    conservationStatus: "NT",
    population: "Declining",
    size: "25–30 cm wingspan",
    habitat: "Tropical and subtropical forest",
    range: "Southeast Asia",
    threats: ["Habitat loss", "Light pollution", "Collection"],
    description: "One of the largest moths in the world. Has no mouth and cannot eat — it survives on energy stored as a caterpillar for its 1–2 week adult life.",
    funFact: "Atlas moths have no mouths and can never eat — they live only 1-2 weeks as adults, surviving entirely on fat stored during the caterpillar stage!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#A1887F", secondaryColor: "#6D4C41", bodyScale: [0.3, 0.12, 0.04], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "giant-wings" },
  },
  {
    id: "queen-alexandras-birdwing",
    name: "Queen Alexandra's Birdwing",
    scientificName: "Ornithoptera alexandrae",
    emoji: "🦋",
    color: "#26A69A",
    accentColor: "#00695C",
    category: "Insect",
    conservationStatus: "EN",
    population: "Unknown (very rare)",
    size: "Up to 31 cm wingspan",
    habitat: "Lowland tropical rainforest",
    range: "Northern Province, Papua New Guinea",
    threats: ["Habitat loss", "Logging", "Oil palm plantations", "Volcanic activity"],
    description: "The largest butterfly in the world. Females have brown wings spanning up to 31 cm while males display iridescent blue-green wings.",
    funFact: "The first specimen was collected by shooting it with a shotgun in 1906 because it was flying too high to catch with a net!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#26A69A", secondaryColor: "#00695C", bodyScale: [0.35, 0.12, 0.04], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "iridescent-wings" },
  },
  {
    id: "hercules-beetle",
    name: "Hercules Beetle",
    scientificName: "Dynastes hercules",
    emoji: "🪲",
    color: "#827717",
    accentColor: "#33691E",
    category: "Insect",
    conservationStatus: "VU",
    population: "Declining",
    size: "Up to 17 cm (with horn)",
    habitat: "Tropical rainforest canopy",
    range: "Central and South America",
    threats: ["Habitat loss", "Deforestation", "Collection"],
    description: "The longest beetle in the world, famous for its enormous horn used in male combat. Can lift up to 850 times its own body weight.",
    funFact: "The Hercules beetle can lift 850 times its body weight — proportionally, that's like a human lifting 65 tons, or about 10 African elephants!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#827717", secondaryColor: "#33691E", bodyScale: [0.3, 0.12, 0.08], limbCount: 6, hasHorns: true, hasWings: true, hasTail: false, hasFins: false, hasShell: true, specialFeature: "giant-horn" },
  },
  {
    id: "wallace-giant-bee",
    name: "Wallace's Giant Bee",
    scientificName: "Megachile pluto",
    emoji: "🐝",
    color: "#37474F",
    accentColor: "#FFA000",
    category: "Insect",
    conservationStatus: "VU",
    population: "Unknown (very rare)",
    size: "3.8 cm body, 6.35 cm wingspan",
    habitat: "Lowland tropical forest",
    range: "North Moluccas, Indonesia",
    threats: ["Deforestation", "Illegal collection", "Habitat loss"],
    description: "The world's largest bee, rediscovered in 2019 after not being seen for 38 years. Has massive jaws used to collect tree resin for its nest.",
    funFact: "Wallace's giant bee was lost to science for 38 years — it was dramatically rediscovered in 2019 living inside active termite mounds in Indonesian trees!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#37474F", secondaryColor: "#FFA000", bodyScale: [0.2, 0.08, 0.06], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "large-mandibles" },
  },
  {
    id: "delhi-sands-flower-loving-fly",
    name: "Delhi Sands Flower-loving Fly",
    scientificName: "Rhaphiomidas terminatus abdominalis",
    emoji: "🪰",
    color: "#FF8A65",
    accentColor: "#E64A19",
    category: "Insect",
    conservationStatus: "CR",
    population: "Unknown (very small)",
    size: "2.5 cm",
    habitat: "Inland sand dune habitat",
    range: "San Bernardino, California, USA",
    threats: ["Urban development", "Habitat loss (98% lost)", "Pollution"],
    description: "The first fly to be listed under the US Endangered Species Act. Lives only in a specific type of fine sand dune habitat mostly paved over.",
    funFact: "This fly delayed a $150 million hospital project and required a highway to be rerouted — it's the only fly protected by the Endangered Species Act!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#FF8A65", secondaryColor: "#E64A19", bodyScale: [0.12, 0.04, 0.03], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "fuzzy-body" },
  },
  {
    id: "weta",
    name: "Giant Wētā",
    scientificName: "Deinacrida heteracantha",
    emoji: "🦗",
    color: "#795548",
    accentColor: "#4E342E",
    category: "Insect",
    conservationStatus: "VU",
    population: "Unknown (declining)",
    size: "Up to 10 cm body, 70 g",
    habitat: "Broadleaf and podocarp forests",
    range: "New Zealand (predator-free islands)",
    threats: ["Introduced rats and mice", "Habitat loss"],
    description: "One of the heaviest insects in the world, weighing as much as three mice. A prehistoric insect that evolved before the dinosaurs went extinct.",
    funFact: "Giant wētā are heavier than sparrows and can weigh more than three adult mice — one specimen weighed 71 grams, more than any other known insect!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#795548", secondaryColor: "#4E342E", bodyScale: [0.25, 0.1, 0.07], limbCount: 6, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "armored-body" },
  },
  {
    id: "rusty-patched-bumblebee",
    name: "Rusty Patched Bumblebee",
    scientificName: "Bombus affinis",
    emoji: "🐝",
    color: "#FDD835",
    accentColor: "#212121",
    category: "Insect",
    conservationStatus: "CR",
    population: "Declined 87%+",
    size: "1.2–2.0 cm",
    habitat: "Grasslands, prairies, urban gardens",
    range: "Eastern and midwestern USA",
    threats: ["Pesticides", "Disease", "Habitat loss", "Climate change"],
    description: "A bumblebee once common across 28 US states, now critically endangered. Named for the rusty-colored patch on its second abdominal segment.",
    funFact: "This was the first bee listed under the US Endangered Species Act in 2017 — it has lost 87% of its population and 90% of its range in 20 years!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#FDD835", secondaryColor: "#212121", bodyScale: [0.1, 0.06, 0.05], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "fuzzy-body" },
  },
  {
    id: "blue-morpho",
    name: "Blue Morpho Butterfly",
    scientificName: "Morpho menelaus",
    emoji: "🦋",
    color: "#1E88E5",
    accentColor: "#0D47A1",
    category: "Insect",
    conservationStatus: "NT",
    population: "Declining",
    size: "12–20 cm wingspan",
    habitat: "Tropical forest understory",
    range: "Central and South America",
    threats: ["Deforestation", "Collection for jewelry trade", "Habitat fragmentation"],
    description: "Famous for its stunning iridescent blue wings, which aren't actually pigmented — the color comes from microscopic scales that reflect light.",
    funFact: "The blue morpho's color isn't from pigment — millions of microscopic scales create structural color by interfering with light waves, inspiring new tech!",
    bodyType: "insectoid",
    bodyParams: { primaryColor: "#1E88E5", secondaryColor: "#0D47A1", bodyScale: [0.25, 0.1, 0.03], limbCount: 6, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "iridescent-wings" },
  },

  // ═══════════════════════════════════════════════════════════
  // MARINE INVERTEBRATES (79-88)
  // ═══════════════════════════════════════════════════════════
  {
    id: "nautilus",
    name: "Chambered Nautilus",
    scientificName: "Nautilus pompilius",
    emoji: "🐚",
    color: "#FF8A65",
    accentColor: "#E64A19",
    category: "Marine",
    conservationStatus: "VU",
    population: "Unknown (declining)",
    size: "20–25 cm shell",
    habitat: "Deep ocean slopes (100–800 m)",
    range: "Indo-Pacific tropics",
    threats: ["Shell trade", "Overharvesting", "Deep-sea mining"],
    description: "A living fossil that has survived virtually unchanged for 500 million years. Its beautiful spiral shell contains gas-filled chambers for buoyancy control.",
    funFact: "The nautilus has over 90 tentacles (compared to an octopus's 8) and its shell follows a perfect mathematical logarithmic spiral!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#FF8A65", secondaryColor: "#E64A19", bodyScale: [0.4, 0.35, 0.3], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: true, specialFeature: "spiral-shell" },
  },
  {
    id: "blue-whale",
    name: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    emoji: "🐋",
    color: "#42A5F5",
    accentColor: "#1565C0",
    category: "Marine",
    conservationStatus: "EN",
    population: "10,000–25,000",
    size: "24–30 m",
    habitat: "Open ocean",
    range: "All oceans",
    threats: ["Ship strikes", "Entanglement", "Noise pollution", "Climate change"],
    description: "The largest animal to have EVER lived on Earth — larger than any dinosaur. Its heart is the size of a small car and its tongue weighs as much as an elephant.",
    funFact: "A blue whale's heart is so large that a small child could crawl through its arteries, and its heartbeat can be detected from 3 km away!",
    bodyType: "aquatic",
    bodyParams: { primaryColor: "#42A5F5", secondaryColor: "#1565C0", bodyScale: [3.0, 0.8, 0.6], limbCount: 2, hasHorns: false, hasWings: false, hasTail: true, hasFins: true, hasShell: false, specialFeature: "baleen" },
  },
  {
    id: "giant-clam",
    name: "Giant Clam",
    scientificName: "Tridacna gigas",
    emoji: "🐚",
    color: "#26A69A",
    accentColor: "#00695C",
    category: "Marine",
    conservationStatus: "VU",
    population: "Unknown (declining)",
    size: "Up to 1.2 m",
    habitat: "Shallow coral reefs",
    range: "Indo-Pacific reefs",
    threats: ["Overharvesting (food, shells)", "Coral reef degradation", "Pollution"],
    description: "The largest living bivalve. Has a symbiotic relationship with photosynthetic algae in its mantle, giving it vibrant colors.",
    funFact: "Giant clams are so heavy (up to 200 kg) they can't close their shells completely — but the myth that they trap divers is completely false!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#26A69A", secondaryColor: "#00695C", bodyScale: [0.8, 0.3, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: true, specialFeature: "wavy-shell" },
  },
  {
    id: "elkhorn-coral",
    name: "Elkhorn Coral",
    scientificName: "Acropora palmata",
    emoji: "🪸",
    color: "#FFB74D",
    accentColor: "#E65100",
    category: "Marine",
    conservationStatus: "CR",
    population: "Declined 97% since 1980",
    size: "Up to 3.7 m wide colonies",
    habitat: "Shallow reef crests",
    range: "Caribbean Sea, western Atlantic",
    threats: ["Coral bleaching", "White band disease", "Hurricane damage", "Ocean acidification"],
    description: "Once the dominant reef-building coral in the Caribbean, forming dense thickets in shallow water. Has declined by 97% since the 1980s.",
    funFact: "Elkhorn coral can grow 5–10 cm per year and a single colony can live for hundreds of years — but 97% have died since 1980!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#FFB74D", secondaryColor: "#E65100", bodyScale: [1.0, 0.8, 0.6], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "branching" },
  },
  {
    id: "giant-pacific-octopus",
    name: "Giant Pacific Octopus",
    scientificName: "Enteroctopus dofleini",
    emoji: "🐙",
    color: "#E53935",
    accentColor: "#B71C1C",
    category: "Marine",
    conservationStatus: "NT",
    population: "Unknown",
    size: "3–5 m arm span",
    habitat: "Rocky reefs, kelp forests",
    range: "North Pacific Ocean",
    threats: ["Overfishing", "Bycatch", "Ocean warming", "Pollution"],
    description: "The largest octopus species with an arm span of up to 6 meters. Highly intelligent, can solve puzzles, open jars, and change color instantly.",
    funFact: "Giant Pacific octopuses have three hearts, blue blood, and can squeeze through any opening larger than their beak — the only hard part of their body!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#E53935", secondaryColor: "#B71C1C", bodyScale: [0.8, 0.6, 0.5], limbCount: 8, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "tentacles" },
  },
  {
    id: "horseshoe-crab",
    name: "Atlantic Horseshoe Crab",
    scientificName: "Limulus polyphemus",
    emoji: "🦀",
    color: "#795548",
    accentColor: "#4E342E",
    category: "Marine",
    conservationStatus: "VU",
    population: "Declining",
    size: "30–60 cm",
    habitat: "Sandy coastlines, shallow bays",
    range: "Atlantic coast (Maine to Yucatán)",
    threats: ["Overharvesting for bait and biomedical use", "Habitat loss", "Climate change"],
    description: "A 450-million-year-old living fossil. Not a true crab — closer to spiders and scorpions. Has blue, copper-based blood used to test vaccine safety.",
    funFact: "Horseshoe crab blood is blue (copper-based) and worth $60,000 per gallon — it's used to test every vaccine and injection for bacterial contamination!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#795548", secondaryColor: "#4E342E", bodyScale: [0.5, 0.1, 0.4], limbCount: 10, hasHorns: false, hasWings: false, hasTail: true, hasFins: false, hasShell: true, specialFeature: "helmet-shell" },
  },
  {
    id: "sunflower-sea-star",
    name: "Sunflower Sea Star",
    scientificName: "Pycnopodia helianthoides",
    emoji: "⭐",
    color: "#FF7043",
    accentColor: "#9C27B0",
    category: "Marine",
    conservationStatus: "CR",
    population: "Declined 90%+",
    size: "Up to 1 m diameter",
    habitat: "Rocky subtidal to deep ocean",
    range: "NE Pacific (Alaska to Baja California)",
    threats: ["Sea star wasting disease", "Ocean warming", "Urchin overgrazing"],
    description: "The largest and fastest sea star, with up to 24 arms. A keystone predator that keeps sea urchin populations in check, protecting kelp forests.",
    funFact: "This sea star has up to 15,000 tube feet and is the fastest sea star in the world — it can move at 1 meter per minute and has up to 24 arms!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#FF7043", secondaryColor: "#9C27B0", bodyScale: [0.8, 0.06, 0.8], limbCount: 24, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "many-arms" },
  },
  {
    id: "sea-angel",
    name: "Sea Angel",
    scientificName: "Clione limacina",
    emoji: "👼",
    color: "#CE93D8",
    accentColor: "#7B1FA2",
    category: "Marine",
    conservationStatus: "NT",
    population: "Declining",
    size: "1–4 cm",
    habitat: "Cold open ocean (surface to 500 m)",
    range: "Arctic and subarctic oceans",
    threats: ["Ocean acidification", "Warming waters", "Food web disruption"],
    description: "A tiny, ethereal swimming sea slug that looks like a transparent angel with wing-like appendages. A predator of sea butterflies.",
    funFact: "Sea angels are so beautiful that in Japan they're called 'clione' and kept as pets — but they shoot out tentacle hooks to catch prey like tiny aliens!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#CE93D8", secondaryColor: "#7B1FA2", bodyScale: [0.15, 0.05, 0.04], limbCount: 2, hasHorns: false, hasWings: true, hasTail: false, hasFins: false, hasShell: false, specialFeature: "wing-appendages" },
  },
  {
    id: "christmas-island-red-crab",
    name: "Christmas Island Red Crab",
    scientificName: "Gecarcoidea natalis",
    emoji: "🦀",
    color: "#E53935",
    accentColor: "#B71C1C",
    category: "Marine",
    conservationStatus: "NT",
    population: "~50 million (declining from 130M)",
    size: "11.6 cm carapace",
    habitat: "Rainforest floor (inland, migrates to coast)",
    range: "Christmas Island, Indian Ocean",
    threats: ["Invasive yellow crazy ants", "Habitat loss", "Climate change"],
    description: "Famous for their spectacular annual migration when 50 million crabs march from forest to sea to spawn, turning roads and beaches red.",
    funFact: "During their annual spawning migration, Christmas Island builds special crab bridges and tunnels under roads — traffic stops for weeks!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#E53935", secondaryColor: "#B71C1C", bodyScale: [0.2, 0.08, 0.15], limbCount: 10, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: true, specialFeature: "claws" },
  },
  {
    id: "japanese-spider-crab",
    name: "Japanese Spider Crab",
    scientificName: "Macrocheira kaempferi",
    emoji: "🦀",
    color: "#FF7043",
    accentColor: "#D84315",
    category: "Marine",
    conservationStatus: "VU",
    population: "Unknown (declining)",
    size: "Up to 3.7 m leg span",
    habitat: "Deep ocean floor (50–600 m)",
    range: "Pacific coast of Japan",
    threats: ["Overfishing", "Deep-sea trawling", "Slow reproduction"],
    description: "The largest living arthropod with a leg span reaching 3.7 meters. Despite its frightening appearance, it is a gentle scavenger.",
    funFact: "Japanese spider crabs can live over 100 years and their leg span of 3.7 meters would stretch across a standard parking space!",
    bodyType: "radial",
    bodyParams: { primaryColor: "#FF7043", secondaryColor: "#D84315", bodyScale: [0.5, 0.15, 0.4], limbCount: 10, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: true, specialFeature: "long-legs" },
  },

  // ═══════════════════════════════════════════════════════════
  // PLANTS (89-100)
  // ═══════════════════════════════════════════════════════════
  {
    id: "corpse-flower",
    name: "Corpse Flower",
    scientificName: "Amorphophallus titanum",
    emoji: "🌺",
    color: "#880E4F",
    accentColor: "#4A148C",
    category: "Plant",
    conservationStatus: "EN",
    population: "~1,000 in wild",
    size: "Up to 3.1 m tall",
    habitat: "Tropical rainforest understory",
    range: "Sumatra, Indonesia",
    threats: ["Deforestation", "Logging", "Collection"],
    description: "Bears the world's largest unbranched flower structure, which blooms for only 24–48 hours and smells like rotting flesh to attract pollinators.",
    funFact: "The corpse flower heats itself to 36°C (human body temperature) to spread its putrid scent — it blooms only once every 7–10 years!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#880E4F", secondaryColor: "#4A148C", bodyScale: [0.6, 2.0, 0.6], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "giant-flower" },
  },
  {
    id: "ghost-orchid",
    name: "Ghost Orchid",
    scientificName: "Dendrophylax lindenii",
    emoji: "🌸",
    color: "#E8EAF6",
    accentColor: "#C5CAE9",
    category: "Plant",
    conservationStatus: "EN",
    population: "~2,000",
    size: "15–25 cm",
    habitat: "Humid swamp forest canopy",
    range: "Florida (USA), Cuba, Bahamas",
    threats: ["Poaching by collectors", "Habitat loss", "Climate change", "Hurricane damage"],
    description: "A leafless, rootless-looking orchid that appears to float in mid-air. Has no leaves and photosynthesizes through its roots.",
    funFact: "The ghost orchid has no leaves — it photosynthesizes through its green roots and only blooms for 1–2 weeks, making it nearly impossible to find in flower!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#E8EAF6", secondaryColor: "#C5CAE9", bodyScale: [0.3, 0.4, 0.2], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "floating-roots" },
  },
  {
    id: "wollemi-pine",
    name: "Wollemi Pine",
    scientificName: "Wollemia nobilis",
    emoji: "🌲",
    color: "#2E7D32",
    accentColor: "#1B5E20",
    category: "Plant",
    conservationStatus: "CR",
    population: "~100 in wild",
    size: "25–40 m tall",
    habitat: "Temperate rainforest canyons",
    range: "Wollemi NP, NSW, Australia",
    threats: ["Single small population", "Phytophthora disease", "Climate change", "Bushfire"],
    description: "A 'living fossil' tree discovered in 1994, previously known only from 200-million-year-old fossils. Its exact location is a state secret.",
    funFact: "The Wollemi pine's location is so secret that scientists are blindfolded and helicoptered in — fewer people have seen it than have walked on the Moon!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#2E7D32", secondaryColor: "#1B5E20", bodyScale: [0.4, 2.5, 0.4], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "ancient-bark" },
  },
  {
    id: "venus-flytrap",
    name: "Venus Flytrap",
    scientificName: "Dionaea muscipula",
    emoji: "🪴",
    color: "#66BB6A",
    accentColor: "#C62828",
    category: "Plant",
    conservationStatus: "VU",
    population: "33,000 plants in wild",
    size: "10–13 cm",
    habitat: "Wet pine savanna bogs",
    range: "Carolinas, USA (within 120 km radius)",
    threats: ["Poaching", "Habitat loss", "Fire suppression", "Drainage"],
    description: "The most famous carnivorous plant. Its jaw-like traps snap shut in 0.1 seconds when trigger hairs are touched, trapping insects.",
    funFact: "A Venus flytrap's trap snaps shut in 100 milliseconds — one of the fastest movements in the plant kingdom. It can count: it needs exactly 2 touches to trigger!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#66BB6A", secondaryColor: "#C62828", bodyScale: [0.2, 0.2, 0.2], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "trap-jaws" },
  },
  {
    id: "rafflesia",
    name: "Rafflesia",
    scientificName: "Rafflesia arnoldii",
    emoji: "🌺",
    color: "#C62828",
    accentColor: "#880E4F",
    category: "Plant",
    conservationStatus: "CR",
    population: "Unknown (very rare)",
    size: "Up to 1 m diameter flower",
    habitat: "Tropical rainforest floor",
    range: "Sumatra, Borneo",
    threats: ["Deforestation", "Tourism disturbance", "Very rare blooming"],
    description: "Produces the largest individual flower in the world (up to 1 m across). A parasitic plant with no leaves, stems, or roots.",
    funFact: "Rafflesia has no roots, leaves, or stems — it steals all its nutrients from a vine, and its giant flower smells like rotting meat to attract fly pollinators!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#C62828", secondaryColor: "#880E4F", bodyScale: [0.8, 0.3, 0.8], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "giant-petals" },
  },
  {
    id: "welwitschia",
    name: "Welwitschia",
    scientificName: "Welwitschia mirabilis",
    emoji: "🌿",
    color: "#8D6E63",
    accentColor: "#4E342E",
    category: "Plant",
    conservationStatus: "NT",
    population: "Unknown (stable)",
    size: "Up to 2 m wide",
    habitat: "Namib Desert gravel plains",
    range: "Namibia, Angola",
    threats: ["Climate change", "Illegal collection", "Off-road vehicles", "Mining"],
    description: "A bizarre desert plant that produces only two leaves in its entire life — which grow continuously and can live for over 2,000 years.",
    funFact: "Welwitschia only ever grows TWO leaves its entire life — but those two leaves continuously grow for over 2,000 years, splitting and fraying in the wind!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#8D6E63", secondaryColor: "#4E342E", bodyScale: [0.8, 0.4, 0.8], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "two-leaves" },
  },
  {
    id: "jade-vine",
    name: "Jade Vine",
    scientificName: "Strongylodon macrobotrys",
    emoji: "🌿",
    color: "#00BFA5",
    accentColor: "#00695C",
    category: "Plant",
    conservationStatus: "VU",
    population: "Declining",
    size: "Up to 18 m long",
    habitat: "Tropical rainforest canopy",
    range: "Philippines",
    threats: ["Deforestation", "Pollinator decline (bats)", "Habitat fragmentation"],
    description: "Produces stunning turquoise claw-shaped flowers that glow in the dark due to their unique pigment. Pollinated by bats.",
    funFact: "Jade vine flowers are bioluminescent — they glow turquoise-green in the dark, which helps their bat pollinators find them at night!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#00BFA5", secondaryColor: "#00695C", bodyScale: [0.4, 1.5, 0.3], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "hanging-flowers" },
  },
  {
    id: "monkey-puzzle-tree",
    name: "Monkey Puzzle Tree",
    scientificName: "Araucaria araucana",
    emoji: "🌲",
    color: "#2E7D32",
    accentColor: "#1B5E20",
    category: "Plant",
    conservationStatus: "EN",
    population: "Declining",
    size: "Up to 40 m tall",
    habitat: "Andean mountain forests",
    range: "Chile, Argentina",
    threats: ["Logging", "Fire", "Grazing", "Climate change"],
    description: "A prehistoric conifer with sharp, armored leaves that overlap like scales. A living fossil from the Jurassic period, 200+ million years old.",
    funFact: "Its name comes from the comment: 'It would puzzle a monkey to climb that tree!' — it's covered in sharp overlapping scale-like leaves!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#2E7D32", secondaryColor: "#1B5E20", bodyScale: [0.5, 2.5, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "spiral-branches" },
  },
  {
    id: "dragon-blood-tree",
    name: "Dragon Blood Tree",
    scientificName: "Dracaena cinnabari",
    emoji: "🌳",
    color: "#C62828",
    accentColor: "#4E342E",
    category: "Plant",
    conservationStatus: "VU",
    population: "Declining",
    size: "Up to 10 m tall",
    habitat: "Arid highland plateaus",
    range: "Socotra Island, Yemen",
    threats: ["Climate change", "Overgrazing by goats", "Drought"],
    description: "An alien-looking tree with an umbrella-shaped canopy that bleeds crimson red sap. Found only on the remote island of Socotra.",
    funFact: "When cut, the tree bleeds a dark red resin called 'dragon's blood' — it was used as a dye, medicine, and even violin varnish for centuries!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#C62828", secondaryColor: "#4E342E", bodyScale: [0.6, 1.8, 0.6], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "umbrella-canopy" },
  },
  {
    id: "baobab",
    name: "Grandidier's Baobab",
    scientificName: "Adansonia grandidieri",
    emoji: "🌳",
    color: "#A1887F",
    accentColor: "#5D4037",
    category: "Plant",
    conservationStatus: "EN",
    population: "Unknown (declining)",
    size: "Up to 25 m tall, 3 m diameter",
    habitat: "Dry deciduous forest",
    range: "Western Madagascar",
    threats: ["Habitat loss", "Fire", "Agricultural expansion"],
    description: "The tallest and most iconic of Madagascar's six baobab species. Its swollen trunk can store up to 120,000 liters of water.",
    funFact: "Grandidier's baobab can store 120,000 liters of water in its trunk — elephants in Africa have been known to gouge baobabs to drink during droughts!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#A1887F", secondaryColor: "#5D4037", bodyScale: [0.8, 2.5, 0.8], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "bottle-trunk" },
  },
  {
    id: "titan-arum",
    name: "Titan Arum",
    scientificName: "Amorphophallus titanum",
    emoji: "🌺",
    color: "#880E4F",
    accentColor: "#311B92",
    category: "Plant",
    conservationStatus: "EN",
    population: "~1,000 in wild",
    size: "Up to 3 m spadix",
    habitat: "Tropical rainforest clearings",
    range: "Sumatra, Indonesia",
    threats: ["Deforestation", "Collection", "Habitat loss"],
    description: "Produces the tallest flower structure in the plant kingdom with a spathe that unfurls to reveal a dark, velvety interior.",
    funFact: "The titan arum's spadix can reach 3 meters tall and the entire flowering event lasts only 24-48 hours — then it collapses and won't bloom again for 7-10 years!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#880E4F", secondaryColor: "#311B92", bodyScale: [0.5, 2.0, 0.5], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "giant-spathe" },
  },
  {
    id: "pitcher-plant",
    name: "Attenborough's Pitcher Plant",
    scientificName: "Nepenthes attenboroughii",
    emoji: "🪴",
    color: "#66BB6A",
    accentColor: "#C62828",
    category: "Plant",
    conservationStatus: "CR",
    population: "Unknown (very rare)",
    size: "Pitchers up to 30 cm",
    habitat: "Ultramafic mountain summit",
    range: "Mount Victoria, Palawan, Philippines",
    threats: ["Poaching by collectors", "Tiny range", "Climate change"],
    description: "One of the largest carnivorous pitcher plants, capable of trapping rats. Named after Sir David Attenborough. Discovered in 2007.",
    funFact: "This pitcher plant is large enough to trap and digest rats — it was discovered only in 2007 on a single mountain peak in the Philippines!",
    bodyType: "plant",
    bodyParams: { primaryColor: "#66BB6A", secondaryColor: "#C62828", bodyScale: [0.3, 0.5, 0.2], limbCount: 0, hasHorns: false, hasWings: false, hasTail: false, hasFins: false, hasShell: false, specialFeature: "pitcher-trap" },
  },
];

export function getSpeciesById(id: string): RareSpeciesData | undefined {
  return RARE_SPECIES.find(s => s.id === id);
}

export const CATEGORIES = ["All", "Mammal", "Bird", "Reptile", "Amphibian", "Fish", "Insect", "Marine", "Plant"] as const;
export const STATUS_LABELS: Record<string, { label: string; color: string }> = {
  CR: { label: "Critically Endangered", color: "#E53935" },
  EN: { label: "Endangered", color: "#FF9800" },
  VU: { label: "Vulnerable", color: "#FDD835" },
  NT: { label: "Near Threatened", color: "#42A5F5" },
};
