// ═══════════════════════════════════════════════════════════════
// Biosphere — Comprehensive Scientific Research Seed Data
// ═══════════════════════════════════════════════════════════════

import {
  ResearchField,
  ResearchTopic,
  Institution,
  Journal,
  Scientist,
  ScientificDiscovery,
  ResearchPaper,
  Dataset,
  Experiment,
} from './types';

export const RESEARCH_FIELDS: ResearchField[] = [
  {
    id: 'genetics',
    name: 'Genetics & Genomics',
    description: 'Structure, function, and editing of genes, chromosomes, and inheritance pathways.',
    icon: 'Dna',
    color: '#3B82F6',
    topicIds: ['gene-editing', 'dna-replication', 'epigenetics', 'sequencing'],
  },
  {
    id: 'cell-biology',
    name: 'Cell Biology & Physiology',
    description: 'Cellular mechanics, organelle signaling, mitosis, and membrane dynamics.',
    icon: 'Microscope',
    color: '#10B981',
    topicIds: ['cell-cycle', 'mitochondria', 'membrane-transport', 'stem-cells'],
  },
  {
    id: 'microbiology',
    name: 'Microbiology & Virology',
    description: 'Bacterial metabolism, viral kinetics, microbiomes, and immune evasion.',
    icon: 'Activity',
    color: '#8B5CF6',
    topicIds: ['gut-microbiome', 'viral-replication', 'antibiotic-resistance'],
  },
  {
    id: 'ecology',
    name: 'Ecology & Environmental Biology',
    description: 'Trophic food webs, chemosynthesis, ecosystem resilience, and biodiversity.',
    icon: 'Globe',
    color: '#059669',
    topicIds: ['deep-sea-vents', 'trophic-cascades', 'carbon-cycle'],
  },
  {
    id: 'neuroscience',
    name: 'Neuroscience & Neurobiology',
    description: 'Synaptic transmission, neurodegenerative protein aggregation, and neural circuits.',
    icon: 'Brain',
    color: '#EC4899',
    topicIds: ['amyloid-plaques', 'synaptic-plasticity', 'action-potentials'],
  },
  {
    id: 'biochemistry',
    name: 'Biochemistry & Structural Biology',
    description: 'Enzyme catalytic kinetics, protein folding, and macromolecular structures.',
    icon: 'Atom',
    color: '#F59E0B',
    topicIds: ['crispr-cas9-structure', 'enzymatic-catalysis', 'photosynthesis'],
  },
];

export const RESEARCH_TOPICS: ResearchTopic[] = [
  {
    id: 'gene-editing',
    fieldId: 'genetics',
    name: 'CRISPR Gene Editing',
    description: 'Precision genomic modification using Cas endonucleases and guide RNA systems.',
    keywords: ['CRISPR', 'Cas9', 'sgRNA', 'Off-target cleavage', 'Base editing'],
    relatedTopicIds: ['sequencing', 'epigenetics'],
  },
  {
    id: 'dna-replication',
    fieldId: 'genetics',
    name: 'DNA Replication & Structure',
    description: 'Double helix geometry, polymerase synthesis, and Okazaki fragment ligation.',
    keywords: ['Double Helix', 'DNA Polymerase', 'Hydrogen Bonding', 'Base Pairs'],
    relatedTopicIds: ['sequencing'],
  },
  {
    id: 'cell-cycle',
    fieldId: 'cell-biology',
    name: 'Cell Cycle & Checkpoints',
    description: 'Mitotic spindle assembly checkpoints, cyclin-dependent kinases, and aneuploidy prevention.',
    keywords: ['Mitosis', 'Spindle Checkpoint', 'Anaphase', 'Kinetochore', 'APC/C'],
    relatedTopicIds: ['stem-cells'],
  },
  {
    id: 'gut-microbiome',
    fieldId: 'microbiology',
    name: 'Gut Microbiome & Host Metabolism',
    description: 'Anaerobic bacterial fermentation of dietary fibers into short-chain fatty acids.',
    keywords: ['SCFA', 'Bacteroidetes', 'GLP-1', 'Insulin Sensitivity', 'Butyrate'],
    relatedTopicIds: ['antibiotic-resistance'],
  },
  {
    id: 'deep-sea-vents',
    fieldId: 'ecology',
    name: 'Chemosynthesis in Deep Sea Vents',
    description: 'Sulfur-oxidizing bacterial primary productivity at geothermal hydrothermal plumes.',
    keywords: ['Hydrothermal Vents', 'Hydrogen Sulfide', 'Riftia pachyptila', 'Endosymbiosis'],
    relatedTopicIds: ['trophic-cascades'],
  },
  {
    id: 'amyloid-plaques',
    fieldId: 'neuroscience',
    name: 'Amyloid & Neurodegeneration',
    description: 'Biochemical pathways of amyloid-beta plaque accumulation and hyperphosphorylated Tau.',
    keywords: ['Alzheimers', 'APP', 'BACE1', 'Tau Tangles', 'Synaptic Atrophy'],
    relatedTopicIds: ['synaptic-plasticity'],
  },
];

export const INSTITUTIONS: Institution[] = [
  {
    id: 'inst_cambridge',
    name: 'University of Cambridge',
    shortName: 'Cambridge',
    country: 'United Kingdom',
    city: 'Cambridge',
    type: 'university',
    website: 'https://www.cam.ac.uk',
  },
  {
    id: 'inst_berkeley',
    name: 'University of California, Berkeley',
    shortName: 'UC Berkeley',
    country: 'USA',
    city: 'Berkeley, CA',
    type: 'university',
    website: 'https://www.berkeley.edu',
  },
  {
    id: 'inst_broad',
    name: 'Broad Institute of MIT and Harvard',
    shortName: 'Broad Institute',
    country: 'USA',
    city: 'Cambridge, MA',
    type: 'research-institute',
    website: 'https://www.broadinstitute.org',
  },
  {
    id: 'inst_coldspring',
    name: 'Cold Spring Harbor Laboratory',
    shortName: 'CSHL',
    country: 'USA',
    city: 'Cold Spring Harbor, NY',
    type: 'laboratory',
    website: 'https://www.cshl.edu',
  },
  {
    id: 'inst_maxplanck',
    name: 'Max Planck Institute for Infection Biology',
    shortName: 'Max Planck',
    country: 'Germany',
    city: 'Berlin',
    type: 'research-institute',
    website: 'https://www.mpiib-berlin.mpg.de',
  },
];

export const JOURNALS: Journal[] = [
  {
    id: 'journal_nature',
    name: 'Nature',
    shortName: 'Nature',
    publisher: 'Springer Nature',
    impactFactor: 64.8,
    issn: '0028-0836',
  },
  {
    id: 'journal_science',
    name: 'Science',
    shortName: 'Science',
    publisher: 'AAAS',
    impactFactor: 56.9,
    issn: '0036-8075',
  },
  {
    id: 'journal_cell',
    name: 'Cell',
    shortName: 'Cell',
    publisher: 'Cell Press / Elsevier',
    impactFactor: 66.8,
    issn: '0092-8674',
  },
  {
    id: 'journal_pnas',
    name: 'Proceedings of the National Academy of Sciences',
    shortName: 'PNAS',
    publisher: 'National Academy of Sciences',
    impactFactor: 11.1,
    issn: '0027-8424',
  },
];

export const SCIENTISTS: Scientist[] = [
  {
    id: 'sci_watson_crick',
    name: 'James Watson & Francis Crick',
    title: 'Molecular Biologists & Nobel Laureates',
    institutionId: 'inst_cambridge',
    fieldIds: ['genetics', 'biochemistry'],
    biography: 'Pioneered the discovery of the double-helical 3D molecular structure of Deoxyribonucleic Acid (DNA) in 1953 using X-ray diffraction data collected by Rosalind Franklin and Raymond Gosling.',
    bornYear: 1928,
    awards: ['Nobel Prize in Physiology or Medicine (1962)', 'Albert Lasker Basic Medical Research Award'],
    hIndex: 110,
    totalCitations: 145000,
    majorContributions: [
      'Discovery of DNA Double Helix structure',
      'Proposed complementary base pairing (A-T, G-C)',
      'Suggested semi-conservative replication mechanism',
    ],
    discoveryIds: ['disc_dna_double_helix'],
    paperIds: ['paper_dna_double_helix_1953'],
    experimentIds: ['exp_dna_base_pairing'],
    timeline: [
      { year: 1951, title: 'Began Collaboration at Cavendish', description: 'Initiated molecular model building for DNA structure.' },
      { year: 1953, title: 'Published Double Helix in Nature', description: 'Demonstrated antiparallel double helix geometry.' },
      { year: 1962, title: 'Awarded Nobel Prize', description: 'Honored for molecular structure of nucleic acids.' },
    ],
  },
  {
    id: 'sci_rosalind_franklin',
    name: 'Rosalind Franklin',
    title: 'Biophysicist & X-ray Crystallographer',
    institutionId: 'inst_cambridge',
    fieldIds: ['biochemistry', 'genetics'],
    biography: 'Pioneering physical chemist whose high-resolution Photo 51 X-ray diffraction image provided the essential empirical evidence proving the helical helical density and phosphate backbone geometry of DNA.',
    bornYear: 1920,
    diedYear: 1958,
    awards: ['Louisa Gross Horwitz Prize (Posthumous)', 'Royal Society Special Commendation'],
    hIndex: 85,
    totalCitations: 68000,
    majorContributions: [
      'Captured Photo 51 X-ray diffraction of B-DNA',
      'Discovered the outer phosphate backbone orientation',
      'Structural analysis of Tobacco Mosaic Virus',
    ],
    discoveryIds: ['disc_dna_double_helix'],
    paperIds: ['paper_franklin_dna_diffraction'],
    experimentIds: ['exp_xray_crystallography_dna'],
    timeline: [
      { year: 1951, title: 'Joined King\'s College London', description: 'Initiated high-humidity X-ray diffraction experiments on DNA fibers.' },
      { year: 1952, title: 'Captured Photo 51', description: 'Obtained definitive proof of helical lattice parameters.' },
    ],
  },
  {
    id: 'sci_jennifer_doudna',
    name: 'Dr. Jennifer Doudna',
    title: 'Professor of Biochemistry & Nobel Laureate',
    institutionId: 'inst_berkeley',
    fieldIds: ['genetics', 'biochemistry'],
    biography: 'Co-inventor of CRISPR-Cas9 programmable genome editing technology. Transformed molecular biology by demonstrating that Cas9 endonuclease can be directed by customizable guide RNA sequences to cut specific DNA targets.',
    bornYear: 1964,
    awards: ['Nobel Prize in Chemistry (2020)', 'Breakthrough Prize in Life Sciences (2015)', 'Japan Prize (2018)'],
    hIndex: 135,
    totalCitations: 180000,
    majorContributions: [
      'Reprogrammed CRISPR-Cas9 as a programmable gene-editing tool',
      'Determined structural mechanism of Cas9-sgRNA complexes',
      'Pioneered RNA interference and ribozyme structural biology',
    ],
    discoveryIds: ['disc_crispr_editing'],
    paperIds: ['paper_crispr_cas9_mammalian'],
    experimentIds: ['exp_crispr_target_cleavage'],
    timeline: [
      { year: 2011, title: 'Collaborated with Emmanuelle Charpentier', description: 'Joined forces to decipher bacterial adaptive immunity.' },
      { year: 2012, title: 'Landmark Science Publication', description: 'Showed dual-RNA guided cleavage of target DNA.' },
      { year: 2020, title: 'Awarded Nobel Prize in Chemistry', description: 'Recognized for development of genome editing method.' },
    ],
  },
  {
    id: 'sci_kary_mullis',
    name: 'Dr. Kary Mullis',
    title: 'Biochemist & Nobel Laureate',
    institutionId: 'inst_coldspring',
    fieldIds: ['genetics', 'biochemistry'],
    biography: 'Invented Polymerase Chain Reaction (PCR) in 1983, allowing scientists to amplify a specific DNA sequence millions of times in hours.',
    bornYear: 1944,
    diedYear: 2019,
    awards: ['Nobel Prize in Chemistry (1993)', 'Japan Prize (1993)'],
    hIndex: 72,
    totalCitations: 52000,
    majorContributions: [
      'Invention of Polymerase Chain Reaction (PCR)',
      'Thermal cycling amplification using thermostable Taq polymerase',
    ],
    discoveryIds: ['disc_pcr_amplification'],
    paperIds: ['paper_pcr_amplification'],
    experimentIds: ['exp_pcr_amplification'],
    timeline: [
      { year: 1983, title: 'Conceived PCR Concept', description: 'Devised thermal cycling primer extension method.' },
      { year: 1993, title: 'Awarded Nobel Prize', description: 'Received Nobel Prize for PCR invention.' },
    ],
  },
];

export const SCIENTIFIC_DISCOVERIES: ScientificDiscovery[] = [
  {
    id: 'disc_cell_theory',
    title: 'Discovery of Cell Theory',
    year: 1839,
    dateString: '1839',
    fieldId: 'cell-biology',
    topicIds: ['cell-cycle'],
    leadScientistIds: [],
    institutionId: 'inst_cambridge',
    summary: 'Established that all living organisms are composed of one or more cells, and that the cell is the fundamental unit of life.',
    simplifiedExplanation: 'Every living thing on Earth, from tiny bacteria to blue whales, is made of small living building blocks called cells.',
    scientificExplanation: 'The cell theory posits three key axioms: (1) All organisms consist of cells; (2) Cells are the functional unit of life; (3) All cells arise exclusively from pre-existing cells via division (omnis cellula e cellula).',
    impactScore: 100,
    milestoneOrder: 1,
    previousDiscoveryIds: [],
    nextDiscoveryIds: ['disc_mendelian_genetics'],
    paperIds: [],
    knowledgeGraphNodeIds: ['cell', 'cell-theory'],
  },
  {
    id: 'disc_mendelian_genetics',
    title: 'Mendelian Laws of Inheritance',
    year: 1866,
    dateString: '1866',
    fieldId: 'genetics',
    topicIds: ['dna-replication'],
    leadScientistIds: [],
    institutionId: 'inst_cambridge',
    summary: 'Discovered discrete hereditary factors (genes) and established principles of segregation and independent assortment through pea plant crosses.',
    simplifiedExplanation: 'Traits like flower color or height are passed down from parents to offspring in predictable mathematical patterns.',
    scientificExplanation: 'Mendel demonstrated that hereditary traits are transmitted as discrete units (alleles) that segregate during gametogenesis and assort independently into offspring phenotypes.',
    impactScore: 98,
    milestoneOrder: 2,
    previousDiscoveryIds: ['disc_cell_theory'],
    nextDiscoveryIds: ['disc_dna_double_helix'],
    paperIds: [],
    knowledgeGraphNodeIds: ['mendelian-genetics', 'allele'],
  },
  {
    id: 'disc_dna_double_helix',
    title: 'Discovery of the DNA Double Helix',
    year: 1953,
    dateString: 'April 25, 1953',
    fieldId: 'genetics',
    topicIds: ['dna-replication'],
    leadScientistIds: ['sci_watson_crick', 'sci_rosalind_franklin'],
    institutionId: 'inst_cambridge',
    summary: 'Elucidated the 3D double-helical structure of DNA with complementary base pairing, revealing the molecular mechanism for genetic replication.',
    simplifiedExplanation: 'DNA is shaped like a twisted ladder made of two strands that pair up with chemical bases (A-T and G-C).',
    scientificExplanation: 'B-DNA exists as two antiparallel polynucleotide chains held together by hydrogen bonds between complementary purine and pyrimidine bases (A pairs with T via 2 bonds; G pairs with C via 3 bonds) wrapped around a central axis.',
    impactScore: 100,
    milestoneOrder: 3,
    previousDiscoveryIds: ['disc_mendelian_genetics'],
    nextDiscoveryIds: ['disc_pcr_amplification'],
    paperIds: ['paper_dna_double_helix_1953', 'paper_franklin_dna_diffraction'],
    knowledgeGraphNodeIds: ['dna', 'double-helix', 'base-pairing'],
  },
  {
    id: 'disc_pcr_amplification',
    title: 'Invention of Polymerase Chain Reaction (PCR)',
    year: 1983,
    dateString: '1983',
    fieldId: 'genetics',
    topicIds: ['sequencing'],
    leadScientistIds: ['sci_kary_mullis'],
    institutionId: 'inst_coldspring',
    summary: 'Developed automated thermal cycling method to exponentially amplify targeted DNA sequences in vitro using DNA polymerase.',
    simplifiedExplanation: 'A molecular photocopy machine that turns one tiny sample of DNA into billions of exact copies in a few hours.',
    scientificExplanation: 'PCR relies on thermal cycling consisting of denaturation (95°C), primer annealing (55-65°C), and elongation (72°C) catalyzed by heat-stable Taq DNA polymerase, resulting in 2^n exponential DNA copy yields.',
    impactScore: 96,
    milestoneOrder: 4,
    previousDiscoveryIds: ['disc_dna_double_helix'],
    nextDiscoveryIds: ['disc_human_genome_project'],
    paperIds: ['paper_pcr_amplification'],
    knowledgeGraphNodeIds: ['pcr', 'dna-polymerase'],
  },
  {
    id: 'disc_human_genome_project',
    title: 'Completion of the Human Genome Project',
    year: 2003,
    dateString: 'April 14, 2003',
    fieldId: 'genetics',
    topicIds: ['sequencing'],
    leadScientistIds: [],
    institutionId: 'inst_broad',
    summary: 'Sequenced the complete ~3 billion base-pair human genome, mapping approximately 20,000 protein-coding genes.',
    simplifiedExplanation: 'Scientists read the entire genetic instruction book containing 3 billion letters that make up a human being.',
    scientificExplanation: 'International consortium decoded 99% of the euchromatic human genome at 99.99% accuracy using BAC-based Sanger sequencing, laying the foundation for modern comparative genomics and precision medicine.',
    impactScore: 99,
    milestoneOrder: 5,
    previousDiscoveryIds: ['disc_pcr_amplification'],
    nextDiscoveryIds: ['disc_crispr_editing'],
    paperIds: [],
    knowledgeGraphNodeIds: ['human-genome', 'dna-sequencing'],
  },
  {
    id: 'disc_crispr_editing',
    title: 'CRISPR-Cas9 Programmable Genome Editing',
    year: 2012,
    dateString: 'August 17, 2012',
    fieldId: 'genetics',
    topicIds: ['gene-editing'],
    leadScientistIds: ['sci_jennifer_doudna'],
    institutionId: 'inst_berkeley',
    summary: 'Reprogrammed bacterial Cas9 endonucleases with synthetic guide RNAs to perform site-specific double-strand breaks in living genomes.',
    simplifiedExplanation: 'A pair of microscopic molecular scissors that can find and rewrite specific genetic code errors inside living cells.',
    scientificExplanation: 'Cas9 is targeted by a single guide RNA (sgRNA) matching a 20-nucleotide genomic target sequence adjacent to a 5\'-NGG-3\' PAM sequence. Upon binding, RuvC and HNH nuclease domains induce a targeted double-strand break (DSB) resolved by NHEJ or HDR repair.',
    impactScore: 100,
    milestoneOrder: 6,
    previousDiscoveryIds: ['disc_human_genome_project'],
    nextDiscoveryIds: [],
    paperIds: ['paper_crispr_cas9_mammalian'],
    knowledgeGraphNodeIds: ['crispr', 'cas9', 'gene-editing'],
  },
];

export const RESEARCH_PAPERS: ResearchPaper[] = [
  {
    id: 'paper_crispr_cas9_mammalian',
    title: 'CRISPR-Cas9 Gene Editing in Mammalian Cells: Efficacy and Off-Target Mutations',
    abstract: 'CRISPR-Cas9 has revolutionized genomic editing. This paper investigates target cleavage efficiencies in mammalian cells, detailing biochemical techniques to optimize Cas9 binding and mitigate off-target cleavage by over 90%.',
    simplifiedExplanation: 'CRISPR acts like fine molecular scissors for DNA. By re-engineering the guide RNA sequence and Cas9 protein, scientists prevented accidental cuts at non-target genes.',
    scientificExplanation: 'We evaluated Cas9-mediated double-stranded breaks in HEK293T cells using targeted deep sequencing. High-fidelity Cas9 variants (Cas9-HF1) exhibited identical on-target cleavage yields while reducing off-target mutagenesis below detectability limits across 14 genome loci.',
    publicationDate: '2024-03-15',
    year: 2024,
    fieldId: 'genetics',
    topicIds: ['gene-editing'],
    authorIds: ['sci_jennifer_doudna'],
    institutionIds: ['inst_berkeley', 'inst_broad'],
    journalId: 'journal_science',
    doi: '10.1126/science.abc1234',
    pmid: '38491029',
    keywords: ['CRISPR', 'Cas9', 'Mammalian Genome', 'Off-target Cleavage', 'sgRNA Architecture'],
    readTimeMinutes: 8,
    citationCount: 420,
    isTrending: true,
    isFeatured: true,
    figures: [
      {
        id: 'fig_1',
        title: 'Figure 1: Cleavage Efficiency Comparison',
        caption: 'Comparison of wild-type Cas9 versus Cas9-HF1 across 8 genomic loci in human cells.',
        dataPoints: [
          { x: 'Locus A', y: 94, label: 'WT-Cas9' },
          { x: 'Locus A (HF)', y: 92, label: 'Cas9-HF1' },
          { x: 'Locus B', y: 88, label: 'WT-Cas9' },
          { x: 'Locus B (HF)', y: 87, label: 'Cas9-HF1' },
        ],
      },
    ],
    tables: [
      {
        id: 'table_1',
        title: 'Table 1: Off-Target Frequency Rate (%)',
        caption: 'Deep sequencing read counts for off-target locus cuts.',
        headers: ['Variant', 'On-Target Efficiency (%)', 'Off-Target Rate (%)', 'Fidelity Ratio'],
        rows: [
          ['WT Cas9', 92.4, 4.8, '19.25'],
          ['eSpCas9', 89.1, 0.6, '148.50'],
          ['Cas9-HF1', 91.8, 0.2, '459.00'],
        ],
      },
    ],
    references: [
      { paperId: 'paper_dna_double_helix_1953', citationText: 'Watson JD, Crick FH. (1953). Molecular structure of nucleic acids. Nature.' },
      { paperId: 'paper_pcr_amplification', citationText: 'Mullis K, et al. (1986). Specific enzymatic amplification of DNA. CSHL Symp.' },
    ],
    citedByPaperIds: ['paper_gut_microbiome_metabolism', 'paper_amyloid_beta_alzheimers'],
    relatedTopicIds: ['gene-editing', 'dna-replication'],
    relatedDiseaseIds: ['sickle-cell', 'cystic-fibrosis'],
    relatedAnatomyIds: ['cell-nucleus', 'chromosome'],
    relatedSimulationIds: ['dna-editor-sim'],
    relatedLabIds: ['crispr-lab'],
    relatedLessonIds: ['lesson-genetics-101'],
    knowledgeGraphNodeIds: ['crispr', 'cas9', 'dna'],
  },
  {
    id: 'paper_chemosynthesis_deepsea',
    title: 'Chemosynthetic Pathways in Deep-Sea Hydrothermal Vent Ecosystems',
    abstract: 'Hydrothermal vents support complex biological communities in the complete absence of sunlight. We trace primary productivity pathways driven by sulfur-oxidizing bacterial endosymbiosis.',
    simplifiedExplanation: 'Deep underwater where no sunlight reaches, ocean creatures live off geothermal chemicals emitting from black smokers instead of plants and sunlight.',
    scientificExplanation: 'Chemolithoautotrophic bacteria oxidize hydrogen sulfide (H2S) using oxygen or nitrate as electron acceptors, fixing inorganic CO2 via the Calvin-Benson cycle to nourish giant tube worms (Riftia pachyptila) inside the trophosome.',
    publicationDate: '2023-11-04',
    year: 2023,
    fieldId: 'ecology',
    topicIds: ['deep-sea-vents'],
    authorIds: [],
    institutionIds: ['inst_cambridge'],
    journalId: 'journal_nature',
    doi: '10.1038/s41586-023-09876',
    keywords: ['Chemosynthesis', 'Hydrothermal Vents', 'Riftia pachyptila', 'Hydrogen Sulfide', 'Trophosome'],
    readTimeMinutes: 6,
    citationCount: 185,
    isTrending: false,
    isFeatured: true,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: [],
    relatedTopicIds: ['deep-sea-vents'],
    relatedDiseaseIds: [],
    relatedAnatomyIds: ['mitochondria'],
    relatedSimulationIds: ['ecosystem-sim'],
    relatedLabIds: ['chemosynthesis-lab'],
    relatedLessonIds: ['lesson-ecology-201'],
    knowledgeGraphNodeIds: ['chemosynthesis', 'hydrothermal-vent'],
  },
  {
    id: 'paper_gut_microbiome_metabolism',
    title: 'Gut Microbiome Diversity and Its Regulation of Human Metabolic Homeostasis',
    abstract: 'This paper reviews how short-chain fatty acids (SCFAs) produced by intestinal bacterial fermentation regulate host insulin sensitivity, GLP-1 hormone secretion, and metabolic balance.',
    simplifiedExplanation: 'Friendly bacteria living in our gut digest fibers we cannot eat, producing health-promoting chemical signals (SCFAs) that keep blood sugar balanced.',
    scientificExplanation: 'Anaerobic fermentation of complex dietary non-digestible carbohydrates by Bacteroidetes yields short-chain fatty acids (acetate, propionate, butyrate). These act as ligands for G-protein coupled receptors GPR41/43, inducing GLP-1 secretion from intestinal L-cells.',
    publicationDate: '2023-09-20',
    year: 2023,
    fieldId: 'microbiology',
    topicIds: ['gut-microbiome'],
    authorIds: [],
    institutionIds: ['inst_broad'],
    journalId: 'journal_cell',
    doi: '10.1016/j.cell.2023.08.012',
    keywords: ['Gut Microbiome', 'SCFAs', 'Butyrate', 'GLP-1', 'Insulin Sensitivity'],
    readTimeMinutes: 7,
    citationCount: 290,
    isTrending: true,
    isFeatured: false,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: [],
    relatedTopicIds: ['gut-microbiome'],
    relatedDiseaseIds: ['diabetes-type2', 'obesity'],
    relatedAnatomyIds: ['gastrointestinal-tract'],
    relatedSimulationIds: ['microbiome-sim'],
    relatedLabIds: ['gut-lab'],
    relatedLessonIds: ['lesson-microbiology-101'],
    knowledgeGraphNodeIds: ['gut-microbiome', 'scfa'],
  },
  {
    id: 'paper_amyloid_beta_alzheimers',
    title: 'Pathophysiological Mechanisms of Amyloid-Beta Plaque Accumulation in Alzheimer\'s Disease',
    abstract: 'The accumulation of amyloid-beta plaques between cerebral neurons is a major hallmark of Alzheimer\'s disease. We review secretase processing pathways and hyperphosphorylated Tau neurofibrillary tangles.',
    simplifiedExplanation: 'Toxic protein clumps in the brain block nerve cells from talking to each other, leading to memory loss in Alzheimer\'s disease.',
    scientificExplanation: 'Sequential cleavage of Amyloid Precursor Protein (APP) by BACE1 and gamma-secretase generates hydrophobic A-beta-42 monomers that oligomerize into cytotoxic fibrillar plaques, triggering neuroinflammation and Tau protein hyperphosphorylation.',
    publicationDate: '2024-01-10',
    year: 2024,
    fieldId: 'neuroscience',
    topicIds: ['amyloid-plaques'],
    authorIds: [],
    institutionIds: ['inst_maxplanck'],
    journalId: 'journal_pnas',
    doi: '10.1073/pnas.2318901121',
    keywords: ['Alzheimers', 'Amyloid Beta', 'APP', 'Tau Tangles', 'BACE1'],
    readTimeMinutes: 9,
    citationCount: 310,
    isTrending: false,
    isFeatured: false,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: [],
    relatedTopicIds: ['amyloid-plaques'],
    relatedDiseaseIds: ['alzheimers-disease'],
    relatedAnatomyIds: ['brain', 'neuron'],
    relatedSimulationIds: ['neuron-sim'],
    relatedLabIds: ['neuro-lab'],
    relatedLessonIds: ['lesson-neuro-101'],
    knowledgeGraphNodeIds: ['amyloid-beta', 'alzheimers'],
  },
  {
    id: 'paper_dna_double_helix_1953',
    title: 'Molecular Structure of Nucleic Acids: A Structure for Deoxyribose Nucleic Acid',
    abstract: 'We wish to suggest a structure for the salt of deoxyribose nucleic acid (D.N.A.). This structure has two helical chains each coiled round the same axis.',
    simplifiedExplanation: 'The classic 1953 scientific paper that introduced the double helix structure of DNA to the world.',
    scientificExplanation: 'Demonstrated complementary hydrogen bonding between adenine-thymine and guanine-cytosine base pairs, satisfying Chargaff\'s rules and providing a self-evident copying mechanism for genetic material.',
    publicationDate: '1953-04-25',
    year: 1953,
    fieldId: 'genetics',
    topicIds: ['dna-replication'],
    authorIds: ['sci_watson_crick'],
    institutionIds: ['inst_cambridge'],
    journalId: 'journal_nature',
    doi: '10.1038/171737a0',
    keywords: ['DNA', 'Double Helix', 'Base Pairing', 'Nucleic Acids', 'X-ray Diffraction'],
    readTimeMinutes: 4,
    citationCount: 15400,
    isTrending: false,
    isFeatured: true,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: ['paper_crispr_cas9_mammalian', 'paper_pcr_amplification'],
    relatedTopicIds: ['dna-replication'],
    relatedDiseaseIds: [],
    relatedAnatomyIds: ['chromosome', 'cell-nucleus'],
    relatedSimulationIds: ['dna-viewer-3d'],
    relatedLabIds: ['dna-extraction-lab'],
    relatedLessonIds: ['lesson-dna-foundations'],
    knowledgeGraphNodeIds: ['dna', 'double-helix'],
  },
  {
    id: 'paper_franklin_dna_diffraction',
    title: 'Molecular Configuration in Sodium Thymonucleate',
    abstract: 'X-ray diffraction photograph of sodium thymonucleate structure B showing definitive coaxial double helical parameters with outer phosphate positioning.',
    simplifiedExplanation: 'Rosalind Franklin\'s landmark X-ray diffraction report proving DNA has a double helical spiral structure with its phosphate groups on the outside.',
    scientificExplanation: 'High-humidity X-ray diffraction patterns of fiber B-DNA exhibited characteristic X-pattern reflections at 3.4 Å layer lines with a 34 Å helical repeat pitch.',
    publicationDate: '1953-04-25',
    year: 1953,
    fieldId: 'biochemistry',
    topicIds: ['dna-replication'],
    authorIds: ['sci_rosalind_franklin'],
    institutionIds: ['inst_cambridge'],
    journalId: 'journal_nature',
    doi: '10.1038/171740a0',
    keywords: ['Photo 51', 'X-ray Crystallography', 'B-DNA', 'Phosphate Backbone'],
    readTimeMinutes: 5,
    citationCount: 8900,
    isTrending: false,
    isFeatured: false,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: ['paper_dna_double_helix_1953'],
    relatedTopicIds: ['dna-replication'],
    relatedDiseaseIds: [],
    relatedAnatomyIds: ['cell-nucleus'],
    relatedSimulationIds: ['xray-diffraction-sim'],
    relatedLabIds: ['crystallography-lab'],
    relatedLessonIds: ['lesson-dna-foundations'],
    knowledgeGraphNodeIds: ['photo-51', 'x-ray-diffraction'],
  },
  {
    id: 'paper_pcr_amplification',
    title: 'Specific Enzymatic Amplification of DNA In Vitro: The Polymerase Chain Reaction',
    abstract: 'Description of an automated thermostable DNA amplification procedure utilizing repeated cycles of denaturation, primer annealing, and extension by Thermus aquaticus polymerase.',
    simplifiedExplanation: 'The original paper introducing PCR thermal cycling technology to duplicate targeted DNA fragments.',
    scientificExplanation: 'Taq polymerase withstands repeated 95°C denaturation heat pulses without denaturation, allowing continuous automated multi-cycle DNA exponential doubling.',
    publicationDate: '1986-05-10',
    year: 1986,
    fieldId: 'genetics',
    topicIds: ['sequencing'],
    authorIds: ['sci_kary_mullis'],
    institutionIds: ['inst_coldspring'],
    journalId: 'journal_science',
    doi: '10.1126/science.230.4732.1350',
    keywords: ['PCR', 'Taq Polymerase', 'Thermal Cycling', 'DNA Amplification'],
    readTimeMinutes: 6,
    citationCount: 12100,
    isTrending: false,
    isFeatured: false,
    figures: [],
    tables: [],
    references: [],
    citedByPaperIds: ['paper_crispr_cas9_mammalian'],
    relatedTopicIds: ['sequencing'],
    relatedDiseaseIds: [],
    relatedAnatomyIds: ['cell-nucleus'],
    relatedSimulationIds: ['pcr-sim'],
    relatedLabIds: ['pcr-virtual-lab'],
    relatedLessonIds: ['lesson-pcr-mastery'],
    knowledgeGraphNodeIds: ['pcr', 'taq-polymerase'],
  },
];

export const DATASETS: Dataset[] = [
  {
    id: 'dataset_crispr_offtargets',
    title: 'Genome-Wide Cas9 Off-Target Cleavage Sequencing Data',
    description: 'High-throughput GUIDE-seq and deep sequencing read metrics comparing wild-type Cas9 against Cas9-HF1 across 14 human cell line genomic loci.',
    doi: '10.5061/dryad.crispr2024',
    format: 'CSV',
    fileSize: '48.2 MB',
    sampleCount: 14,
    headers: ['Locus_Name', 'Target_Sequence', 'WT_Reads', 'HF1_Reads', 'OffTarget_Match_Percent'],
    rowsPreview: [
      { Locus_Name: 'EMX1_site_1', Target_Sequence: 'GAGTCCGAGCAGAAGAAGAAGGG', WT_Reads: 14200, HF1_Reads: 13950, OffTarget_Match_Percent: 98.2 },
      { Locus_Name: 'FANCF_site_2', Target_Sequence: 'GGAATCCCTTCTGCAGCACCAGG', WT_Reads: 18900, HF1_Reads: 18420, OffTarget_Match_Percent: 97.5 },
      { Locus_Name: 'VEGFA_site_1', Target_Sequence: 'GGACCCAGGGAGGCAACAGTCGG', WT_Reads: 11500, HF1_Reads: 11280, OffTarget_Match_Percent: 98.1 },
      { Locus_Name: 'DNMT1_site_3', Target_Sequence: 'GATCCTGAAGCCTCCAACACAGG', WT_Reads: 16400, HF1_Reads: 16100, OffTarget_Match_Percent: 98.8 },
    ],
    relatedPaperId: 'paper_crispr_cas9_mammalian',
    keywords: ['CRISPR', 'Deep Sequencing', 'GUIDE-seq', 'Cas9-HF1'],
  },
  {
    id: 'dataset_gut_scfa_metabolomics',
    title: 'Human Gut Metagenomic SCFA Quantification Dataset',
    description: 'Concentrations of acetate, propionate, and butyrate (μmol/g stool) measured across 120 healthy adults under dietary fiber intervention.',
    doi: '10.5061/dryad.gutscfa2023',
    format: 'JSON',
    fileSize: '12.4 MB',
    sampleCount: 120,
    headers: ['Subject_ID', 'Diet_Group', 'Acetate_uMol', 'Propionate_uMol', 'Butyrate_uMol', 'GLP1_pg_mL'],
    rowsPreview: [
      { Subject_ID: 'SUBJ_001', Diet_Group: 'High-Fiber', Acetate_uMol: 64.2, Propionate_uMol: 22.4, Butyrate_uMol: 18.9, GLP1_pg_mL: 24.5 },
      { Subject_ID: 'SUBJ_002', Diet_Group: 'High-Fiber', Acetate_uMol: 58.7, Propionate_uMol: 20.1, Butyrate_uMol: 17.3, GLP1_pg_mL: 22.1 },
      { Subject_ID: 'SUBJ_003', Diet_Group: 'Control', Acetate_uMol: 38.1, Propionate_uMol: 12.5, Butyrate_uMol: 8.4, GLP1_pg_mL: 14.2 },
    ],
    relatedPaperId: 'paper_gut_microbiome_metabolism',
    keywords: ['Metabolomics', 'SCFAs', 'Gut Microbiome', 'GLP-1'],
  },
];

export const EXPERIMENTS: Experiment[] = [
  {
    id: 'exp_crispr_target_cleavage',
    title: 'Optimizing Guide RNA Length to Minimize Off-Target Cas9 Mutagenesis',
    objective: 'Investigate how shortening single guide RNA (sgRNA) target complementary lengths from 20 to 18 nucleotides affects Cas9 cleavage specificity.',
    fieldId: 'genetics',
    hypothesisTemplate: 'If the sgRNA length is reduced from 20 to 17-18 nucleotides, then off-target Cas9 cleavage will decrease significantly while maintaining on-target efficiency.',
    variables: [
      { id: 'v1', name: 'sgRNA Length (nucleotides)', type: 'independent', defaultValue: 20, description: 'Length of the target-matching region (17, 18, 19, or 20 nt).' },
      { id: 'v2', name: 'Off-Target Cleavage Rate (%)', type: 'dependent', description: 'Percentage of non-target genomic reads carrying indel mutations.' },
      { id: 'v3', name: 'Cas9 Concentration (nM)', type: 'controlled', defaultValue: 50, description: 'Kept constant across all electroporation trials.' },
      { id: 'v4', name: 'Incubation Time (hours)', type: 'controlled', defaultValue: 48, description: 'Cell culture harvesting timeframe.' },
    ],
    controls: [
      { id: 'c1', name: 'Non-targeting sgRNA (Scrambled)', type: 'negative', description: 'Rules out spontaneous non-specific background DNA breaks.' },
      { id: 'c2', name: 'Validated Wild-Type 20nt sgRNA', type: 'positive', description: 'Establishes baseline high on-target cleavage.' },
    ],
    procedureSteps: [
      { stepNumber: 1, title: 'Design sgRNA Constructs', instruction: 'Synthesize sgRNAs targeting EMX1 with 17, 18, 19, and 20 nt spacer lengths.', durationMinutes: 30 },
      { stepNumber: 2, title: 'Cell Electroporation', instruction: 'Deliver Cas9 protein-sgRNA ribonucleoprotein (RNP) complexes into HEK293T cells.', durationMinutes: 45, safetyNotes: 'Use sterile biosafety cabinet for cell handling.' },
      { stepNumber: 3, title: 'Genomic DNA Isolation', instruction: 'Harvest cells after 48h and extract genomic DNA using spin column protocol.', durationMinutes: 60 },
      { stepNumber: 4, title: 'Deep Sequencing & Analysis', instruction: 'Amplify target and predicted off-target loci for Illumina sequencing.', durationMinutes: 120 },
    ],
    expectedOutcome: 'Shortened 17-18 nt sgRNAs maintain >85% on-target cleavage while reducing off-target cutting by up to 500-fold due to lower binding free energy at mismatched loci.',
    relatedPaperId: 'paper_crispr_cas9_mammalian',
    relatedLabId: 'crispr-virtual-lab',
    difficulty: 'intermediate',
  },
  {
    id: 'exp_pcr_amplification',
    title: 'Optimizing MgCl2 Concentration in PCR Amplification Yields',
    objective: 'Determine the optimal magnesium ion concentration required for maximal Taq DNA Polymerase catalytic activity without non-specific priming.',
    fieldId: 'genetics',
    hypothesisTemplate: 'If MgCl2 concentration is maintained between 1.5 mM and 2.5 mM, then PCR product yield will peak with high specificity.',
    variables: [
      { id: 'v1', name: 'MgCl2 Concentration (mM)', type: 'independent', defaultValue: 1.5, description: 'Tested across 0.5, 1.0, 1.5, 2.5, 4.0 mM.' },
      { id: 'v2', name: 'DNA Yield (ng/μL)', type: 'dependent', description: 'Concentration of amplified target band measured by fluorometry.' },
      { id: 'v3', name: 'Annealing Temperature (°C)', type: 'controlled', defaultValue: 58, description: 'Kept constant during thermal cycling.' },
    ],
    controls: [
      { id: 'c1', name: 'No-Template Reaction (NTC)', type: 'negative', description: 'Checks for reagent contamination or primer dimers.' },
    ],
    procedureSteps: [
      { stepNumber: 1, title: 'Prepare Master Mixes', instruction: 'Assemble PCR reaction tubes with varying concentrations of MgCl2.', durationMinutes: 20 },
      { stepNumber: 2, title: 'Run Thermal Cycling', instruction: 'Program thermocycler for 30 cycles of (95°C 30s, 58°C 30s, 72°C 60s).', durationMinutes: 90 },
      { stepNumber: 3, title: 'Agarose Gel Electrophoresis', instruction: 'Load products on a 1.5% agarose gel to inspect band purity.', durationMinutes: 45 },
    ],
    expectedOutcome: '1.5 mM to 2.0 mM MgCl2 will yield a sharp single band of expected size; higher MgCl2 causes non-specific amplification bands.',
    relatedPaperId: 'paper_pcr_amplification',
    relatedLabId: 'pcr-lab',
    difficulty: 'beginner',
  },
];
