// ═══════════════════════════════════════════════════════════════
// Biosphere — Cell Organelle Knowledge Objects
// ═══════════════════════════════════════════════════════════════

import type { KnowledgeObject } from "@/knowledge-types/object";

export const CELL_ORGANELLE_OBJECTS: KnowledgeObject[] = [
  // ── Mitochondria ───────────────────────────────────────────
  {
    id: "mitochondria",
    name: "Mitochondria",
    scientificName: "Mitochondrion (singular)",
    category: "cell-biology",
    subcategory: "Organelles",
    icon: "mitochondria",
    accentColor: "#2FFFB0",
    description: "Mitochondria are double-membrane-bound organelles found in nearly all eukaryotic cells. Often called the 'powerhouse of the cell,' they generate most of the cell's supply of adenosine triphosphate (ATP) through oxidative phosphorylation.",
    difficulty: "beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain how mitochondria produce ATP", icon: "mitochondria" },
      { text: "Describe the structure of the inner and outer membranes", icon: "cell-explorer" },
      { text: "Understand why mitochondria have their own DNA", icon: "dna-genetics" },
      { text: "Relate mitochondrial dysfunction to human diseases", icon: "disease-explorer" },
    ],
    importantTerms: [
      { term: "ATP", definition: "Adenosine triphosphate — the primary energy currency of cells." },
      { term: "Cristae", definition: "Folds of the inner mitochondrial membrane that increase surface area for ATP production." },
      { term: "Matrix", definition: "The innermost compartment of the mitochondrion containing enzymes, mtDNA, and ribosomes." },
      { term: "Oxidative Phosphorylation", definition: "Process by which ATP is formed using the electron transport chain and chemiosmosis." },
      { term: "mtDNA", definition: "Mitochondrial DNA — a small circular genome inherited exclusively from the mother." },
      { term: "Endosymbiotic Theory", definition: "Theory that mitochondria evolved from an ancient alpha-proteobacterium engulfed by an ancestral eukaryotic cell." },
    ],
    summary: "Mitochondria are the energy factories of eukaryotic cells. They convert nutrients into ATP through cellular respiration. Their unique double-membrane structure features cristae that maximize ATP output. Mitochondria contain their own DNA and ribosomes, supporting the endosymbiotic theory of their ancient bacterial origin.",
    quickRevision: [
      "Mitochondria produce ~90% of the cell's ATP via oxidative phosphorylation.",
      "They have a double membrane — smooth outer, folded inner (cristae).",
      "The matrix contains mtDNA, ribosomes, and Krebs cycle enzymes.",
      "Mitochondrial DNA is inherited maternally.",
      "Mitochondrial dysfunction is linked to neurodegenerative diseases.",
    ],
    interestingFacts: [
      "A single liver cell can contain over 2,000 mitochondria!",
      "Mitochondria can fuse together and split apart depending on the cell's energy needs.",
      "The endosymbiotic theory suggests mitochondria were once free-living bacteria ~2 billion years ago.",
      "Mitochondrial Eve is the most recent common matrilineal ancestor of all living humans.",
    ],
    commonMisconceptions: [
      "Misconception: Mitochondria only produce energy. Reality: They also regulate calcium signaling, apoptosis (cell death), and heat production.",
      "Misconception: All cells have the same number of mitochondria. Reality: Muscle cells and neurons have thousands; red blood cells have none.",
    ],
    scientists: [
      { name: "Richard Altmann", contribution: "First identified mitochondria as cell organelles", year: "1890" },
      { name: "Carl Benda", contribution: "Coined the term 'mitochondria' from Greek (mitos = thread, chondros = grain)", year: "1898" },
      { name: "Lynn Margulis", contribution: "Championed the endosymbiotic theory of mitochondrial origin", year: "1967" },
      { name: "Peter Mitchell", contribution: "Nobel Prize for chemiosmotic hypothesis of ATP synthesis", year: "1978" },
    ],
    timeline: [
      { year: "~2 billion BCE", title: "Endosymbiosis", description: "An ancestral eukaryote engulfed an alpha-proteobacterium, beginning the evolution of mitochondria." },
      { year: "1890", title: "Discovery", description: "Richard Altmann described mitochondria as 'bioblasts' in living cells." },
      { year: "1898", title: "Naming", description: "Carl Benda coined the word 'mitochondria.'" },
      { year: "1961", title: "Chemiosmotic Hypothesis", description: "Peter Mitchell proposed that ATP synthesis is driven by a proton gradient." },
      { year: "1967", title: "Endosymbiotic Theory", description: "Lynn Margulis published the theory that mitochondria evolved from bacteria." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/cell-explorer/mitochondria", accentColor: "#2FFFB0", cameraPosition: [0, 1.5, 5] },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain the structure and function of mitochondria in detail, including the electron transport chain, cristae, mtDNA, and the endosymbiotic theory.",
    parentTopicId: "animal-cell",
    childTopicIds: [],
    relatedTopicIds: ["nucleus", "ribosome", "cell-membrane"],
    prerequisiteIds: [],
    nextTopicIds: ["nucleus", "cell-membrane"],
    relatedDiseaseIds: [],
    relatedSpeciesIds: [],
    relatedOrganIds: ["heart"],
    relatedCellIds: [],
    relatedSimulationIds: ["photosynthesis"],
    relatedResearchIds: [],
    clinicalImportance: "Mitochondrial dysfunction is implicated in Parkinson's disease, Alzheimer's disease, diabetes, cardiovascular disease, and inherited mitochondrial myopathies. Mitochondrial DNA mutations accumulate with age and are a key driver of cellular aging.",
    realWorldApplications: [
      "Forensic science uses mitochondrial DNA for identification when nuclear DNA is degraded.",
      "Mitochondrial replacement therapy ('three-parent IVF') prevents inherited mitochondrial diseases.",
      "Cancer research targets mitochondrial metabolism to starve tumor cells.",
    ],
    quiz: {
      id: "mitochondria-quiz",
      title: "Mitochondria Knowledge Check",
      questions: [
        { text: "What is the primary function of mitochondria?", options: ["Protein synthesis", "ATP production", "DNA replication", "Cell division"], answerIndex: 1, explanation: "Mitochondria generate ATP through oxidative phosphorylation — they are the cell's powerhouse." },
        { text: "What are cristae?", options: ["Outer membrane proteins", "Inner membrane folds", "Matrix enzymes", "Mitochondrial ribosomes"], answerIndex: 1, explanation: "Cristae are folds of the inner mitochondrial membrane that increase the surface area for ATP production." },
        { text: "Who proposed the endosymbiotic theory?", options: ["Peter Mitchell", "Richard Altmann", "Lynn Margulis", "Carl Benda"], answerIndex: 2, explanation: "Lynn Margulis published the endosymbiotic theory in 1967, proposing that mitochondria evolved from bacteria." },
        { text: "How is mitochondrial DNA inherited?", options: ["From both parents", "Maternally only", "Paternally only", "Randomly"], answerIndex: 1, explanation: "mtDNA is inherited exclusively from the mother through the egg cell's cytoplasm." },
      ],
    },
    flashcards: [
      { id: "mito-fc-1", front: "What is the 'powerhouse of the cell'?", back: "Mitochondria — they produce ATP through oxidative phosphorylation and the electron transport chain.", category: "Cell Organelles" },
      { id: "mito-fc-2", front: "What are cristae?", back: "Folds of the inner mitochondrial membrane that dramatically increase the surface area available for ATP synthesis.", category: "Structure" },
      { id: "mito-fc-3", front: "What is mitochondrial DNA (mtDNA)?", back: "A small, circular genome (~16,500 base pairs) inside the mitochondrial matrix, encoding 37 genes. Inherited maternally.", category: "Genetics" },
      { id: "mito-fc-4", front: "What is the endosymbiotic theory?", back: "The theory that mitochondria originated ~2 billion years ago when an ancestral eukaryote engulfed an alpha-proteobacterium, which became a permanent symbiont.", category: "Evolution" },
    ],
    revisionNotes: {
      importantPoints: [
        "Mitochondria produce ~90% of ATP via oxidative phosphorylation.",
        "Double membrane: smooth outer + folded inner (cristae).",
        "Matrix contains mtDNA, ribosomes, and Krebs cycle enzymes.",
        "mtDNA is circular, maternally inherited, and encodes 37 genes.",
        "Endosymbiotic theory: mitochondria evolved from bacteria ~2 billion years ago.",
      ],
      keyTerms: [
        { term: "ATP", definition: "Adenosine triphosphate — the cell's energy currency." },
        { term: "Cristae", definition: "Inner membrane folds that increase ATP production surface area." },
        { term: "mtDNA", definition: "Circular mitochondrial genome inherited maternally." },
        { term: "Oxidative Phosphorylation", definition: "ATP production using electron transport and chemiosmosis." },
      ],
      summary: "Mitochondria are double-membrane organelles that produce ATP. Their inner membrane folds (cristae) house the electron transport chain. They contain their own DNA (mtDNA), supporting the endosymbiotic theory that they evolved from ancient bacteria.",
    },
    xpPoints: 150,
    achievementBadge: { id: "powerhouse-master", title: "Powerhouse Master", description: "Mastered the structure and function of mitochondria", icon: "mitochondria", xpReward: 150 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Campbell Biology, 12th ed., Chapter 9", "Alberts et al., Molecular Biology of the Cell, 6th ed.", "Margulis L. (1967) On the origin of mitosing cells. J Theor Biol."],
    furtherReading: ["Nick Lane — Power, Sex, Suicide: Mitochondria and the Meaning of Life", "Wallace DC (2005) A Mitochondrial Paradigm of Metabolic and Degenerative Diseases. Science."],
    existingRoute: "/cell-explorer/mitochondria",
  },

  // ── Nucleus ────────────────────────────────────────────────
  {
    id: "nucleus",
    name: "Nucleus",
    scientificName: "Nucleus cellulae",
    category: "cell-biology",
    subcategory: "Organelles",
    icon: "nucleus",
    accentColor: "#FF6B9D",
    description: "The nucleus is the membrane-bound organelle that contains the cell's genetic material (DNA). It serves as the command center of the cell, controlling gene expression, DNA replication, and cell division.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe the structure of the nuclear envelope", icon: "cell-explorer" },
      { text: "Explain the role of the nucleolus in ribosome production", icon: "ribosome" },
      { text: "Understand chromatin vs chromosome organization", icon: "dna-genetics" },
    ],
    importantTerms: [
      { term: "Nuclear Envelope", definition: "Double membrane surrounding the nucleus with nuclear pore complexes for transport." },
      { term: "Chromatin", definition: "DNA-protein complex; loosely coiled during interphase, condensed into chromosomes during division." },
      { term: "Nucleolus", definition: "Dense region within the nucleus where ribosomal RNA (rRNA) is synthesized." },
      { term: "Nuclear Pore", definition: "Channel in the nuclear envelope that regulates movement of molecules between nucleus and cytoplasm." },
    ],
    summary: "The nucleus is the control center of eukaryotic cells. It houses DNA organized as chromatin, contains the nucleolus for ribosome assembly, and is enclosed by a double-membrane nuclear envelope perforated with nuclear pores.",
    quickRevision: [
      "The nucleus houses nearly all of the cell's DNA.",
      "The nuclear envelope is a double membrane with pore complexes.",
      "The nucleolus produces ribosomal RNA (rRNA).",
      "Chromatin condenses into visible chromosomes during cell division.",
    ],
    interestingFacts: [
      "Red blood cells in mammals lose their nucleus during maturation to make room for more hemoglobin!",
      "The nuclear envelope breaks down during mitosis and reforms in daughter cells.",
      "A single human cell nucleus contains ~2 meters of DNA tightly coiled around histone proteins.",
    ],
    commonMisconceptions: [
      "Misconception: All cells have a nucleus. Reality: Prokaryotes lack a nucleus, and mature red blood cells lose theirs.",
      "Misconception: DNA is always in chromosome form. Reality: DNA exists as loose chromatin most of the time; it only condenses into chromosomes during division.",
    ],
    scientists: [
      { name: "Robert Brown", contribution: "First described the cell nucleus in orchid cells", year: "1831" },
      { name: "Walther Flemming", contribution: "Discovered chromatin and described mitosis", year: "1882" },
    ],
    timeline: [
      { year: "1831", title: "Discovery", description: "Robert Brown identified the nucleus as a fundamental cell component." },
      { year: "1882", title: "Chromatin", description: "Walther Flemming described chromatin and the stages of mitosis." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/cell-explorer/nucleus", accentColor: "#FF6B9D", cameraPosition: [0, 1, 4] },
    askAiPrompt: "Explain the structure and function of the cell nucleus, including the nuclear envelope, nucleolus, chromatin, and nuclear pores.",
    parentTopicId: "animal-cell",
    childTopicIds: [],
    relatedTopicIds: ["mitochondria", "ribosome", "dna-replication"],
    prerequisiteIds: [],
    nextTopicIds: ["dna-replication", "ribosome"],
    relatedDiseaseIds: [],
    relatedSpeciesIds: [],
    relatedOrganIds: [],
    relatedCellIds: [],
    relatedSimulationIds: [],
    relatedResearchIds: [],
    clinicalImportance: "Nuclear abnormalities are hallmarks of cancer. Pathologists examine nuclear morphology to grade tumors. Nuclear envelope defects cause laminopathies including progeria (premature aging).",
    realWorldApplications: [
      "Cancer diagnosis relies on examining nuclear size, shape, and chromatin patterns.",
      "Gene therapy delivers corrective DNA directly into the nucleus.",
    ],
    quiz: {
      id: "nucleus-quiz",
      title: "Nucleus Knowledge Check",
      questions: [
        { text: "What is the primary function of the cell nucleus?", options: ["Energy production", "Protein synthesis", "Storing and expressing genetic information", "Lipid metabolism"], answerIndex: 2, explanation: "The nucleus stores DNA and controls gene expression." },
        { text: "What does the nucleolus produce?", options: ["mRNA", "ATP", "Ribosomal RNA", "Lipids"], answerIndex: 2, explanation: "The nucleolus synthesizes ribosomal RNA (rRNA) for ribosome assembly." },
      ],
    },
    flashcards: [
      { id: "nuc-fc-1", front: "What is the function of the nucleus?", back: "The nucleus is the control center of the cell — it stores DNA and regulates gene expression.", category: "Organelles" },
      { id: "nuc-fc-2", front: "What is chromatin?", back: "A complex of DNA and histone proteins; loosely organized during interphase, condensed into chromosomes during division.", category: "Structure" },
      { id: "nuc-fc-3", front: "What is the nucleolus?", back: "A dense structure inside the nucleus where ribosomal RNA (rRNA) is produced and ribosome subunits are assembled.", category: "Organelles" },
    ],
    revisionNotes: {
      importantPoints: [
        "The nucleus houses nearly all of the cell's DNA.",
        "Nuclear envelope = double membrane + nuclear pores.",
        "Nucleolus = site of rRNA synthesis and ribosome assembly.",
        "Chromatin ↔ chromosomes (loose vs. condensed DNA).",
      ],
      keyTerms: [
        { term: "Chromatin", definition: "DNA-histone complex in the nucleus." },
        { term: "Nuclear Envelope", definition: "Double membrane enclosing the nucleus." },
        { term: "Nucleolus", definition: "Ribosomal RNA synthesis site within the nucleus." },
      ],
      summary: "The nucleus is the eukaryotic cell's command center. It contains DNA (as chromatin), the nucleolus (rRNA factory), and is enclosed by a double membrane with nuclear pores.",
    },
    xpPoints: 120,
    verification: { status: "published", version: "1.0.0" },
    references: ["Campbell Biology, Chapter 6", "Alberts et al., Molecular Biology of the Cell"],
    furtherReading: ["Lodish et al., Molecular Cell Biology"],
    existingRoute: "/cell-explorer/nucleus",
  },

  // ── Cell Membrane ──────────────────────────────────────────
  {
    id: "cell-membrane",
    name: "Cell Membrane",
    scientificName: "Plasma Membrane",
    category: "cell-biology",
    subcategory: "Organelles",
    icon: "membrane",
    accentColor: "#4ECDC4",
    description: "The cell membrane (plasma membrane) is a selectively permeable lipid bilayer that forms the boundary of all cells. It controls the movement of substances in and out of the cell and is essential for maintaining cellular homeostasis.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe the fluid mosaic model of the cell membrane", icon: "cell-explorer" },
      { text: "Explain the roles of phospholipids, proteins, and cholesterol", icon: "virtual-lab" },
      { text: "Distinguish passive from active membrane transport", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Phospholipid Bilayer", definition: "Two layers of phospholipid molecules forming the basic structure of the membrane." },
      { term: "Fluid Mosaic Model", definition: "Model describing the membrane as a dynamic structure with proteins floating in a fluid lipid bilayer." },
      { term: "Selective Permeability", definition: "The membrane's ability to allow some substances to pass while blocking others." },
      { term: "Integral Proteins", definition: "Proteins embedded within the lipid bilayer, spanning partially or completely through it." },
    ],
    summary: "The cell membrane is a flexible phospholipid bilayer studded with proteins, cholesterol, and carbohydrates. It regulates what enters and exits the cell via passive and active transport mechanisms.",
    quickRevision: [
      "The membrane is a phospholipid bilayer (hydrophilic heads out, hydrophobic tails in).",
      "The fluid mosaic model describes membrane dynamics.",
      "Integral proteins span the membrane; peripheral proteins attach to the surface.",
      "Transport: passive (diffusion, osmosis) vs. active (ATP-dependent pumps).",
    ],
    interestingFacts: [
      "The cell membrane is only ~7-8 nanometers thick — about 10,000 times thinner than a sheet of paper!",
      "Cholesterol in the membrane acts like a fluidity buffer, preventing the membrane from becoming too rigid or too fluid.",
    ],
    commonMisconceptions: [
      "Misconception: The cell membrane is a rigid wall. Reality: It's a dynamic, fluid structure where proteins and lipids constantly move laterally.",
    ],
    scientists: [
      { name: "S.J. Singer & G. Nicolson", contribution: "Proposed the fluid mosaic model", year: "1972" },
    ],
    timeline: [
      { year: "1972", title: "Fluid Mosaic Model", description: "Singer and Nicolson proposed that the membrane is a mosaic of proteins in a fluid lipid bilayer." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/cell-explorer/membrane", accentColor: "#4ECDC4", cameraPosition: [0, 1, 5] },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain the structure and functions of the cell membrane, including the fluid mosaic model, phospholipid bilayer, and transport mechanisms.",
    parentTopicId: "animal-cell",
    childTopicIds: [],
    relatedTopicIds: ["mitochondria", "nucleus"],
    prerequisiteIds: [],
    nextTopicIds: ["mitochondria"],
    relatedDiseaseIds: [],
    relatedSpeciesIds: [],
    relatedOrganIds: [],
    relatedCellIds: [],
    relatedSimulationIds: [],
    relatedResearchIds: [],
    clinicalImportance: "Cystic fibrosis is caused by a defective membrane transport protein (CFTR). Many drugs work by targeting membrane receptors.",
    realWorldApplications: [
      "Drug delivery systems mimic cell membranes using liposomes.",
      "Understanding membrane receptors is key to developing targeted cancer therapies.",
    ],
    quiz: {
      id: "membrane-quiz",
      title: "Cell Membrane Quiz",
      questions: [
        { text: "What model describes the structure of the cell membrane?", options: ["Lock and Key Model", "Fluid Mosaic Model", "Double Helix Model", "Central Dogma"], answerIndex: 1, explanation: "The fluid mosaic model describes the membrane as proteins floating in a fluid lipid bilayer." },
        { text: "What makes up the bulk of the cell membrane?", options: ["Carbohydrates", "Proteins", "Phospholipids", "Cholesterol"], answerIndex: 2, explanation: "The phospholipid bilayer forms the fundamental structure of the cell membrane." },
      ],
    },
    flashcards: [
      { id: "mem-fc-1", front: "What is the fluid mosaic model?", back: "A model describing the cell membrane as a dynamic structure with proteins floating in a fluid phospholipid bilayer.", category: "Cell Structure" },
      { id: "mem-fc-2", front: "What is selective permeability?", back: "The membrane's ability to allow certain molecules to pass while blocking others based on size, charge, and polarity.", category: "Transport" },
    ],
    revisionNotes: {
      importantPoints: [
        "Membrane = phospholipid bilayer + proteins + cholesterol + carbohydrates.",
        "Fluid mosaic model: dynamic structure with lateral movement.",
        "Selective permeability controls substance exchange.",
      ],
      keyTerms: [
        { term: "Phospholipid", definition: "Molecule with hydrophilic head and hydrophobic tails forming the bilayer." },
        { term: "Fluid Mosaic Model", definition: "Dynamic membrane model proposed by Singer & Nicolson (1972)." },
      ],
      summary: "The cell membrane is a selectively permeable phospholipid bilayer embedded with proteins. The fluid mosaic model describes its dynamic nature.",
    },
    xpPoints: 100,
    verification: { status: "published", version: "1.0.0" },
    references: ["Campbell Biology, Chapter 7", "Singer SJ, Nicolson GL (1972) Science 175:720-731."],
    furtherReading: [],
    existingRoute: "/cell-explorer/membrane",
  },

  // ── Ribosome ───────────────────────────────────────────────
  {
    id: "ribosome",
    name: "Ribosome",
    scientificName: "Ribosome",
    category: "cell-biology",
    subcategory: "Organelles",
    icon: "ribosome",
    accentColor: "#FFD93D",
    description: "Ribosomes are molecular machines that synthesize proteins by translating messenger RNA (mRNA) into amino acid chains. They are found free in the cytoplasm or bound to the rough endoplasmic reticulum.",
    difficulty: "beginner",
    estimatedMinutes: 8,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain how ribosomes translate mRNA into proteins", icon: "ribosome" },
      { text: "Distinguish between free and bound ribosomes", icon: "cell-explorer" },
      { text: "Compare prokaryotic and eukaryotic ribosomes", icon: "microorganisms" },
    ],
    importantTerms: [
      { term: "Translation", definition: "The process of synthesizing a protein from an mRNA template on a ribosome." },
      { term: "Large Subunit", definition: "The ribosomal subunit that catalyzes peptide bond formation (60S in eukaryotes)." },
      { term: "Small Subunit", definition: "The ribosomal subunit that reads mRNA codons (40S in eukaryotes)." },
      { term: "Polyribosome", definition: "Multiple ribosomes translating a single mRNA strand simultaneously." },
    ],
    summary: "Ribosomes are the protein factories of the cell. Composed of two subunits (large + small), they read mRNA and assemble amino acids into polypeptide chains. They exist free in the cytoplasm or bound to the rough ER.",
    quickRevision: [
      "Ribosomes translate mRNA into proteins (translation).",
      "Two subunits: large (peptide bonding) + small (mRNA reading).",
      "Free ribosomes → cytoplasmic proteins; bound → secreted/membrane proteins.",
      "Eukaryotic: 80S (60S + 40S). Prokaryotic: 70S (50S + 30S).",
    ],
    interestingFacts: [
      "A single bacterial cell may contain 10,000 ribosomes — constituting 25% of the cell's total mass!",
      "Antibiotics like tetracycline and erythromycin target bacterial ribosomes (70S) without affecting human ribosomes (80S).",
    ],
    commonMisconceptions: [
      "Misconception: Ribosomes are membrane-bound organelles. Reality: Ribosomes are NOT surrounded by a membrane — they are macromolecular complexes of RNA and protein.",
    ],
    scientists: [
      { name: "George Palade", contribution: "Discovered ribosomes using electron microscopy", year: "1955" },
      { name: "Venkatraman Ramakrishnan", contribution: "Nobel Prize for determining atomic structure of the ribosome", year: "2009" },
    ],
    timeline: [
      { year: "1955", title: "Discovery", description: "George Palade visualized ribosomes using electron microscopy." },
      { year: "2009", title: "Atomic Structure", description: "Nobel Prize awarded for solving the 3D atomic structure of the ribosome." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/cell-explorer/ribosome", accentColor: "#FFD93D", cameraPosition: [0, 1, 4] },
    askAiPrompt: "Explain the structure and function of ribosomes, including translation, subunit composition, and the difference between free and bound ribosomes.",
    parentTopicId: "animal-cell",
    childTopicIds: [],
    relatedTopicIds: ["nucleus", "dna-replication"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: [],
    relatedSpeciesIds: [],
    relatedOrganIds: [],
    relatedCellIds: [],
    relatedSimulationIds: [],
    relatedResearchIds: [],
    clinicalImportance: "Many antibiotics work by targeting bacterial ribosomes (70S), exploiting the structural differences from human ribosomes (80S) to selectively kill bacteria.",
    realWorldApplications: [
      "Antibiotic drug design targets prokaryotic ribosome structure.",
      "mRNA vaccines (COVID-19) rely on ribosomes to translate the injected mRNA into spike protein.",
    ],
    flashcards: [
      { id: "rib-fc-1", front: "What do ribosomes do?", back: "Ribosomes translate mRNA into proteins through the process of translation.", category: "Organelles" },
      { id: "rib-fc-2", front: "How do eukaryotic and prokaryotic ribosomes differ?", back: "Eukaryotic ribosomes are 80S (60S + 40S); prokaryotic are 70S (50S + 30S). Antibiotics exploit this difference.", category: "Comparison" },
    ],
    revisionNotes: {
      importantPoints: [
        "Ribosomes = protein synthesis machinery (translation).",
        "Two subunits: large + small.",
        "Free ribosomes make cytoplasmic proteins; bound ribosomes make secreted/membrane proteins.",
        "Eukaryotic 80S vs prokaryotic 70S — basis for antibiotic selectivity.",
      ],
      keyTerms: [
        { term: "Translation", definition: "mRNA → protein on a ribosome." },
        { term: "Polyribosome", definition: "Multiple ribosomes on one mRNA strand." },
      ],
      summary: "Ribosomes are RNA-protein machines that translate mRNA into proteins. They consist of two subunits and exist free or bound to the rough ER.",
    },
    xpPoints: 100,
    verification: { status: "published", version: "1.0.0" },
    references: ["Campbell Biology, Chapter 17", "Ramakrishnan V (2009) Nobel Lecture."],
    furtherReading: [],
    existingRoute: "/cell-explorer/ribosome",
  },
];
