// ═══════════════════════════════════════════════════════════════
// Biosphere — Human Anatomy Knowledge Objects (12 Systems)
// ═══════════════════════════════════════════════════════════════

import type { KnowledgeObject } from "@/knowledge-types/object";

export const HUMAN_ANATOMY_OBJECTS: KnowledgeObject[] = [
  {
    id: "heart",
    name: "Heart",
    scientificName: "Cor",
    category: "human-anatomy",
    subcategory: "Cardiovascular System",
    icon: "human-body",
    accentColor: "#FF4757",
    description: "The heart is a muscular four-chambered pump driving systemic and pulmonary blood circulation. It beats ~100,000 times daily, delivering oxygenated blood to body tissues and returning deoxygenated blood to the lungs.",
    difficulty: "intermediate",
    estimatedMinutes: 15,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe the four chambers of the heart", icon: "human-body" },
      { text: "Trace the path of blood through pulmonary and systemic loops", icon: "process-simulations" },
      { text: "Explain the cardiac cycle and SA node conduction", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Atrium", definition: "Upper receiving chambers of the heart." },
      { term: "Ventricle", definition: "Lower muscular pumping chambers." },
      { term: "Sinoatrial (SA) Node", definition: "Natural cardiac pacemaker generating electrical impulses." },
      { term: "Cardiac Cycle", definition: "Complete phase of contraction (systole) and relaxation (diastole)." },
      { term: "Coronary Arteries", definition: "Arteries supplying oxygen-rich blood to myocardium." },
    ],
    summary: "The heart is a 4-chambered pump (2 atria, 2 ventricles). The right side pumps deoxygenated blood to lungs; the left side pumps oxygenated blood to the body. Governed by the SA node.",
    quickRevision: [
      "Four chambers: RA, RV, LA, LV.",
      "Pulmonary circuit (right) vs. Systemic circuit (left).",
      "Conduction: SA node → AV node → Bundle of His → Purkinje fibers.",
      "Cardiac Output = Stroke Volume × Heart Rate.",
    ],
    interestingFacts: [
      "The heart pumps ~7,500 liters of blood every single day!",
      "Left ventricle wall is 3x thicker than right due to high systemic pressure demands.",
    ],
    commonMisconceptions: [
      "Misconception: Heart is on far left. Reality: Sits in mediastinum center, tilted slightly left.",
      "Misconception: Deoxygenated blood is blue. Reality: It is dark maroon red.",
    ],
    scientists: [
      { name: "William Harvey", contribution: "Discovered complete blood circulation", year: "1628" },
      { name: "Christiaan Barnard", contribution: "First human heart transplant", year: "1967" },
    ],
    timeline: [
      { year: "1628", title: "Circulation Described", description: "William Harvey published 'De Motu Cordis'." },
      { year: "1967", title: "First Heart Transplant", description: "Performed by Dr. Christiaan Barnard." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#FF4757" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain heart anatomy, chambers, cardiac cycle, and coronary circulation.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["lungs", "kidneys", "blood-vessels"],
    prerequisiteIds: [],
    nextTopicIds: ["lungs"],
    relatedDiseaseIds: ["cad", "myocardial-infarction", "arrhythmia"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["lungs", "kidneys"],
    relatedCellIds: ["cardiomyocyte"],
    relatedSimulationIds: ["cardiac-cycle-sim"],
    relatedVirtualLabIds: ["ecg-lab"],
    relatedResearchIds: ["cardiac-regeneration-paper"],
    clinicalImportance: "Coronary artery disease and heart failure are leading causes of mortality worldwide.",
    realWorldApplications: [
      "ECG diagnostics",
      "Artificial pacemaker implantation",
      "Coronary artery bypass grafting (CABG)",
    ],
    quiz: {
      id: "heart-quiz",
      title: "Heart Anatomy Quiz",
      questions: [
        { text: "Which chamber pumps blood to the lungs?", options: ["Left Atrium", "Right Ventricle", "Left Ventricle", "Right Atrium"], answerIndex: 1, explanation: "Right ventricle pumps deoxygenated blood to lungs via pulmonary artery." },
        { text: "What is the primary cardiac pacemaker?", options: ["AV Node", "SA Node", "Purkinje Fibers", "Bundle of His"], answerIndex: 1, explanation: "Sinoatrial (SA) node initiates electrical impulses." },
      ],
    },
    flashcards: [
      { id: "fc-heart-1", front: "What does the SA node do?", back: "Acts as the natural pacemaker generating rhythmic impulses.", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Four chambers", "Double circulation loop", "SA node pacemaker"],
      keyTerms: [{ term: "Systole", definition: "Contraction phase." }],
      summary: "Heart pumps blood continuously to maintain systemic cellular respiration.",
    },
    xpPoints: 200,
    achievementBadge: { id: "cardiac-master", title: "Cardiac Scholar", description: "Mastered cardiac anatomy", icon: "human-body", xpReward: 200 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Gray's Anatomy 42nd ed."],
    furtherReading: ["Guyton and Hall Physiology"],
    existingRoute: "/human-body",
  },
  {
    id: "brain",
    name: "Brain",
    scientificName: "Cerebrum",
    category: "human-anatomy",
    subcategory: "Nervous System",
    icon: "human-body",
    accentColor: "#E879F9",
    description: "The brain is the command center of the central nervous system, integrating sensory data, directing motor function, and hosting conscious thought, emotion, and memory.",
    difficulty: "advanced",
    estimatedMinutes: 20,
    prerequisites: [],
    learningObjectives: [
      { text: "Identify cerebral lobes and cerebellum functions", icon: "human-body" },
      { text: "Explain synaptic neurotransmission and action potentials", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Cerebral Cortex", definition: "Outer layer of neural tissue responsible for high-level cognition." },
      { term: "Synapse", definition: "Junction between two neurons transmitting chemical or electrical signals." },
      { term: "Brainstem", definition: "Controls fundamental autonomic functions like breathing and heart rate." },
    ],
    summary: "The brain consists of the cerebrum, cerebellum, and brainstem. It contains ~86 billion neurons and consumes 20% of body energy.",
    quickRevision: [
      "Lobes: Frontal (executive), Parietal (sensory), Temporal (auditory/memory), Occipital (vision).",
      "Cerebellum: Motor coordination & balance.",
      "Brainstem: Autonomic homeostasis (medulla, pons).",
    ],
    interestingFacts: [
      "Action potentials travel down myelinated axons at up to 268 mph!",
      "The human brain contains roughly 86 billion neurons.",
    ],
    commonMisconceptions: [
      "Misconception: We only use 10% of our brain. Reality: Virtually all brain regions are active 24/7.",
    ],
    scientists: [
      { name: "Santiago Ramón y Cajal", contribution: "Pioneered neuron doctrine and neuroanatomy", year: "1906 Nobel" },
    ],
    timeline: [
      { year: "1906", title: "Neuron Doctrine", description: "Cajal demonstrated that neurons are discrete individual cells." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#E879F9" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain brain anatomy, cerebral lobes, neuroplasticity, and synaptic transmission.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["spinal-cord", "eyes", "ears"],
    prerequisiteIds: [],
    nextTopicIds: ["spinal-cord"],
    relatedDiseaseIds: ["alzheimers", "stroke", "epilepsy"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["spinal-cord", "eyes"],
    relatedCellIds: ["neuron", "astrocyte"],
    relatedSimulationIds: ["action-potential-sim"],
    relatedVirtualLabIds: ["neuro-lab"],
    relatedResearchIds: ["neuroplasticity-research"],
    clinicalImportance: "Neurological disorders represent major medical challenges including stroke, neurodegeneration, and traumatic brain injury.",
    realWorldApplications: [
      "Electroencephalography (EEG)",
      "Functional MRI (fMRI)",
      "Brain-computer interfaces (BCIs)",
    ],
    quiz: {
      id: "brain-quiz",
      title: "Brain Anatomy Quiz",
      questions: [
        { text: "Which lobe processes visual information?", options: ["Frontal", "Parietal", "Temporal", "Occipital"], answerIndex: 3, explanation: "Occipital lobe houses primary visual cortex." },
      ],
    },
    flashcards: [
      { id: "fc-brain-1", front: "What does the cerebellum control?", back: "Motor precision, balance, and spatial coordination.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["86B neurons", "Four cerebral lobes", "Brainstem controls vitals"],
      keyTerms: [{ term: "Neuron", definition: "Functional cell unit of nervous system." }],
      summary: "The brain processes all internal and external stimuli to guide behavior.",
    },
    xpPoints: 220,
    achievementBadge: { id: "neuro-master", title: "Neuroscience Scholar", description: "Mastered neuroanatomy", icon: "human-body", xpReward: 220 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Kandel's Principles of Neural Science"],
    furtherReading: ["Neuroscience 6th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "lungs",
    name: "Lungs",
    scientificName: "Pulmones",
    category: "human-anatomy",
    subcategory: "Respiratory System",
    icon: "human-body",
    accentColor: "#F472B6",
    description: "The lungs are essential paired respiratory organs that exchange oxygen from inhaled air into the bloodstream while expelling carbon dioxide waste.",
    difficulty: "intermediate",
    estimatedMinutes: 15,
    prerequisites: [],
    learningObjectives: [
      { text: "Trace airflow from trachea to alveoli", icon: "human-body" },
      { text: "Explain alveolar gas diffusion and hemoglobin binding", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Alveoli", definition: "Microscopic air sacs where gas exchange occurs across capillaries." },
      { term: "Diaphragm", definition: "Primary muscle of respiration separating thoracic and abdominal cavities." },
      { term: "Surfactant", definition: "Lipoprotein fluid reducing alveolar surface tension to prevent collapse." },
    ],
    summary: "Right lung has 3 lobes; left lung has 2 lobes. Contains ~480 million alveoli delivering gas exchange over a 70 m² surface area.",
    quickRevision: [
      "Inspiration: Diaphragm contracts downwards → negative thoracic pressure.",
      "Gas exchange: O2 diffuses into blood, CO2 diffuses into alveoli.",
      "Left lung features cardiac notch to house the heart.",
    ],
    interestingFacts: [
      "Total surface area of human alveoli equals roughly half a tennis court!",
    ],
    commonMisconceptions: [
      "Misconception: Lungs expand because air is blown into them. Reality: Atmospheric pressure fills lungs when chest volume increases.",
    ],
    scientists: [
      { name: "John Haldane", contribution: "Discovered carbon dioxide regulation of breathing", year: "1905" },
    ],
    timeline: [
      { year: "1905", title: "Respiration Control", description: "Haldane demonstrated CO2 drive in respiratory rhythm." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#F472B6" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain lung mechanics, ventilation, alveolar gas exchange, and surfactant function.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["heart", "trachea"],
    prerequisiteIds: [],
    nextTopicIds: ["heart"],
    relatedDiseaseIds: ["pneumonia", "asthma", "copd"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["heart"],
    relatedCellIds: ["pneumocyte"],
    relatedSimulationIds: ["respiration-sim"],
    relatedVirtualLabIds: ["spirometry-lab"],
    relatedResearchIds: ["pulmonary-fibrosis-study"],
    clinicalImportance: "Pulmonary conditions like asthma, pneumonia, and COPD are major worldwide health issues.",
    realWorldApplications: ["Spirometry lung function testing", "Mechanical ventilation in ICUs"],
    quiz: {
      id: "lungs-quiz",
      title: "Lungs Quiz",
      questions: [
        { text: "Where does gas exchange occur?", options: ["Trachea", "Bronchi", "Alveoli", "Pleura"], answerIndex: 2, explanation: "Alveoli are microscopic sacs wrapped in capillaries for gas diffusion." },
      ],
    },
    flashcards: [
      { id: "fc-lungs-1", front: "How many lobes does the right lung have?", back: "Three: superior, middle, and inferior.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["480M alveoli", "Diaphragm driven", "Surfactant prevents collapse"],
      keyTerms: [{ term: "Alveoli", definition: "Site of gas exchange." }],
      summary: "Lungs maintain arterial oxygenation and blood pH via CO2 elimination.",
    },
    xpPoints: 180,
    achievementBadge: { id: "pulmo-master", title: "Pulmonology Scholar", description: "Mastered lung anatomy", icon: "human-body", xpReward: 180 },
    verification: { status: "published", version: "1.0.0" },
    references: ["West's Respiratory Physiology"],
    furtherReading: ["Murray and Nadel's Textbook of Respiratory Medicine"],
    existingRoute: "/human-body",
  },
  {
    id: "liver",
    name: "Liver",
    scientificName: "Hepar",
    category: "human-anatomy",
    subcategory: "Digestive System",
    icon: "human-body",
    accentColor: "#D97706",
    description: "The liver is the body's largest internal metabolic organ, performing >500 essential functions including blood filtration, toxin breakdown, protein synthesis, and bile secretion.",
    difficulty: "intermediate",
    estimatedMinutes: 15,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain hepatic lobule structure and portal circulation", icon: "human-body" },
      { text: "Describe bile production and detoxification pathways", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Hepatocyte", definition: "Primary metabolic parenchymal cell of the liver." },
      { term: "Hepatic Portal Vein", definition: "Vessel supplying nutrient-rich blood from GI tract to liver." },
      { term: "Bile", definition: "Digestive fluid emulsifying fats in the duodenum." },
    ],
    summary: "Receives dual blood supply (hepatic artery & portal vein). Filters 1.4 L/min. Capable of remarkable cellular regeneration.",
    quickRevision: [
      "Functions: Detoxification, glycogen storage, plasma protein synthesis (albumin), bile production.",
      "Dual blood supply: 75% portal vein (nutrients), 25% hepatic artery (O2).",
      "Can regenerate full size from just 25% original tissue mass.",
    ],
    interestingFacts: [
      "The liver is the only internal human organ capable of natural regeneration!",
    ],
    commonMisconceptions: [
      "Misconception: Alcohol is the only cause of liver damage. Reality: Fatty liver disease and viral hepatitis are equally major causes.",
    ],
    scientists: [
      { name: "Marcello Malpighi", contribution: "Described liver lobular microanatomy", year: "1666" },
    ],
    timeline: [
      { year: "1666", title: "Liver Microanatomy", description: "Malpighi described hepatic lobules and sinusoids." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#D97706" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain liver metabolic functions, portal vein anatomy, detoxification, and bile flow.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["gallbladder", "stomach", "pancreas"],
    prerequisiteIds: [],
    nextTopicIds: ["gallbladder"],
    relatedDiseaseIds: ["cirrhosis", "hepatitis", "fatty-liver"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["gallbladder", "stomach"],
    relatedCellIds: ["hepatocyte", "kupffer-cell"],
    relatedSimulationIds: ["metabolism-sim"],
    relatedVirtualLabIds: ["liver-function-lab"],
    relatedResearchIds: ["hepatocyte-regeneration-paper"],
    clinicalImportance: "Cirrhosis and non-alcoholic fatty liver disease affect millions globally.",
    realWorldApplications: ["Liver enzyme blood panels (ALT/AST)", "Living donor liver transplantation"],
    quiz: {
      id: "liver-quiz",
      title: "Liver Quiz",
      questions: [
        { text: "What vessel carries nutrient-rich blood from GI tract to liver?", options: ["Hepatic Artery", "Hepatic Portal Vein", "Celiac Trunk", "Jugular Vein"], answerIndex: 1, explanation: "Hepatic portal vein carries absorbed nutrients from intestines directly to hepatocytes." },
      ],
    },
    flashcards: [
      { id: "fc-liver-1", front: "What percentage of liver blood comes from the portal vein?", back: "~75% carrying nutrients from stomach and intestines.", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["500+ chemical jobs", "Dual blood supply", "High regenerative capacity"],
      keyTerms: [{ term: "Bile", definition: "Fat emulsifier stored in gallbladder." }],
      summary: "Liver acts as metabolic hub for detoxification and nutrient synthesis.",
    },
    xpPoints: 190,
    achievementBadge: { id: "hepa-master", title: "Hepatology Scholar", description: "Mastered liver anatomy", icon: "human-body", xpReward: 190 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Zakim and Boyer's Hepatology"],
    furtherReading: ["Schiff's Diseases of the Liver"],
    existingRoute: "/human-body",
  },
  {
    id: "stomach",
    name: "Stomach",
    scientificName: "Gaster",
    category: "human-anatomy",
    subcategory: "Digestive System",
    icon: "human-body",
    accentColor: "#10B981",
    description: "A muscular J-shaped digestive organ that churns food into chyme using gastric juices containing hydrochloric acid (pH 1.5-2.0) and digestive enzymes.",
    difficulty: "beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    learningObjectives: [
      { text: "Identify stomach regions: cardia, fundus, body, pylorus", icon: "human-body" },
      { text: "Explain parietal cell acid secretion and mucosal protection", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Chyme", definition: "Semi-fluid mass of partially digested food expelled into duodenum." },
      { term: "Parietal Cells", definition: "Gastric pit cells secreting hydrochloric acid (HCl)." },
      { term: "Pyloric Sphincter", definition: "Smooth muscle valve regulating chyme entry to intestine." },
    ],
    summary: "Stomach churns food, digests proteins via pepsin, and releases chyme incrementally via pylorus.",
    quickRevision: [
      "pH 1.5-2.0 breaks down food and kills ingested pathogens.",
      "Protected by alkaline mucus barrier.",
      "Chief cells secrete pepsinogen → activated by HCl to pepsin.",
    ],
    interestingFacts: [
      "Stomach lining completely replaces itself every 3 to 5 days to prevent auto-digestion!",
    ],
    commonMisconceptions: [
      "Misconception: Stress causes most stomach ulcers. Reality: ~80% of peptic ulcers are caused by H. pylori bacterial infection.",
    ],
    scientists: [
      { name: "William Beaumont", contribution: "Pioneered gastric physiology observations", year: "1833" },
      { name: "Barry Marshall", contribution: "Discovered H. pylori causes peptic ulcers", year: "2005 Nobel" },
    ],
    timeline: [
      { year: "2005", title: "H. pylori Discovery", description: "Marshall & Warren awarded Nobel Prize for ulcer discovery." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#10B981" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain stomach anatomy, HCl secretion, gastric motility, and mucosal barrier.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["esophagus", "intestines", "liver"],
    prerequisiteIds: [],
    nextTopicIds: ["intestines"],
    relatedDiseaseIds: ["gastric-ulcer", "gerd", "gastritis"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["esophagus", "intestines"],
    relatedCellIds: ["parietal-cell"],
    relatedSimulationIds: ["digestion-sim"],
    relatedVirtualLabIds: ["gastric-ph-lab"],
    relatedResearchIds: ["h-pylori-paper"],
    clinicalImportance: "GERD, peptic ulcer disease, and gastric adenocarcinoma are frequent clinical presentations.",
    realWorldApplications: ["Proton pump inhibitor therapeutics (PPIs)", "Endoscopic gastroscopy"],
    quiz: {
      id: "stomach-quiz",
      title: "Stomach Quiz",
      questions: [
        { text: "What do stomach parietal cells secrete?", options: ["Pepsinogen", "Hydrochloric acid", "Bile", "Insulin"], answerIndex: 1, explanation: "Parietal cells secrete HCl to create acidic gastric pH." },
      ],
    },
    flashcards: [
      { id: "fc-stomach-1", front: "What enzyme breaks down proteins in the stomach?", back: "Pepsin (activated from pepsinogen by HCl).", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Acidic pH 1.5-2.0", "Protein breakdown", "Pyloric sphincter regulates emptying"],
      keyTerms: [{ term: "Chyme", definition: "Partially digested food liquid." }],
      summary: "Stomach prepares ingested nutrients for intestinal absorption.",
    },
    xpPoints: 160,
    achievementBadge: { id: "gastro-master", title: "Gastroenterology Scholar", description: "Mastered stomach anatomy", icon: "human-body", xpReward: 160 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Sleisenger and Fordtran's Gastrointestinal Disease"],
    furtherReading: ["Textbook of Gastroenterology"],
    existingRoute: "/human-body",
  },
  {
    id: "intestines",
    name: "Intestines",
    scientificName: "Intestinum",
    category: "human-anatomy",
    subcategory: "Digestive System",
    icon: "human-body",
    accentColor: "#3B82F6",
    description: "The small intestine (20 ft) absorbs water and nutrients via intestinal villi, while the large intestine (5 ft) absorbs water, consolidates waste, and houses trillions of gut microbiota.",
    difficulty: "intermediate",
    estimatedMinutes: 16,
    prerequisites: [],
    learningObjectives: [
      { text: "Differentiate duodenum, jejunum, ileum, and colon regions", icon: "human-body" },
      { text: "Explain villi surface area expansion and gut microbiome symbiosis", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Villi & Microvilli", definition: "Microscopic finger-like projections maximizing absorption area to 250 m²." },
      { term: "Microbiome", definition: "Trillions of symbiotic bacteria synthesising vitamins and modulating immunity." },
      { term: "Peristalsis", definition: "Rhythmic smooth muscle waves propelling luminal contents forward." },
    ],
    summary: "Small intestine absorbs 90% of nutrients. Large intestine absorbs remaining water and hosts gut flora.",
    quickRevision: [
      "Small intestine sections: Duodenum → Jejunum → Ileum.",
      "Large intestine sections: Cecum → Colon (ascending, transverse, descending, sigmoid) → Rectum.",
      "Gut mucosal surface area equals ~250 square meters.",
    ],
    interestingFacts: [
      "Your gut contains more bacterial cells than total human cells in your entire body!",
    ],
    commonMisconceptions: [
      "Misconception: Digestion occurs mostly in the stomach. Reality: Most nutrient absorption occurs in the small intestine.",
    ],
    scientists: [
      { name: "Ilya Metchnikoff", contribution: "Discovered gut microbiota health benefits", year: "1908 Nobel" },
    ],
    timeline: [
      { year: "1908", title: "Microbiome Concept", description: "Metchnikoff proposed gut flora enhances longevity." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#3B82F6" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain intestinal absorption, villi microanatomy, peristalsis, and gut microbiome health.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["stomach", "liver", "pancreas"],
    prerequisiteIds: [],
    nextTopicIds: ["kidneys"],
    relatedDiseaseIds: ["crohns", "celiac", "colon-cancer"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["stomach", "liver"],
    relatedCellIds: ["enterocyte", "goblet-cell"],
    relatedSimulationIds: ["nutrient-absorption-sim"],
    relatedVirtualLabIds: ["microbiome-lab"],
    relatedResearchIds: ["gut-brain-axis-paper"],
    clinicalImportance: "Inflammatory bowel disease (IBD) and colorectal cancer represent significant global healthcare burdens.",
    realWorldApplications: ["Colonoscopy screening", "Probiotic microflora therapies"],
    quiz: {
      id: "intestines-quiz",
      title: "Intestines Quiz",
      questions: [
        { text: "Where does the majority of nutrient absorption occur?", options: ["Stomach", "Small Intestine", "Large Intestine", "Esophagus"], answerIndex: 1, explanation: "Small intestine villi absorb ~90% of ingested nutrients." },
      ],
    },
    flashcards: [
      { id: "fc-gut-1", front: "What are the three parts of the small intestine?", back: "Duodenum, jejunum, and ileum.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["250 m² surface area", "Villi and microvilli", "Trillions of microbiome flora"],
      keyTerms: [{ term: "Peristalsis", definition: "Wavelike intestinal smooth muscle contraction." }],
      summary: "Intestines perform final nutrient extraction and waste consolidation.",
    },
    xpPoints: 190,
    achievementBadge: { id: "enteric-master", title: "Enterology Scholar", description: "Mastered intestinal anatomy", icon: "human-body", xpReward: 190 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Yamada's Textbook of Gastroenterology"],
    furtherReading: ["Physiology of the Gastrointestinal Tract"],
    existingRoute: "/human-body",
  },
  {
    id: "kidneys",
    name: "Kidneys",
    scientificName: "Renes",
    category: "human-anatomy",
    subcategory: "Urinary System",
    icon: "human-body",
    accentColor: "#8B5CF6",
    description: "Paired retroperitoneal organs containing ~2 million nephrons that filter 180 liters of fluid daily to regulate blood pressure, electrolyte levels, blood pH, and waste excretion.",
    difficulty: "advanced",
    estimatedMinutes: 18,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe nephron architecture: glomerulus, PCT, Loop of Henle, DCT, CD", icon: "human-body" },
      { text: "Explain countercurrent multiplication and RAAS blood pressure regulation", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Nephron", definition: "Functional microscopic filtration unit of the kidney." },
      { term: "Glomerular Filtration Rate (GFR)", definition: "Volume of fluid filtered per minute (~125 mL/min)." },
      { term: "Erythropoietin (EPO)", definition: "Hormone secreted by kidneys stimulating RBC production." },
    ],
    summary: "Kidneys filter blood to generate urine, maintaining fluid balance, electrolyte concentration, and arterial blood pressure via RAAS.",
    quickRevision: [
      "Filter 180 liters of fluid per day; produce ~1.5 L urine.",
      "Nephron steps: Ultrafiltration (glomerulus) → Reabsorption (PCT/loop) → Secretion (DCT) → Excretion.",
      "RAAS system: Renin → Angiotensin II → Aldosterone.",
    ],
    interestingFacts: [
      "Kidneys represent only 0.5% of body weight but receive 20-25% of resting cardiac output!",
    ],
    commonMisconceptions: [
      "Misconception: Drinking excess water cleanses kidneys infinitely. Reality: Overhydration can cause life-threatening hyponatremia.",
    ],
    scientists: [
      { name: "Sir William Bowman", contribution: "Discovered Bowman's capsule in nephrons", year: "1842" },
    ],
    timeline: [
      { year: "1842", title: "Nephron Microanatomy", description: "Bowman described the glomerular capsule." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#8B5CF6" },
    simulationUrl: "/process-simulations",
    virtualLabUrl: "/virtual-lab",
    askAiPrompt: "Explain kidney nephron physiology, GFR, countercurrent exchange, and RAAS cascade.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["bladder", "heart", "adrenal"],
    prerequisiteIds: [],
    nextTopicIds: ["bladder"],
    relatedDiseaseIds: ["chronic-kidney-disease", "kidney-stones", "glomerulonephritis"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["bladder", "adrenal"],
    relatedCellIds: ["podocyte"],
    relatedSimulationIds: ["nephron-filtration-sim"],
    relatedVirtualLabIds: ["dialysis-lab"],
    relatedResearchIds: ["renal-regeneration-study"],
    clinicalImportance: "Chronic kidney disease (CKD) affects over 10% of global population requiring hemodialysis or transplant.",
    realWorldApplications: ["Hemodialysis machines", "Serum creatinine GFR calculations"],
    quiz: {
      id: "kidneys-quiz",
      title: "Kidneys Quiz",
      questions: [
        { text: "What is the functional unit of the kidney?", options: ["Alveolus", "Nephron", "Neuron", "Lobule"], answerIndex: 1, explanation: "Nephron is the microscopic functional filtration unit (~1M per kidney)." },
      ],
    },
    flashcards: [
      { id: "fc-kidney-1", front: "What hormone do kidneys release to stimulate red blood cell production?", back: "Erythropoietin (EPO).", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["2 Million nephrons", "Filters 180 L/day", "Secretes EPO and Renin"],
      keyTerms: [{ term: "GFR", definition: "Glomerular filtration rate." }],
      summary: "Kidneys control homeostatic electrolyte balance and blood pressure.",
    },
    xpPoints: 210,
    achievementBadge: { id: "nephro-master", title: "Nephrology Scholar", description: "Mastered renal physiology", icon: "human-body", xpReward: 210 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Brenner and Rector's The Kidney"],
    furtherReading: ["Renal Physiology 6th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "bladder",
    name: "Bladder",
    scientificName: "Vesica Urinaria",
    category: "human-anatomy",
    subcategory: "Urinary System",
    icon: "human-body",
    accentColor: "#FBBF24",
    description: "A distensible pelvic muscular organ lined with transitional urothelium that collects, stores, and expels urine (capacity 400-600 mL) via detrusor muscle voiding.",
    difficulty: "beginner",
    estimatedMinutes: 10,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain detrusor muscle function and micturition reflex", icon: "human-body" },
    ],
    importantTerms: [
      { term: "Detrusor Muscle", definition: "Smooth muscle wall contracting during urination." },
      { term: "Urothelium", definition: "Specialised transitional epithelium stretching without rupturing." },
    ],
    summary: "Stores urine received from ureters and contracts via autonomic parasympathetic stimulation during micturition.",
    quickRevision: [
      "Capacity ~400-600 mL; urge triggers at ~150-200 mL.",
      "Internal sphincter (involuntary) vs External sphincter (voluntary).",
    ],
    interestingFacts: [
      "The bladder's urothelium can expand to over twice its relaxed surface area!",
    ],
    commonMisconceptions: [
      "Misconception: Holding urine damages bladder permanently. Reality: Causes discomfort; true rupture is exceedingly rare.",
    ],
    scientists: [
      { name: "Galen", contribution: "First recorded urinary sphincter function", year: "170 AD" },
    ],
    timeline: [
      { year: "170 AD", title: "Urinary Physiology", description: "Galen demonstrated urine passage from kidney to bladder." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#FBBF24" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain bladder micturition reflex, urothelium histology, and detrusor innervation.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["kidneys"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["cystitis", "overactive-bladder", "bladder-cancer"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["kidneys"],
    relatedCellIds: ["urothelial-cell"],
    relatedSimulationIds: ["micturition-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Urinary tract infections (UTIs) and incontinence are common clinical conditions.",
    realWorldApplications: ["Foley catheterization", "Urodynamic studies"],
    quiz: {
      id: "bladder-quiz",
      title: "Bladder Quiz",
      questions: [
        { text: "What muscle wall contracts to void urine from the bladder?", options: ["Diaphragm", "Detrusor", "Myometrium", "Pectoralis"], answerIndex: 1, explanation: "Detrusor smooth muscle contracts during micturition." },
      ],
    },
    flashcards: [
      { id: "fc-bladder-1", front: "What tissue lines the interior bladder?", back: "Transitional epithelium (urothelium).", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["Stores 400-600 mL", "Urothelium stretch capacity", "Detrusor muscle driven"],
      keyTerms: [{ term: "Micturition", definition: "Act of urinating." }],
      summary: "Bladder provides controlled storage and voiding of liquid renal waste.",
    },
    xpPoints: 150,
    achievementBadge: { id: "uro-master", title: "Urology Scholar", description: "Mastered bladder anatomy", icon: "human-body", xpReward: 150 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Campbell-Walsh-Wein Urology"],
    furtherReading: ["Basic Science of Urology"],
    existingRoute: "/human-body",
  },
  {
    id: "eyes",
    name: "Eyes",
    scientificName: "Oculi",
    category: "human-anatomy",
    subcategory: "Nervous System",
    icon: "human-body",
    accentColor: "#0EA5E9",
    description: "Complex sensory photoreceptor organs focusing light through cornea and lens onto retina rods (120M) and cones (6M) to generate visual nerve signals.",
    difficulty: "intermediate",
    estimatedMinutes: 14,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe eye tunic layers: sclera, uvea, and retina", icon: "human-body" },
      { text: "Contrast rod photopic and cone scotopic vision", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Retina", definition: "Neural inner layer containing rods (light/dark) and cones (color)." },
      { term: "Fovea Centralis", definition: "Retinal pit with highest cone density for high-acuity vision." },
    ],
    summary: "Transduces light photons into action potentials transmitted via Optic Nerve (CN II) to occipital visual cortex.",
    quickRevision: [
      "Cornea + Lens focus light on retina.",
      "Rods (120M) = Low light vision; Cones (6M) = Color & high detail.",
    ],
    interestingFacts: [
      "The eye can distinguish between 10 million distinct color hues!",
    ],
    commonMisconceptions: [
      "Misconception: Carrots give super human night vision. Reality: Vitamin A prevents night blindness, but won't grant superhuman vision.",
    ],
    scientists: [
      { name: "Hermann von Helmholtz", contribution: "Invented ophthalmoscope and vision theories", year: "1851" },
    ],
    timeline: [
      { year: "1851", title: "Ophthalmoscope Invention", description: "Helmholtz enabled direct visualization of living retina." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#0EA5E9" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain optical refraction, phototransduction cascade, and retinal processing.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["brain"],
    prerequisiteIds: [],
    nextTopicIds: ["ears"],
    relatedDiseaseIds: ["glaucoma", "cataracts", "macular-degeneration"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["brain"],
    relatedCellIds: ["rod-cell", "cone-cell"],
    relatedSimulationIds: ["phototransduction-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Cataracts and glaucoma are leading worldwide causes of preventable blindness.",
    realWorldApplications: ["LASIK refractive surgery", "Fundus photography"],
    quiz: {
      id: "eyes-quiz",
      title: "Eyes Quiz",
      questions: [
        { text: "Which photoreceptors process color vision?", options: ["Rods", "Cones", "Ganglion cells", "Bipolar cells"], answerIndex: 1, explanation: "Cones process photopic color vision (red, green, blue)." },
      ],
    },
    flashcards: [
      { id: "fc-eye-1", front: "What is the optic nerve cranial nerve number?", back: "CN II.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["120M rods + 6M cones", "Cornea provides 2/3 refractive power", "Optic nerve output"],
      keyTerms: [{ term: "Fovea", definition: "Point of sharpest central vision." }],
      summary: "Eyes convert light waves into neural visual imagery.",
    },
    xpPoints: 170,
    achievementBadge: { id: "ophthalmo-master", title: "Ophthalmology Scholar", description: "Mastered eye anatomy", icon: "human-body", xpReward: 170 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Adler's Physiology of the Eye"],
    furtherReading: ["Duane's Ophthalmology"],
    existingRoute: "/human-body",
  },
  {
    id: "ears",
    name: "Ears",
    scientificName: "Aures",
    category: "human-anatomy",
    subcategory: "Nervous System",
    icon: "human-body",
    accentColor: "#F59E0B",
    description: "Sensory organs for auditory acoustic perception and vestibular balance, housing tympanic ossicles (malleus, incus, stapes) and fluid-filled cochlear hair cells.",
    difficulty: "intermediate",
    estimatedMinutes: 14,
    prerequisites: [],
    learningObjectives: [
      { text: "Trace sound vibration: Pinna → Tympanum → Ossicles → Cochlea", icon: "human-body" },
      { text: "Explain vestibular semicircular canal balance mechanism", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Cochlea", definition: "Spiral snail-like organ transducing fluid pressure waves to nerve impulses." },
      { term: "Stapes", definition: "Smallest bone in the human body (~3 mm) transferring vibration to oval window." },
    ],
    summary: "External, middle, and inner ear regions process sound waves (20-20,000 Hz) and dynamic equilibrium.",
    quickRevision: [
      "Middle ear ossicles: Malleus (hammer), Incus (anvil), Stapes (stirrup).",
      "Inner ear: Cochlea (hearing) + Semicircular canals (balance).",
    ],
    interestingFacts: [
      "The stapes bone in your ear is smaller than a single grain of rice!",
    ],
    commonMisconceptions: [
      "Misconception: Earwax is dirt. Reality: Cerumen is protective antibacterial wax secreted by ear glands.",
    ],
    scientists: [
      { name: "Georg von Békésy", contribution: "Discovered cochlear travelling wave mechanics", year: "1961 Nobel" },
    ],
    timeline: [
      { year: "1961", title: "Cochlear Mechanics", description: "Békésy awarded Nobel Prize for auditory research." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#F59E0B" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain ear acoustic conduction, organ of Corti mechanics, and vestibular equilibrium.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["brain"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["otitis-media", "tinnitus", "menieres-disease"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["brain"],
    relatedCellIds: ["hair-cell"],
    relatedSimulationIds: ["auditory-transduction-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Conductive and sensorineural hearing loss impact hundreds of millions worldwide.",
    realWorldApplications: ["Cochlear implant prosthetics", "Audiometric hearing checks"],
    quiz: {
      id: "ears-quiz",
      title: "Ears Quiz",
      questions: [
        { text: "What is the smallest bone in the human body?", options: ["Femur", "Malleus", "Incus", "Stapes"], answerIndex: 3, explanation: "Stapes (stirrup bone in middle ear) is ~3 mm." },
      ],
    },
    flashcards: [
      { id: "fc-ear-1", front: "What structure in the ear is responsible for sense of balance?", back: "Semicircular canals and vestibule.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["Ossicles amplify sound", "Cochlea transduces fluid waves", "Vestibule maintains balance"],
      keyTerms: [{ term: "Organ of Corti", definition: "Sensory hair cell receptor organ." }],
      summary: "Ears provide acoustic sensory perception and spatial posture balance.",
    },
    xpPoints: 160,
    achievementBadge: { id: "oto-master", title: "Otology Scholar", description: "Mastered ear anatomy", icon: "human-body", xpReward: 160 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Ballenger's Otorhinolaryngology"],
    furtherReading: ["Physiology of the Auditory System"],
    existingRoute: "/human-body",
  },
  {
    id: "thyroid",
    name: "Thyroid Gland",
    scientificName: "Glandula Thyroidea",
    category: "human-anatomy",
    subcategory: "Endocrine System",
    icon: "human-body",
    accentColor: "#EF4444",
    description: "Butterfly-shaped endocrine gland in anterior neck secreting thyroxine (T4), triiodothyronine (T3), and calcitonin to govern systemic basal metabolic rate and calcium homeostasis.",
    difficulty: "intermediate",
    estimatedMinutes: 12,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain hypothalamic-pituitary-thyroid (HPT) axis feedback loop", icon: "human-body" },
    ],
    importantTerms: [
      { term: "Thyroxine (T4)", definition: "Primary iodine-containing metabolic hormone produced by thyroid follicles." },
      { term: "TSH", definition: "Thyroid Stimulating Hormone released by anterior pituitary gland." },
    ],
    summary: "Governs basal metabolic rate, oxygen consumption, and protein synthesis throughout human cells.",
    quickRevision: [
      "TRH (Hypothalamus) → TSH (Pituitary) → T3/T4 (Thyroid).",
      "Requires dietary iodine for thyroid hormone synthesis.",
      "Parafollicular C-cells secrete calcitonin (lowers blood calcium).",
    ],
    interestingFacts: [
      "The thyroid holds over 80% of all iodine in the entire human body!",
    ],
    commonMisconceptions: [
      "Misconception: Hypothyroidism causes massive weight gain. Reality: Usually causes 5-10 lbs of fluid/metabolic weight change, not obesity.",
    ],
    scientists: [
      { name: "Edward Calvin Kendall", contribution: "Isolated thyroxine hormone", year: "1914" },
    ],
    timeline: [
      { year: "1914", title: "Thyroxine Isolation", description: "Kendall crystallized pure thyroxine." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#EF4444" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain HPT axis, T3/T4 synthesis, iodine metabolism, and thyroid feedback.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["pituitary", "adrenal"],
    prerequisiteIds: [],
    nextTopicIds: ["pituitary"],
    relatedDiseaseIds: ["hypothyroidism", "hyperthyroidism", "graves-disease"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["pituitary"],
    relatedCellIds: ["follicular-cell"],
    relatedSimulationIds: ["hpt-axis-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Hypothyroidism and Hashimoto's thyroiditis affect millions worldwide.",
    realWorldApplications: ["Levothyroxine hormone replacement therapy", "TSH blood screening tests"],
    quiz: {
      id: "thyroid-quiz",
      title: "Thyroid Quiz",
      questions: [
        { text: "Which element is essential for thyroid hormone synthesis?", options: ["Iron", "Iodine", "Zinc", "Calcium"], answerIndex: 1, explanation: "Iodine is required to synthesize T3 and T4 hormones." },
      ],
    },
    flashcards: [
      { id: "fc-thyroid-1", front: "What hormone stimulates the thyroid to produce T3 and T4?", back: "TSH (Thyroid Stimulating Hormone) from pituitary.", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Controls metabolic rate", "Requires iodine", "HPT negative feedback loop"],
      keyTerms: [{ term: "TSH", definition: "Pituitary hormone driving thyroid activity." }],
      summary: "Thyroid governs metabolic cellular energy usage.",
    },
    xpPoints: 160,
    achievementBadge: { id: "thyro-master", title: "Thyroid Scholar", description: "Mastered thyroid anatomy", icon: "human-body", xpReward: 160 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Werner & Ingbar's The Thyroid"],
    furtherReading: ["Endocrinology 7th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "adrenal",
    name: "Adrenal Glands",
    scientificName: "Glandulae Suprarenales",
    category: "human-anatomy",
    subcategory: "Endocrine System",
    icon: "human-body",
    accentColor: "#FBBF24",
    description: "Pyramidal glands atop both kidneys with an outer cortex (cortisol, aldosterone, androgens) and inner medulla (adrenaline/noradrenaline fight-or-flight response).",
    difficulty: "intermediate",
    estimatedMinutes: 14,
    prerequisites: [],
    learningObjectives: [
      { text: "Differentiate adrenal cortex layers: Zona glomerulosa, fasciculata, reticularis", icon: "human-body" },
      { text: "Explain sympathetic catecholamine release during acute stress", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Cortisol", definition: "Glucocorticoid stress hormone regulating glucose metabolism and immune response." },
      { term: "Aldosterone", definition: "Mineralocorticoid maintaining sodium/water retention in kidneys." },
      { term: "Adrenaline (Epinephrine)", definition: "Catecholamine driving rapid sympathetic fight-or-flight reaction." },
    ],
    summary: "Adrenal glands govern acute stress (medulla) and chronic metabolic/electrolyte balance (cortex).",
    quickRevision: [
      "Adrenal Cortex: Glomerulosa (Aldosterone), Fasciculata (Cortisol), Reticularis (Androgens).",
      "Adrenal Medulla: Epinephrine (80%) & Norepinephrine (20%).",
    ],
    interestingFacts: [
      "Adrenaline can trigger instantaneous blood flow redirection from internal organs to skeletal muscles in milliseconds!",
    ],
    commonMisconceptions: [
      "Misconception: 'Adrenal fatigue' is a recognized medical diagnosis. Reality: Not recognized by endocrinology societies; adrenal insufficiency (Addison's) is a real medical disorder.",
    ],
    scientists: [
      { name: "Thomas Addison", contribution: "Described primary adrenal insufficiency", year: "1855" },
    ],
    timeline: [
      { year: "1855", title: "Addison's Disease", description: "Thomas Addison described destructive adrenal lesions." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#FBBF24" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain adrenal steroidogenesis, HPA axis, cortisol circadian rhythm, and catecholamines.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["kidneys", "pituitary"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["addisons-disease", "cushings-syndrome", "pheochromocytoma"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["kidneys", "pituitary"],
    relatedCellIds: ["chromaffin-cell"],
    relatedSimulationIds: ["stress-response-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Addisonian crisis and Cushing's syndrome are serious endocrine conditions.",
    realWorldApplications: ["EpiPen emergency anaphylaxis therapy", "Exogenous corticosteroid anti-inflammatories"],
    quiz: {
      id: "adrenal-quiz",
      title: "Adrenal Glands Quiz",
      questions: [
        { text: "Which hormone is secreted by the adrenal medulla during acute stress?", options: ["Aldosterone", "Cortisol", "Adrenaline", "Insulin"], answerIndex: 2, explanation: "Adrenal medulla secretes adrenaline (epinephrine) for fight-or-flight." },
      ],
    },
    flashcards: [
      { id: "fc-adrenal-1", front: "What does aldosterone regulate?", back: "Sodium retention and potassium excretion in kidney distal tubules.", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Dual cortex & medulla", "Cortisol stress control", "Aldosterone electrolyte balance"],
      keyTerms: [{ term: "Cortisol", definition: "Primary glucocorticoid stress hormone." }],
      summary: "Adrenals coordinate endocrine and autonomic stress adaptation.",
    },
    xpPoints: 170,
    achievementBadge: { id: "adreno-master", title: "Adrenal Scholar", description: "Mastered adrenal anatomy", icon: "human-body", xpReward: 170 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Williams Textbook of Endocrinology"],
    furtherReading: ["Adrenal Cortex & Medulla Physiology"],
    existingRoute: "/human-body",
  },
  {
    id: "pituitary",
    name: "Pituitary Gland",
    scientificName: "Hypophysis",
    category: "human-anatomy",
    subcategory: "Endocrine System",
    icon: "human-body",
    accentColor: "#A855F7",
    description: "The 'master gland' housed in skull sella turcica, secreting 9 key hormones (GH, TSH, ACTH, FSH, LH, Prolactin, MSH, Oxytocin, ADH) to direct thyroid, adrenals, gonads, and growth.",
    difficulty: "advanced",
    estimatedMinutes: 16,
    prerequisites: [],
    learningObjectives: [
      { text: "Differentiate anterior adenohypophysis and posterior neurohypophysis lobes", icon: "human-body" },
    ],
    importantTerms: [
      { term: "Adenohypophysis", definition: "Anterior lobe synthesizing GH, TSH, ACTH, FSH, LH, and PRL." },
      { term: "Neurohypophysis", definition: "Posterior lobe storing oxytocin and ADH from hypothalamus." },
    ],
    summary: "Pea-sized master gland orchestrating thyroid, adrenal, reproductive, and growth endocrine axes.",
    quickRevision: [
      "Anterior Pituitary: GH, TSH, ACTH, FSH, LH, Prolactin.",
      "Posterior Pituitary: Vasopressin (ADH) & Oxytocin.",
    ],
    interestingFacts: [
      "Despite its huge control over your entire body, the pituitary gland is only the size of a single pea!",
    ],
    commonMisconceptions: [
      "Misconception: Pituitary works independently. Reality: It is strictly controlled by hypothalamic neurohormones.",
    ],
    scientists: [
      { name: "Andrew Schally", contribution: "Discovered hypothalamic control of pituitary hormones", year: "1977 Nobel" },
    ],
    timeline: [
      { year: "1977", title: "Neuroendocrinology Nobel", description: "Schally and Guillemin decoded hypothalamic peptide releasing factors." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#A855F7" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain pituitary adenohypophysis vs neurohypophysis, trophic hormones, and feedback loops.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["brain", "thyroid", "adrenal"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["pituitary-adenoma", "acromegaly", "diabetes-insipidus"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["brain", "thyroid", "adrenal"],
    relatedCellIds: ["somatotropes"],
    relatedSimulationIds: ["endocrine-axis-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Pituitary adenomas cause hormonal hypersecretion or optic chiasm compression visual field deficits.",
    realWorldApplications: ["Transsphenoidal pituitary surgery", "Recombinant Human Growth Hormone (rhGH) therapy"],
    quiz: {
      id: "pituitary-quiz",
      title: "Pituitary Quiz",
      questions: [
        { text: "Where is the pituitary gland located?", options: ["Neck", "Sella turcica of skull", "Abdomen", "Pelvis"], answerIndex: 1, explanation: "Rests in the sella turcica bone cavity at base of brain." },
      ],
    },
    flashcards: [
      { id: "fc-pit-1", front: "What two hormones are stored in posterior pituitary?", back: "Oxytocin and ADH (Vasopressin).", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Master endocrine gland", "Pea-sized structure", "Anterior vs. posterior lobes"],
      keyTerms: [{ term: "ADH", definition: "Anti-diuretic hormone regulating water retention." }],
      summary: "Pituitary coordinates systemic hormonal secretion.",
    },
    xpPoints: 200,
    achievementBadge: { id: "pitu-master", title: "Endocrinology Scholar", description: "Mastered pituitary anatomy", icon: "human-body", xpReward: 200 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Melmed's The Pituitary"],
    furtherReading: ["Clinical Endocrinology 5th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "spleen",
    name: "Spleen",
    scientificName: "Lien",
    category: "human-anatomy",
    subcategory: "Lymphatic System",
    icon: "human-body",
    accentColor: "#6B21A8",
    description: "Largest lymphatic organ (left upper abdomen) featuring red pulp (filters senescent red blood cells) and white pulp (initiates immune antibody responses).",
    difficulty: "intermediate",
    estimatedMinutes: 11,
    prerequisites: [],
    learningObjectives: [
      { text: "Contrast red pulp erythrocyte recycling and white pulp lymphoid immune surveillance", icon: "human-body" },
    ],
    importantTerms: [
      { term: "Red Pulp", definition: "Splenic sinusoids removing old or damaged RBCs and storing platelets." },
      { term: "White Pulp", definition: "Lymphoid follicles mounting B and T cell adaptive immune responses." },
    ],
    summary: "Filters circulating blood, recycles iron from aged RBCs, and mounts adaptive systemic immunity.",
    quickRevision: [
      "Filters whole blood (unlike lymph nodes which filter lymph).",
      "Red pulp = Macrophages destroy old RBCs (~120 day lifespan).",
      "White pulp = Immune response to blood-borne pathogens.",
    ],
    interestingFacts: [
      "The spleen holds an emergency reservoir of up to 1 cup of concentrated blood!",
    ],
    commonMisconceptions: [
      "Misconception: You cannot survive without a spleen. Reality: Asplenic patients survive well, though face higher encapsulated bacteria infection risks.",
    ],
    scientists: [
      { name: "Marcello Malpighi", contribution: "Discovered splenic white pulp follicles", year: "1669" },
    ],
    timeline: [
      { year: "1669", title: "Splenic Malpighian Corpuscles", description: "First detailed description of white pulp." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#6B21A8" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain spleen red pulp vs white pulp, macrophage culling of RBCs, and post-splenectomy risks.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["lymph-nodes", "bone-marrow", "heart"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["splenomegaly", "splenic-rupture", "asplenia"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["lymph-nodes", "bone-marrow"],
    relatedCellIds: ["splenic-macrophage"],
    relatedSimulationIds: ["immune-response-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Blunt abdominal trauma can cause life-threatening splenic rupture hemorrhage.",
    realWorldApplications: ["Post-splenectomy Pneumococcal vaccinations", "Abdominal ultrasound evaluation"],
    quiz: {
      id: "spleen-quiz",
      title: "Spleen Quiz",
      questions: [
        { text: "What is the primary function of splenic red pulp?", options: ["Hormone production", "Recycling old red blood cells", "Biliary storage", "Gas exchange"], answerIndex: 1, explanation: "Red pulp filters and recycles senescent RBCs." },
      ],
    },
    flashcards: [
      { id: "fc-spleen-1", front: "What does splenic white pulp contain?", back: "Lymphocytes (B and T cells) for blood immune surveillance.", category: "Anatomy" },
    ],
    revisionNotes: {
      importantPoints: ["Largest lymphoid organ", "Red pulp (RBC culling) vs White pulp (Immunity)", "Platelet storage site"],
      keyTerms: [{ term: "Splenectomy", definition: "Surgical removal of spleen." }],
      summary: "Spleen cleans blood and defends against systemic bacteremia.",
    },
    xpPoints: 150,
    achievementBadge: { id: "spleno-master", title: "Splenology Scholar", description: "Mastered spleen anatomy", icon: "human-body", xpReward: 150 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Janeway's Immunobiology"],
    furtherReading: ["Spleen Physiology & Pathology"],
    existingRoute: "/human-body",
  },
  {
    id: "skeleton",
    name: "Skeletal System",
    scientificName: "Systema Sceletale",
    category: "human-anatomy",
    subcategory: "Skeletal System",
    icon: "human-body",
    accentColor: "#E2E8F0",
    description: "The 206 bones of the human body providing structural framework, organ protection, mineral storage (99% calcium), and hematopoiesis bone marrow site.",
    difficulty: "beginner",
    estimatedMinutes: 15,
    prerequisites: [],
    learningObjectives: [
      { text: "Distinguish axial skeleton (80 bones) and appendicular skeleton (126 bones)", icon: "human-body" },
      { text: "Explain osteoblast bone formation and osteoclast resorption remodeling", icon: "virtual-lab" },
    ],
    importantTerms: [
      { term: "Axial Skeleton", definition: "Skull, vertebral column, ribs, and sternum protecting central organs." },
      { term: "Appendicular Skeleton", definition: "Pectoral and pelvic girdles plus upper and lower limb bones." },
      { term: "Osteon", definition: "Concentric structural Haversian unit of compact bone." },
    ],
    summary: "206 bones connected by joints and ligaments, storing calcium and producing blood cells in red bone marrow.",
    quickRevision: [
      "206 total bones in adult skeleton (babies born with ~270 fused over time).",
      "Osteoblasts build bone; Osteoclasts break down bone; Osteocytes maintain bone tissue.",
    ],
    interestingFacts: [
      "Bone is ounce-for-ounce stronger than steel in resisting compression forces!",
    ],
    commonMisconceptions: [
      "Misconception: Bones are dry dead tissue. Reality: Bones are highly vascular, living, continuously remodeling tissues.",
    ],
    scientists: [
      { name: "Clopton Havers", contribution: "Described microscopic bone canal structures (Haversian canals)", year: "1691" },
    ],
    timeline: [
      { year: "1691", title: "Haversian Canals", description: "Havers published microscopic bone vascular architecture." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#E2E8F0" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain bone remodeling cycle, axial vs appendicular skeleton, and calcium homeostasis.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["muscles", "bone-marrow"],
    prerequisiteIds: [],
    nextTopicIds: ["muscles"],
    relatedDiseaseIds: ["osteoporosis", "fractures", "osteoarthritis"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["muscles", "bone-marrow"],
    relatedCellIds: ["osteoblast", "osteoclast"],
    relatedSimulationIds: ["bone-remodeling-sim"],
    relatedVirtualLabIds: ["bone-density-lab"],
    relatedResearchIds: [],
    clinicalImportance: "Osteoporosis fractures cause severe morbidity in aging populations.",
    realWorldApplications: ["DEXA bone density scans", "Orthopedic fracture fixation"],
    quiz: {
      id: "skeleton-quiz",
      title: "Skeletal System Quiz",
      questions: [
        { text: "How many bones are in the adult human skeleton?", options: ["180", "206", "270", "300"], answerIndex: 1, explanation: "An adult human has 206 distinct bones." },
      ],
    },
    flashcards: [
      { id: "fc-skel-1", front: "What cells resorb bone tissue?", back: "Osteoclasts.", category: "Histology" },
    ],
    revisionNotes: {
      importantPoints: ["206 Adult bones", "Axial + Appendicular divisions", "Calcium reservoir & hematopoiesis"],
      keyTerms: [{ term: "Osteon", definition: "Functional compact bone unit." }],
      summary: "Skeletal system provides framework, mobility levers, and mineral balance.",
    },
    xpPoints: 180,
    achievementBadge: { id: "skel-master", title: "Osteology Scholar", description: "Mastered skeletal anatomy", icon: "human-body", xpReward: 180 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Orthopaedic Basic Science"],
    furtherReading: ["Skeletal Histology & Physiology"],
    existingRoute: "/human-body",
  },
  {
    id: "muscles",
    name: "Muscular System",
    scientificName: "Systema Musculare",
    category: "human-anatomy",
    subcategory: "Muscular System",
    icon: "human-body",
    accentColor: "#EF4444",
    description: "Over 600 skeletal muscles plus cardiac and smooth muscle tissue responsible for body posture, locomotion, organ motility, and heat generation (thermogenesis).",
    difficulty: "intermediate",
    estimatedMinutes: 16,
    prerequisites: [],
    learningObjectives: [
      { text: "Explain sliding filament theory of actin and myosin sarcomere contraction", icon: "process-simulations" },
      { text: "Compare skeletal (voluntary), cardiac (autonomic striated), and smooth (visceral) muscles", icon: "human-body" },
    ],
    importantTerms: [
      { term: "Sarcomere", definition: "Functional contractile unit of striated muscle bounded by Z-discs." },
      { term: "Myosin & Actin", definition: "Thick and thin motor protein filaments sliding past each other during contraction." },
      { term: "Neuromuscular Junction (NMJ)", definition: "Synapse between motor neuron and muscle fiber using acetylcholine." },
    ],
    summary: "600+ muscles convert ATP chemical energy into mechanical force via sliding actin-myosin crossbridges.",
    quickRevision: [
      "Three muscle types: Skeletal (striated/voluntary), Smooth (nonstriated/involuntary), Cardiac (striated/involuntary).",
      "Contraction requires Calcium (Ca2+) release from sarcoplasmic reticulum.",
    ],
    interestingFacts: [
      "Skeletal muscles generate over 85% of your body's total internal heat when contracting!",
    ],
    commonMisconceptions: [
      "Misconception: Lactic acid causes muscle soreness days later. Reality: Delayed onset muscle soreness (DOMS) is caused by micro-tears in muscle fibers, not persistent lactic acid.",
    ],
    scientists: [
      { name: "Andrew Huxley", contribution: "Proposed sliding filament theory of muscle contraction", year: "1954" },
    ],
    timeline: [
      { year: "1954", title: "Sliding Filament Theory", description: "Huxley & Hanson published sarcomere sliding model." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#EF4444" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain sarcomere structure, sliding filament mechanism, excitation-contraction coupling, and muscle fatigue.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["skeleton", "heart", "nervous"],
    prerequisiteIds: [],
    nextTopicIds: ["skeleton"],
    relatedDiseaseIds: ["muscular-dystrophy", "myasthenia-gravis", "sarcopenia"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["skeleton", "heart"],
    relatedCellIds: ["myocyte"],
    relatedSimulationIds: ["sarcomere-contraction-sim"],
    relatedVirtualLabIds: ["emg-lab"],
    relatedResearchIds: [],
    clinicalImportance: "Myasthenia gravis and muscular dystrophies cause progressive debilitating weakness.",
    realWorldApplications: ["Electromyography (EMG)", "Strength conditioning & rehabilitation"],
    quiz: {
      id: "muscles-quiz",
      title: "Muscular System Quiz",
      questions: [
        { text: "What neurotransmitter is released at the neuromuscular junction?", options: ["Dopamine", "Acetylcholine", "Serotonin", "GABA"], answerIndex: 1, explanation: "Acetylcholine (ACh) binds nicotinic receptors at the NMJ." },
      ],
    },
    flashcards: [
      { id: "fc-musc-1", front: "What ion triggers sarcomere muscle contraction?", back: "Calcium (Ca2+).", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["600+ Skeletal muscles", "Sliding filament theory", "Sarcomere contractile units"],
      keyTerms: [{ term: "Sarcomere", definition: "Contractile unit bounded by Z-lines." }],
      summary: "Muscular system drives movement, posture, and heat generation.",
    },
    xpPoints: 190,
    achievementBadge: { id: "myo-master", title: "Myology Scholar", description: "Mastered muscular anatomy", icon: "human-body", xpReward: 190 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Skeletal Muscle Structure and Function"],
    furtherReading: ["Muscle Physiology 5th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "skin",
    name: "Integumentary System",
    scientificName: "Integumentum Commune",
    category: "human-anatomy",
    subcategory: "Integumentary System",
    icon: "human-body",
    accentColor: "#F5C2A2",
    description: "The body's largest organ by mass (~16% total body weight), consisting of epidermis, dermis, subcutis, keratin, melanin, sweat glands, and cutaneous nerve receptors.",
    difficulty: "beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    learningObjectives: [
      { text: "Describe epidermal layers: Corneum, Lucidum, Granulosum, Spinosum, Basale", icon: "human-body" },
      { text: "Explain thermoregulation, Vitamin D synthesis, and barrier defense", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Epidermis", definition: "Avascular stratified squamous epithelial outer layer with keratinocytes and melanocytes." },
      { term: "Dermis", definition: "Vascular collagenous inner layer housing hair follicles, sweat glands, and nerves." },
      { term: "Melanin", definition: "Pigment produced by melanocytes protecting against ultraviolet DNA damage." },
    ],
    summary: "Provides physical barrier protection, UV protection via melanin, Vitamin D activation, thermoregulation, and cutaneous sensation.",
    quickRevision: [
      "Epidermis (outer keratinized layer) → Dermis (connective tissue & vessels) → Hypodermis (subcutaneous fat).",
      "Sweat gland evaporation cools body; Vasoconstriction retains heat.",
    ],
    interestingFacts: [
      "Your skin sheds approximately 30,000 to 40,000 dead skin cells every single minute!",
    ],
    commonMisconceptions: [
      "Misconception: Pores open and close like doors with hot/cold water. Reality: Pores lack muscle tissue; temperature only changes sweat production and blood flow.",
    ],
    scientists: [
      { name: "Paul Gerson Unna", contribution: "Pioneered dermatological histology and skin pathology", year: "1884" },
    ],
    timeline: [
      { year: "1884", title: "Dermatohistology", description: "Unna published landmark skin microanatomy atlas." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#F5C2A2" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain skin epidermal strata, melanocyte UV defense, thermoregulation, and wound healing.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["nervous", "immune"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["melanoma", "psoriasis", "eczema", "burns"],
    relatedSpeciesIds: [],
    relatedOrganIds: [],
    relatedCellIds: ["keratinocyte", "melanocyte"],
    relatedSimulationIds: ["thermoregulation-sim"],
    relatedResearchIds: [],
    clinicalImportance: "Skin cancers like melanoma require early detection; major burns carry high infection risk.",
    realWorldApplications: ["Dermatoscopic mole mapping", "Skin graft bioengineering"],
    quiz: {
      id: "skin-quiz",
      title: "Integumentary System Quiz",
      questions: [
        { text: "Which epidermal cell type produces protective UV pigment?", options: ["Keratinocyte", "Melanocyte", "Langerhans cell", "Merkel cell"], answerIndex: 1, explanation: "Melanocytes produce melanin pigment." },
      ],
    },
    flashcards: [
      { id: "fc-skin-1", front: "What is the deepest layer of the epidermis?", back: "Stratum basale (contains proliferating stem cells).", category: "Histology" },
    ],
    revisionNotes: {
      importantPoints: ["16% Body weight", "Epidermis, dermis, hypodermis", "UV defense & thermoregulation"],
      keyTerms: [{ term: "Keratin", definition: "Tough structural protein of outer skin." }],
      summary: "Skin forms primary protective barrier against environmental pathogens and moisture loss.",
    },
    xpPoints: 150,
    achievementBadge: { id: "derma-master", title: "Dermatology Scholar", description: "Mastered skin anatomy", icon: "human-body", xpReward: 150 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Rook's Textbook of Dermatology"],
    furtherReading: ["Dermatology 4th Ed"],
    existingRoute: "/human-body",
  },
  {
    id: "reproductive",
    name: "Reproductive System",
    scientificName: "Systema Genitale",
    category: "human-anatomy",
    subcategory: "Reproductive System",
    icon: "human-body",
    accentColor: "#EC4899",
    description: "Male (testes, prostate) and Female (ovaries, uterus) gonadal and tract organs producing haploid gametes (sperm/ova), sex steroid hormones (testosterone/estrogen/progesterone), and supporting human reproduction.",
    difficulty: "intermediate",
    estimatedMinutes: 16,
    prerequisites: [],
    learningObjectives: [
      { text: "Trace gametogenesis: Spermatogenesis vs. Oogenesis meiosis", icon: "virtual-lab" },
      { text: "Explain female menstrual phase cycle and gonadotropin surges (FSH/LH)", icon: "process-simulations" },
    ],
    importantTerms: [
      { term: "Gonads", definition: "Primary reproductive organs (testes/ovaries) producing gametes and sex steroids." },
      { term: "Endometrium", definition: "Uterine mucosal lining thickening during menstrual cycle for blastocyst implantation." },
    ],
    summary: "Differentiated male and female organs producing gametes via meiosis and regulating secondary sexual characteristics.",
    quickRevision: [
      "Hypothalamus GnRH → Pituitary FSH/LH → Gonadal steroid release.",
      "Female cycle: Follicular phase → Ovulation (LH surge) → Luteal phase.",
    ],
    interestingFacts: [
      "Human sperm cells are the smallest cells in the male body, while the human egg cell (ovum) is the largest in the female body!",
    ],
    commonMisconceptions: [
      "Misconception: Fertilization takes place in the uterus. Reality: Fertilization normally occurs in the ampulla of the fallopian tube.",
    ],
    scientists: [
      { name: "Regnier de Graaf", contribution: "Discovered ovarian follicles (Graafian follicles)", year: "1672" },
      { name: "Robert Edwards", contribution: "Developed in vitro fertilization (IVF)", year: "2010 Nobel" },
    ],
    timeline: [
      { year: "1978", title: "First IVF Baby", description: "Birth of Louise Brown via Edwards & Steptoe IVF technique." },
    ],
    images: [],
    infographics: [],
    model3D: { url: "/human-body", accentColor: "#EC4899" },
    simulationUrl: "/process-simulations",
    askAiPrompt: "Explain male/female reproductive anatomy, meiotic gametogenesis, menstrual hormonal cycles, and fertilization.",
    parentTopicId: undefined,
    childTopicIds: [],
    relatedTopicIds: ["pituitary"],
    prerequisiteIds: [],
    nextTopicIds: [],
    relatedDiseaseIds: ["pcos", "endometriosis", "prostate-cancer"],
    relatedSpeciesIds: [],
    relatedOrganIds: ["pituitary"],
    relatedCellIds: ["spermatozoon", "ovum"],
    relatedSimulationIds: ["menstrual-cycle-sim"],
    relatedVirtualLabIds: ["ivf-lab"],
    relatedResearchIds: [],
    clinicalImportance: "Infertility affects 1 in 6 couples globally; PCOS and prostate cancer carry heavy clinical footprints.",
    realWorldApplications: ["In Vitro Fertilization (IVF)", "Hormonal contraception formulations"],
    quiz: {
      id: "reproductive-quiz",
      title: "Reproductive System Quiz",
      questions: [
        { text: "Where does normal fertilization of an egg usually occur?", options: ["Uterus", "Fallopian tube ampulla", "Ovary", "Cervix"], answerIndex: 1, explanation: "Fertilization normally takes place in the fallopian tube ampulla." },
      ],
    },
    flashcards: [
      { id: "fc-repro-1", front: "What pituitary hormone surge triggers ovulation?", back: "Luteinizing Hormone (LH).", category: "Physiology" },
    ],
    revisionNotes: {
      importantPoints: ["Meiotic gametogenesis", "FSH/LH gonadotropin control", "Estrogen/Testosterone synthesis"],
      keyTerms: [{ term: "Endometrium", definition: "Uterine inner mucosal lining." }],
      summary: "Reproductive organs maintain gametogenesis and species propagation.",
    },
    xpPoints: 190,
    achievementBadge: { id: "repro-master", title: "Reproductive Scholar", description: "Mastered reproductive anatomy", icon: "human-body", xpReward: 190 },
    verification: { status: "published", version: "1.0.0" },
    references: ["Yen & Jaffe's Reproductive Endocrinology"],
    furtherReading: ["Knobil and Neill's Physiology of Reproduction"],
    existingRoute: "/human-body",
  },
];
